/**
 * Clinical Vocabulary — Paid-tier expanded word lists for PrismAAC
 *
 * ~600 words per language across 4 categories:
 *   Medical (~150), Clinical/BCBA (~100), Daily Living (~200), Grammar Connectors (~150)
 *
 * Gated to standard / advanced / enterprise plans.
 */
import { SupportedLanguage } from '@/engine/i18n';

// ── English ──────────────────────────────────────────────────────────────────
const en = [
  // Medical (~150)
  'headache','fever','nausea','dizzy','allergy','seizure','breathing','pain','swollen','bleeding','infection','prescription','hospital','clinic','nurse','doctor','wheelchair','therapy','cast','surgery','injection','temperature','cough','rash','bruise','fracture','asthma','diabetes','epilepsy','autism','adhd','anxiety','depression','medication','dosage','symptom','diagnosis','treatment','emergency','ambulance','oxygen','pulse','blood pressure','heart','lungs','stomach','throat','ear','eye','skin','bone','muscle','joint','spine','brain','kidney','liver','vomit','diarrhea','constipation','fatigue','insomnia','migraine','pneumonia','bronchitis','anemia','stroke','tumor','biopsy','x-ray','ultrasound','scan','lab','test','results','pharmacy','tablet','capsule','syrup','inhaler','nebulizer','catheter','bandage','stitches','splint','crutch','walker','hearing aid','glasses','prosthetic','ventilator','monitor','iv','drip','vitals','chart','referral','specialist','pediatrician','neurologist','psychiatrist','cardiologist','dentist','optometrist','surgeon','paramedic','emt','triage','recovery','rehabilitation','physical therapy','occupational therapy','speech therapy','palliative','chronic','acute','contagious','immune','vaccine','booster','antibiotic','antiviral','painkiller','sedative','anesthesia','brace','sling','wheelchair ramp','accessible','disability','impairment','mobility','spasticity','tremor','paralysis','concussion','laceration','burn','wound','abscess','inflammation','swelling','numbness','tingling','shortness of breath','chest pain','abdominal','nauseous','dizzy spell','fainting','allergic reaction','epipen','glucometer','insulin','dialysis','chemotherapy','radiation','prognosis','remission','terminal','hospice','dnr','consent','hipaa','confidential','medical record',
  // Clinical / BCBA (~100)
  'behavior','reinforcement','prompt','stimulus','response','baseline','data','trial','antecedent','consequence','function','escape','attention','tangible','sensory','frequency','duration','latency','interval','generalization','maintenance','extinction','shaping','chaining','modeling','fade','schedule','token','board','assessment','preference','probe','mastery','criterion','graph','trend','target','goal','objective','skill','acquisition','fluency','discrete','natural environment','incidental teaching','pivotal','mand','tact','intraverbal','echoic','listener','receptive','expressive','verbal behavior','functional analysis','functional assessment','abc data','scatter plot','task analysis','backward chaining','forward chaining','total task','prompt hierarchy','least to most','most to least','time delay','errorless','correction','differential reinforcement','dra','dro','dri','drl','ncr','motivating operation','establishing operation','abolishing operation','discriminative stimulus','conditioned reinforcer','unconditioned reinforcer','primary reinforcer','secondary reinforcer','variable ratio','fixed ratio','variable interval','fixed interval','cumulative record','interobserver agreement','ioa','treatment integrity','social validity','single subject','multiple baseline','reversal design','alternating treatment','changing criterion','visual analysis','celeration','standard celeration','behavior intervention plan','bip','functional behavior assessment','fba','individualized education program','iep',
  // Daily Living Expanded (~200)
  'morning','afternoon','evening','night','breakfast','lunch','dinner','snack','shower','bath','brush teeth','comb','dress','undress','cook','clean','wash','dry','fold','sweep','vacuum','mop','dust','grocery','shopping','money','pay','change','receipt','wallet','purse','bag','elevator','stairs','crossing','traffic','sidewalk','building','apartment','bedroom','kitchen','living room','bathroom','garage','garden','yard','neighbor','office','meeting','phone','email','calendar','appointment','birthday','holiday','weekend','weekday','monday','tuesday','wednesday','thursday','friday','saturday','sunday','january','february','march','april','may','june','july','august','september','october','november','december','clock','time','minute','hour','today','tomorrow','yesterday','morning routine','bedtime','alarm','wake up','get up','sit down','stand up','lie down','walk','run','jump','climb','swim','ride','drive','park','bus','train','subway','taxi','airplane','bicycle','scooter','helmet','seatbelt','key','lock','door','window','light','fan','air conditioner','heater','television','remote','computer','tablet','charger','battery','outlet','switch','refrigerator','microwave','oven','stove','sink','dishwasher','washer','dryer','trash','recycling','compost','pet','cat','dog','fish','bird','zoo','museum','library','park','playground','pool','gym','store','mall','restaurant','cafe','bakery','pharmacy','bank','post office','fire station','police','church','temple','mosque','weather','rain','snow','sun','cloud','wind','storm','thunder','lightning','umbrella','coat','jacket','sweater','shirt','pants','shorts','skirt','dress','socks','shoes','boots','hat','gloves','scarf','toothbrush','toothpaste','soap','shampoo','towel','blanket','pillow','bed','chair','table','desk','couch','shelf','drawer','closet','mirror','picture','plant','flower','tree',
  // Grammar Connectors (~150)
  'i am','you are','he is','she is','we are','they are','it is','was','were','will','would','could','should','might','must','shall','have been','has been','had been','going to','used to','able to','want to','need to','try to','like to','have to','get to','about','above','across','after','against','along','among','around','before','behind','below','beneath','beside','between','beyond','during','except','from','inside','into','near','onto','outside','over','past','since','through','toward','under','until','upon','within','without','also','already','always','never','sometimes','often','usually','rarely','still','yet','just','only','even','very','too','enough','almost','really','quite','rather','so','then','now','here','there','where','when','how','what','which','who','whom','whose','why','because','although','unless','while','whereas','whether','if','that','this','these','those','each','every','either','neither','both','all','any','some','none','many','much','few','several','other','another','such','own','same','different','first','last','next','new','old','and','but','or','nor','for','so that','in order to','as well as','not only','but also','instead of','in addition','however','therefore','meanwhile','furthermore','nevertheless','moreover','consequently','regardless','otherwise',
];

// ── Romanian ─────────────────────────────────────────────────────────────────
const ro = [
  // Medical
  'durere de cap','febră','greață','amețeală','alergie','convulsie','respirație','durere','umflat','sângerare','infecție','rețetă','spital','clinică','asistentă','doctor','scaun cu rotile','terapie','gips','operație','injecție','temperatură','tuse','erupție','vânătaie','fractură','astm','diabet','epilepsie','autism','adhd','anxietate','depresie','medicament','dozaj','simptom','diagnostic','tratament','urgență','ambulanță','oxigen','puls','tensiune arterială','inimă','plămâni','stomac','gât','ureche','ochi','piele','os','mușchi','articulație','coloană','creier','rinichi','ficat','vomă','diaree','constipație','oboseală','insomnie','migrenă','pneumonie','bronșită','anemie','accident vascular','tumoare','biopsie','radiografie','ecografie','scanare','laborator','analiză','rezultate','farmacie','tabletă','capsulă','sirop','inhalator','nebulizator','cateter','bandaj','cusătură','atelă','cârjă','premergător','aparat auditiv','ochelari','proteză','ventilator','monitor','perfuzie','semne vitale','fișă','trimitere','specialist','pediatru','neurolog','psihiatru','cardiolog','dentist','oftalmolog','chirurg','paramedic','triaj','recuperare','reabilitare','kinetoterapie','terapie ocupațională','logopedie','paliativ','cronic','acut','contagios','imunitate','vaccin','rapel','antibiotic','antiviral','analgezic','sedativ','anestezie','orteză','eșarfă','rampă','accesibil','dizabilitate','deficiență','mobilitate','spasticitate','tremur','paralizie','comoție','lacerație','arsură','rană','abces','inflamație','umflătură','amorțeală','furnicătură','dificultate de respirație','durere în piept','abdominal','leșin','reacție alergică','epipen','glucometru','insulină','dializă','chimioterapie','radioterapie','prognostic','remisie','terminal','hospice','consimțământ','confidențial','dosar medical',
  // Clinical / BCBA
  'comportament','întărire','prompt','stimul','răspuns','linie de bază','date','probă','antecedent','consecință','funcție','evadare','atenție','tangibil','senzorial','frecvență','durată','latență','interval','generalizare','menținere','extincție','modelare','înlănțuire','model','estompare','program','jeton','panou','evaluare','preferință','sondaj','stăpânire','criteriu','grafic','tendință','țintă','scop','obiectiv','abilitate','achiziție','fluență','discret','mediu natural','predare incidentală','pivotal','cerere','denumire','intraverbal','ecoic','ascultător','receptiv','expresiv','comportament verbal','analiză funcțională','evaluare funcțională','date abc','analiză de sarcină','înlănțuire inversă','înlănțuire directă','ierarhie de prompturi','minim la maxim','maxim la minim','întârziere temporală','fără eroare','corecție','întărire diferențială','dra','dro','dri','drl','ncr','operație motivațională','stimul discriminativ','întăritor condiționat','întăritor primar','întăritor secundar','raport variabil','raport fix','interval variabil','interval fix','acord interobservatori','integritate tratament','validitate socială','subiect unic','linie de bază multiplă','design reversibil','plan de intervenție comportamentală','evaluare comportamentală funcțională','plan educațional individualizat',
  // Daily Living
  'dimineață','după-amiază','seară','noapte','mic dejun','prânz','cină','gustare','duș','baie','spălat pe dinți','pieptănat','îmbrăcat','dezbrăcat','gătit','curățat','spălat','uscat','împăturit','măturat','aspirat','șters praful','cumpărături','magazin','bani','plată','rest','bon','portofel','geantă','lift','scări','trecere de pietoni','trafic','trotuar','clădire','apartament','dormitor','bucătărie','cameră de zi','garaj','grădină','curte','vecin','birou','întâlnire','telefon','email','calendar','programare','zi de naștere','vacanță','weekend','zi lucrătoare','luni','marți','miercuri','joi','vineri','sâmbătă','duminică','ianuarie','februarie','martie','aprilie','mai','iunie','iulie','august','septembrie','octombrie','noiembrie','decembrie','ceas','timp','minut','oră','azi','mâine','ieri','rutină de dimineață','culcare','alarmă','trezire','ridică-te','stai jos','stai în picioare','întinde-te','mers','alergat','sărit','urcat','înot','mers cu bicicleta','condus','parcare','autobuz','tren','metrou','taxi','avion','bicicletă','trotinetă','cască','centură','cheie','încuietoare','ușă','fereastră','lumină','ventilator','aer condiționat','încălzire','televizor','telecomandă','calculator','tabletă','încărcător','baterie','priză','întrerupător','frigider','cuptor cu microunde','cuptor','aragaz','chiuvetă','mașină de spălat vase','mașină de spălat','uscător','gunoi','reciclare','animal de companie','pisică','câine','pește','pasăre','zoo','muzeu','bibliotecă','parc','loc de joacă','piscină','sală de sport','magazin','restaurant','cafenea','brutărie','bancă','poștă','pompieri','poliție','vreme','ploaie','zăpadă','soare','nor','vânt','furtună','umbrelă','haină','jachetă','pulover','cămașă','pantaloni','fustă','rochie','șosete','pantofi','cizme','pălărie','mănuși','eșarfă','periuță','pastă de dinți','săpun','șampon','prosop','pătură','pernă','pat','scaun','masă','birou','canapea','raft','sertar','dulap','oglindă','tablou','plantă','floare','copac',
  // Grammar Connectors
  'eu sunt','tu ești','el este','ea este','noi suntem','ei sunt','ele sunt','a fost','au fost','va','ar','ar putea','ar trebui','s-ar putea','trebuie','o să','am fost','a fost','fusese','urmează să','obișnuiam să','capabil să','vreau să','trebuie să','încerc să','îmi place să','despre','deasupra','de-a lungul','după','împotriva','de-a lungul','printre','în jurul','înainte','în spatele','sub','dedesubt','lângă','între','dincolo','în timpul','cu excepția','din','înăuntru','în','aproape','pe','afară','peste','trecut','de când','prin','spre','sub','până','asupra','în cadrul','fără','de asemenea','deja','întotdeauna','niciodată','uneori','des','de obicei','rar','încă','doar','chiar','foarte','prea','destul','aproape','cu adevărat','destul de','mai degrabă','atunci','acum','aici','acolo','unde','când','cum','ce','care','cine','de ce','pentru că','deși','dacă','în timp ce','fie','nici','toți','unii','fiecare','alt','altul','același','diferit','primul','ultimul','următor','nou','vechi','și','dar','sau','deci','cu toate acestea','prin urmare','în plus','cu toate că','în schimb','în consecință',
];

// ── Spanish ──────────────────────────────────────────────────────────────────
const es = [
  // Medical
  'dolor de cabeza','fiebre','náusea','mareo','alergia','convulsión','respiración','dolor','hinchado','sangrado','infección','receta','hospital','clínica','enfermera','doctor','silla de ruedas','terapia','yeso','cirugía','inyección','temperatura','tos','sarpullido','moretón','fractura','asma','diabetes','epilepsia','autismo','tdah','ansiedad','depresión','medicamento','dosis','síntoma','diagnóstico','tratamiento','emergencia','ambulancia','oxígeno','pulso','presión arterial','corazón','pulmones','estómago','garganta','oído','ojo','piel','hueso','músculo','articulación','columna','cerebro','riñón','hígado','vómito','diarrea','estreñimiento','fatiga','insomnio','migraña','neumonía','bronquitis','anemia','derrame','tumor','biopsia','radiografía','ecografía','escáner','laboratorio','prueba','resultados','farmacia','tableta','cápsula','jarabe','inhalador','nebulizador','catéter','vendaje','puntos','férula','muleta','andador','audífono','lentes','prótesis','ventilador','monitor','suero','signos vitales','expediente','referencia','especialista','pediatra','neurólogo','psiquiatra','cardiólogo','dentista','optometrista','cirujano','paramédico','triaje','recuperación','rehabilitación','fisioterapia','terapia ocupacional','logopedia','paliativo','crónico','agudo','contagioso','inmunidad','vacuna','refuerzo','antibiótico','antiviral','analgésico','sedante','anestesia','soporte','accesible','discapacidad','movilidad','espasticidad','temblor','parálisis','conmoción','laceración','quemadura','herida','absceso','inflamación','hinchazón','adormecimiento','hormigueo','dificultad para respirar','dolor de pecho','abdominal','desmayo','reacción alérgica','glucómetro','insulina','diálisis','quimioterapia','radiación','pronóstico','remisión','consentimiento','confidencial','historial médico',
  // Clinical / BCBA
  'comportamiento','refuerzo','indicación','estímulo','respuesta','línea base','datos','ensayo','antecedente','consecuencia','función','escape','atención','tangible','sensorial','frecuencia','duración','latencia','intervalo','generalización','mantenimiento','extinción','moldeamiento','encadenamiento','modelado','desvanecimiento','programa','ficha','tablero','evaluación','preferencia','sondeo','dominio','criterio','gráfico','tendencia','meta','objetivo','habilidad','adquisición','fluidez','discreto','ambiente natural','enseñanza incidental','pivotal','mando','tacto','intraverbal','ecoico','oyente','receptivo','expresivo','conducta verbal','análisis funcional','evaluación funcional','datos abc','análisis de tarea','encadenamiento hacia atrás','encadenamiento hacia adelante','jerarquía de indicaciones','mínimo a máximo','máximo a mínimo','demora temporal','sin error','corrección','refuerzo diferencial','dra','dro','dri','drl','ncr','operación motivacional','estímulo discriminativo','reforzador condicionado','reforzador primario','reforzador secundario','razón variable','razón fija','intervalo variable','intervalo fijo','acuerdo entre observadores','integridad del tratamiento','validez social','sujeto único','línea base múltiple','diseño de reversión','plan de intervención conductual','evaluación conductual funcional','programa educativo individualizado',
  // Daily Living
  'mañana','tarde','noche','desayuno','almuerzo','cena','merienda','ducha','baño','cepillarse los dientes','peinarse','vestirse','desvestirse','cocinar','limpiar','lavar','secar','doblar','barrer','aspirar','trapear','sacudir','compras','tienda','dinero','pagar','cambio','recibo','cartera','bolsa','ascensor','escaleras','cruce','tráfico','acera','edificio','apartamento','dormitorio','cocina','sala','garaje','jardín','patio','vecino','oficina','reunión','teléfono','correo','calendario','cita','cumpleaños','vacaciones','fin de semana','día laboral','lunes','martes','miércoles','jueves','viernes','sábado','domingo','enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre','reloj','tiempo','minuto','hora','hoy','mañana','ayer','rutina matutina','acostarse','alarma','despertarse','levantarse','sentarse','pararse','acostarse','caminar','correr','saltar','subir','nadar','montar','conducir','estacionamiento','autobús','tren','metro','taxi','avión','bicicleta','patineta','casco','cinturón','llave','cerradura','puerta','ventana','luz','ventilador','aire acondicionado','calefacción','televisión','control remoto','computadora','tableta','cargador','batería','enchufe','interruptor','refrigerador','microondas','horno','estufa','fregadero','lavaplatos','lavadora','secadora','basura','reciclaje','mascota','gato','perro','pez','pájaro','zoológico','museo','biblioteca','parque','área de juegos','piscina','gimnasio','centro comercial','restaurante','cafetería','panadería','banco','correos','bomberos','policía','clima','lluvia','nieve','sol','nube','viento','tormenta','paraguas','abrigo','chaqueta','suéter','camisa','pantalones','falda','vestido','calcetines','zapatos','botas','sombrero','guantes','bufanda','cepillo de dientes','pasta dental','jabón','champú','toalla','cobija','almohada','cama','silla','mesa','escritorio','sofá','estante','cajón','armario','espejo','cuadro','planta','flor','árbol',
  // Grammar Connectors
  'yo soy','tú eres','él es','ella es','nosotros somos','ellos son','era','eran','será','sería','podría','debería','puede que','debe','habrá','he sido','ha sido','había sido','va a','solía','capaz de','quiero','necesito','intento','me gusta','tengo que','sobre','encima','a través','después','contra','a lo largo','entre','alrededor','antes','detrás','debajo','al lado','más allá','durante','excepto','desde','dentro','hacia','cerca','afuera','sobre','pasado','por','bajo','hasta','sin','también','ya','siempre','nunca','a veces','a menudo','generalmente','raramente','todavía','solo','incluso','muy','demasiado','bastante','casi','realmente','entonces','ahora','aquí','allí','donde','cuando','cómo','qué','cuál','quién','por qué','porque','aunque','a menos que','mientras','si','ese','esta','estos','esas','cada','todo','cualquier','algunos','ninguno','muchos','pocos','varios','otro','mismo','diferente','primero','último','siguiente','nuevo','viejo','y','pero','o','ni','para','además','sin embargo','por lo tanto','mientras tanto','no obstante','en consecuencia','en cambio',
];

// ── French ───────────────────────────────────────────────────────────────────
const fr = [
  // Medical
  'mal de tête','fièvre','nausée','vertige','allergie','crise','respiration','douleur','enflé','saignement','infection','ordonnance','hôpital','clinique','infirmière','médecin','fauteuil roulant','thérapie','plâtre','chirurgie','injection','température','toux','éruption','ecchymose','fracture','asthme','diabète','épilepsie','autisme','tdah','anxiété','dépression','médicament','dosage','symptôme','diagnostic','traitement','urgence','ambulance','oxygène','pouls','tension artérielle','cœur','poumons','estomac','gorge','oreille','œil','peau','os','muscle','articulation','colonne','cerveau','rein','foie','vomissement','diarrhée','constipation','fatigue','insomnie','migraine','pneumonie','bronchite','anémie','accident vasculaire','tumeur','biopsie','radiographie','échographie','scanner','laboratoire','analyse','résultats','pharmacie','comprimé','gélule','sirop','inhalateur','nébuliseur','cathéter','pansement','points de suture','attelle','béquille','déambulateur','appareil auditif','lunettes','prothèse','ventilateur','moniteur','perfusion','signes vitaux','dossier','référence','spécialiste','pédiatre','neurologue','psychiatre','cardiologue','dentiste','ophtalmologue','chirurgien','ambulancier','triage','rétablissement','réhabilitation','kinésithérapie','ergothérapie','orthophonie','palliatif','chronique','aigu','contagieux','immunité','vaccin','rappel','antibiotique','antiviral','analgésique','sédatif','anesthésie','orthèse','écharpe','rampe','accessible','handicap','déficience','mobilité','spasticité','tremblement','paralysie','commotion','lacération','brûlure','plaie','abcès','inflammation','enflure','engourdissement','picotement','essoufflement','douleur thoracique','abdominal','évanouissement','réaction allergique','glucomètre','insuline','dialyse','chimiothérapie','radiothérapie','pronostic','rémission','consentement','confidentiel','dossier médical',
  // Clinical / BCBA
  'comportement','renforcement','incitation','stimulus','réponse','ligne de base','données','essai','antécédent','conséquence','fonction','échappement','attention','tangible','sensoriel','fréquence','durée','latence','intervalle','généralisation','maintien','extinction','façonnement','enchaînement','modélisation','estompage','programme','jeton','tableau','évaluation','préférence','sonde','maîtrise','critère','graphique','tendance','cible','but','objectif','compétence','acquisition','fluidité','discret','milieu naturel','enseignement fortuit','pivot','demande','dénomination','intraverbal','échoïque','auditeur','réceptif','expressif','comportement verbal','analyse fonctionnelle','évaluation fonctionnelle','données abc','analyse de tâche','enchaînement rétrograde','enchaînement antérograde','hiérarchie des incitations','minimum au maximum','maximum au minimum','délai temporel','sans erreur','correction','renforcement différentiel','dra','dro','dri','drl','ncr','opération motivationnelle','stimulus discriminatif','renforçateur conditionné','renforçateur primaire','renforçateur secondaire','ratio variable','ratio fixe','intervalle variable','intervalle fixe','accord inter-observateurs','intégrité du traitement','validité sociale','sujet unique','ligne de base multiple','plan inversé','plan intervention comportementale','évaluation comportementale fonctionnelle','programme éducatif individualisé',
  // Daily Living
  'matin','après-midi','soir','nuit','petit-déjeuner','déjeuner','dîner','goûter','douche','bain','brosser les dents','peigner','habiller','déshabiller','cuisiner','nettoyer','laver','sécher','plier','balayer','aspirer','épousseter','courses','magasin','argent','payer','monnaie','reçu','portefeuille','sac','ascenseur','escalier','passage piéton','circulation','trottoir','immeuble','appartement','chambre','cuisine','salon','garage','jardin','cour','voisin','bureau','réunion','téléphone','courriel','calendrier','rendez-vous','anniversaire','vacances','week-end','jour ouvrable','lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche','janvier','février','mars','avril','mai','juin','juillet','août','septembre','octobre','novembre','décembre','horloge','temps','minute','heure','aujourd\'hui','demain','hier','routine matinale','coucher','alarme','se réveiller','se lever','s\'asseoir','se tenir debout','s\'allonger','marcher','courir','sauter','grimper','nager','rouler','conduire','stationnement','autobus','train','métro','taxi','avion','vélo','trottinette','casque','ceinture','clé','serrure','porte','fenêtre','lumière','ventilateur','climatisation','chauffage','télévision','télécommande','ordinateur','tablette','chargeur','batterie','prise','interrupteur','réfrigérateur','micro-ondes','four','cuisinière','évier','lave-vaisselle','lave-linge','sèche-linge','poubelle','recyclage','animal','chat','chien','poisson','oiseau','zoo','musée','bibliothèque','parc','aire de jeux','piscine','gymnase','centre commercial','restaurant','café','boulangerie','banque','poste','pompiers','police','météo','pluie','neige','soleil','nuage','vent','orage','parapluie','manteau','veste','pull','chemise','pantalon','jupe','robe','chaussettes','chaussures','bottes','chapeau','gants','écharpe','brosse à dents','dentifrice','savon','shampooing','serviette','couverture','oreiller','lit','chaise','table','bureau','canapé','étagère','tiroir','placard','miroir','tableau','plante','fleur','arbre',
  // Grammar Connectors
  'je suis','tu es','il est','elle est','nous sommes','ils sont','elles sont','était','étaient','sera','serait','pourrait','devrait','pourra','doit','aura','ai été','a été','avait été','va','avait l\'habitude','capable de','veux','ai besoin','essaie de','aime','dois','à propos','au-dessus','à travers','après','contre','le long','parmi','autour','avant','derrière','en dessous','à côté','entre','au-delà','pendant','sauf','de','dedans','dans','près','dehors','sur','passé','depuis','à travers','vers','sous','jusqu\'à','sans','aussi','déjà','toujours','jamais','parfois','souvent','habituellement','rarement','encore','seulement','même','très','trop','assez','presque','vraiment','plutôt','alors','maintenant','ici','là','où','quand','comment','quoi','quel','qui','pourquoi','parce que','bien que','à moins que','tandis que','si','ce','cette','ces','chaque','tout','quelque','aucun','beaucoup','peu','plusieurs','autre','même','différent','premier','dernier','prochain','nouveau','ancien','et','mais','ou','ni','pour','de plus','cependant','donc','pendant ce temps','néanmoins','en conséquence','au lieu de',
];

// ── Portuguese ───────────────────────────────────────────────────────────────
const pt = [
  // Medical
  'dor de cabeça','febre','náusea','tontura','alergia','convulsão','respiração','dor','inchado','sangramento','infecção','receita','hospital','clínica','enfermeira','médico','cadeira de rodas','terapia','gesso','cirurgia','injeção','temperatura','tosse','erupção','hematoma','fratura','asma','diabetes','epilepsia','autismo','tdah','ansiedade','depressão','medicamento','dosagem','sintoma','diagnóstico','tratamento','emergência','ambulância','oxigênio','pulso','pressão arterial','coração','pulmões','estômago','garganta','ouvido','olho','pele','osso','músculo','articulação','coluna','cérebro','rim','fígado','vômito','diarreia','constipação','fadiga','insônia','enxaqueca','pneumonia','bronquite','anemia','derrame','tumor','biópsia','radiografia','ultrassom','tomografia','laboratório','exame','resultados','farmácia','comprimido','cápsula','xarope','inalador','nebulizador','cateter','curativo','pontos','tala','muleta','andador','aparelho auditivo','óculos','prótese','ventilador','monitor','soro','sinais vitais','prontuário','encaminhamento','especialista','pediatra','neurologista','psiquiatra','cardiologista','dentista','oftalmologista','cirurgião','paramédico','triagem','recuperação','reabilitação','fisioterapia','terapia ocupacional','fonoaudiologia','paliativo','crônico','agudo','contagioso','imunidade','vacina','reforço','antibiótico','antiviral','analgésico','sedativo','anestesia','órtese','tipoia','rampa','acessível','deficiência','mobilidade','espasticidade','tremor','paralisia','concussão','laceração','queimadura','ferida','abscesso','inflamação','inchaço','dormência','formigamento','falta de ar','dor no peito','abdominal','desmaio','reação alérgica','glicosímetro','insulina','diálise','quimioterapia','radioterapia','prognóstico','remissão','consentimento','confidencial','prontuário médico',
  // Clinical / BCBA
  'comportamento','reforço','dica','estímulo','resposta','linha de base','dados','tentativa','antecedente','consequência','função','fuga','atenção','tangível','sensorial','frequência','duração','latência','intervalo','generalização','manutenção','extinção','modelagem','encadeamento','modelação','esvanecimento','esquema','ficha','quadro','avaliação','preferência','sondagem','domínio','critério','gráfico','tendência','alvo','meta','objetivo','habilidade','aquisição','fluência','discreto','ambiente natural','ensino incidental','pivotal','mando','tato','intraverbal','ecoico','ouvinte','receptivo','expressivo','comportamento verbal','análise funcional','avaliação funcional','dados abc','análise de tarefa','encadeamento reverso','encadeamento direto','hierarquia de dicas','mínimo ao máximo','máximo ao mínimo','atraso temporal','sem erro','correção','reforço diferencial','dra','dro','dri','drl','ncr','operação motivacional','estímulo discriminativo','reforçador condicionado','reforçador primário','reforçador secundário','razão variável','razão fixa','intervalo variável','intervalo fixo','concordância entre observadores','integridade do tratamento','validade social','sujeito único','linha de base múltipla','delineamento de reversão','plano de intervenção comportamental','avaliação comportamental funcional','plano educacional individualizado',
  // Daily Living
  'manhã','tarde','noite','café da manhã','almoço','jantar','lanche','chuveiro','banho','escovar os dentes','pentear','vestir','despir','cozinhar','limpar','lavar','secar','dobrar','varrer','aspirar','passar pano','tirar poeira','compras','loja','dinheiro','pagar','troco','recibo','carteira','bolsa','elevador','escadas','faixa de pedestres','trânsito','calçada','prédio','apartamento','quarto','cozinha','sala','garagem','jardim','quintal','vizinho','escritório','reunião','telefone','email','calendário','consulta','aniversário','feriado','fim de semana','dia útil','segunda','terça','quarta','quinta','sexta','sábado','domingo','janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro','relógio','tempo','minuto','hora','hoje','amanhã','ontem','rotina matinal','dormir','alarme','acordar','levantar','sentar','ficar de pé','deitar','andar','correr','pular','subir','nadar','pedalar','dirigir','estacionamento','ônibus','trem','metrô','táxi','avião','bicicleta','patinete','capacete','cinto','chave','fechadura','porta','janela','luz','ventilador','ar condicionado','aquecedor','televisão','controle remoto','computador','tablet','carregador','bateria','tomada','interruptor','geladeira','micro-ondas','forno','fogão','pia','lava-louças','máquina de lavar','secadora','lixo','reciclagem','animal de estimação','gato','cachorro','peixe','pássaro','zoológico','museu','biblioteca','parque','parquinho','piscina','academia','shopping','restaurante','café','padaria','banco','correio','bombeiros','polícia','clima','chuva','neve','sol','nuvem','vento','tempestade','guarda-chuva','casaco','jaqueta','suéter','camisa','calça','saia','vestido','meias','sapatos','botas','chapéu','luvas','cachecol','escova de dentes','pasta de dentes','sabonete','shampoo','toalha','cobertor','travesseiro','cama','cadeira','mesa','escrivaninha','sofá','prateleira','gaveta','armário','espelho','quadro','planta','flor','árvore',
  // Grammar Connectors
  'eu sou','você é','ele é','ela é','nós somos','eles são','elas são','era','eram','vai','iria','poderia','deveria','pode','deve','terá','tenho sido','tem sido','tinha sido','vai','costumava','capaz de','quero','preciso','tento','gosto de','tenho que','sobre','acima','através','depois','contra','ao longo','entre','ao redor','antes','atrás','abaixo','ao lado','além','durante','exceto','de','dentro','para','perto','fora','sobre','passado','desde','por','em direção','sob','até','sem','também','já','sempre','nunca','às vezes','frequentemente','geralmente','raramente','ainda','só','mesmo','muito','demais','bastante','quase','realmente','então','agora','aqui','ali','onde','quando','como','o que','qual','quem','por que','porque','embora','a menos que','enquanto','se','esse','esta','estes','essas','cada','todo','qualquer','alguns','nenhum','muitos','poucos','vários','outro','mesmo','diferente','primeiro','último','próximo','novo','velho','e','mas','ou','nem','para','além disso','no entanto','portanto','enquanto isso','todavia','em consequência','em vez de',
];

// ── German ───────────────────────────────────────────────────────────────────
const de = [
  // Medical
  'Kopfschmerzen','Fieber','Übelkeit','Schwindel','Allergie','Anfall','Atmung','Schmerz','geschwollen','Blutung','Infektion','Rezept','Krankenhaus','Klinik','Krankenschwester','Arzt','Rollstuhl','Therapie','Gips','Operation','Spritze','Temperatur','Husten','Ausschlag','Prellung','Bruch','Asthma','Diabetes','Epilepsie','Autismus','ADHS','Angst','Depression','Medikament','Dosierung','Symptom','Diagnose','Behandlung','Notfall','Krankenwagen','Sauerstoff','Puls','Blutdruck','Herz','Lunge','Magen','Hals','Ohr','Auge','Haut','Knochen','Muskel','Gelenk','Wirbelsäule','Gehirn','Niere','Leber','Erbrechen','Durchfall','Verstopfung','Müdigkeit','Schlaflosigkeit','Migräne','Lungenentzündung','Bronchitis','Anämie','Schlaganfall','Tumor','Biopsie','Röntgen','Ultraschall','Scan','Labor','Test','Ergebnisse','Apotheke','Tablette','Kapsel','Sirup','Inhalator','Vernebler','Katheter','Verband','Naht','Schiene','Krücke','Gehwagen','Hörgerät','Brille','Prothese','Beatmungsgerät','Monitor','Infusion','Vitalzeichen','Akte','Überweisung','Facharzt','Kinderarzt','Neurologe','Psychiater','Kardiologe','Zahnarzt','Augenarzt','Chirurg','Sanitäter','Triage','Genesung','Rehabilitation','Physiotherapie','Ergotherapie','Logopädie','palliativ','chronisch','akut','ansteckend','Immunität','Impfung','Auffrischung','Antibiotikum','Antiviral','Schmerzmittel','Beruhigungsmittel','Narkose','Orthese','Schlinge','Rampe','barrierefrei','Behinderung','Beeinträchtigung','Mobilität','Spastik','Zittern','Lähmung','Gehirnerschütterung','Risswunde','Verbrennung','Wunde','Abszess','Entzündung','Schwellung','Taubheit','Kribbeln','Atemnot','Brustschmerzen','Bauch','Ohnmacht','allergische Reaktion','Blutzuckermessgerät','Insulin','Dialyse','Chemotherapie','Strahlentherapie','Prognose','Remission','Einwilligung','vertraulich','Patientenakte',
  // Clinical / BCBA
  'Verhalten','Verstärkung','Hilfestellung','Reiz','Reaktion','Ausgangslage','Daten','Versuch','Vorläufer','Konsequenz','Funktion','Flucht','Aufmerksamkeit','materiell','sensorisch','Häufigkeit','Dauer','Latenz','Intervall','Generalisierung','Erhaltung','Löschung','Formung','Verkettung','Modellierung','Ausblendung','Zeitplan','Token','Tafel','Bewertung','Präferenz','Sonde','Beherrschung','Kriterium','Grafik','Trend','Ziel','Zielstellung','Kompetenz','Erwerb','Geläufigkeit','diskret','natürliche Umgebung','beiläufiges Lernen','Schlüssel','Anforderung','Benennung','intraverbal','echoisch','Zuhörer','rezeptiv','expressiv','verbales Verhalten','Funktionsanalyse','funktionale Bewertung','ABC-Daten','Aufgabenanalyse','Rückwärtsverkettung','Vorwärtsverkettung','Hilfestellungshierarchie','Minimum zu Maximum','Maximum zu Minimum','Zeitverzögerung','fehlerfrei','Korrektur','differentielle Verstärkung','DRA','DRO','DRI','DRL','NCR','Motivationsoperation','diskriminativer Reiz','konditionierter Verstärker','primärer Verstärker','sekundärer Verstärker','variable Quote','feste Quote','variables Intervall','festes Intervall','Beobachterübereinstimmung','Behandlungsintegrität','soziale Validität','Einzelfall','multiple Ausgangslage','Umkehrdesign','Verhaltensinterventionsplan','funktionale Verhaltensbewertung','individueller Bildungsplan',
  // Daily Living
  'Morgen','Nachmittag','Abend','Nacht','Frühstück','Mittagessen','Abendessen','Snack','Dusche','Bad','Zähneputzen','Kämmen','Anziehen','Ausziehen','Kochen','Putzen','Waschen','Trocknen','Falten','Fegen','Staubsaugen','Wischen','Abstauben','Einkaufen','Geschäft','Geld','Bezahlen','Wechselgeld','Quittung','Geldbörse','Tasche','Aufzug','Treppe','Zebrastreifen','Verkehr','Gehweg','Gebäude','Wohnung','Schlafzimmer','Küche','Wohnzimmer','Badezimmer','Garage','Garten','Hof','Nachbar','Büro','Besprechung','Telefon','E-Mail','Kalender','Termin','Geburtstag','Feiertag','Wochenende','Werktag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag','Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember','Uhr','Zeit','Minute','Stunde','heute','morgen','gestern','Morgenroutine','Schlafenszeit','Wecker','Aufwachen','Aufstehen','Hinsetzen','Stehen','Hinlegen','Gehen','Laufen','Springen','Klettern','Schwimmen','Radfahren','Autofahren','Parkplatz','Bus','Zug','U-Bahn','Taxi','Flugzeug','Fahrrad','Roller','Helm','Sicherheitsgurt','Schlüssel','Schloss','Tür','Fenster','Licht','Ventilator','Klimaanlage','Heizung','Fernseher','Fernbedienung','Computer','Tablet','Ladegerät','Batterie','Steckdose','Schalter','Kühlschrank','Mikrowelle','Ofen','Herd','Spüle','Geschirrspüler','Waschmaschine','Trockner','Müll','Recycling','Haustier','Katze','Hund','Fisch','Vogel','Zoo','Museum','Bibliothek','Park','Spielplatz','Schwimmbad','Fitnessstudio','Einkaufszentrum','Restaurant','Café','Bäckerei','Bank','Post','Feuerwehr','Polizei','Wetter','Regen','Schnee','Sonne','Wolke','Wind','Sturm','Regenschirm','Mantel','Jacke','Pullover','Hemd','Hose','Rock','Kleid','Socken','Schuhe','Stiefel','Hut','Handschuhe','Schal','Zahnbürste','Zahnpasta','Seife','Shampoo','Handtuch','Decke','Kissen','Bett','Stuhl','Tisch','Schreibtisch','Sofa','Regal','Schublade','Schrank','Spiegel','Bild','Pflanze','Blume','Baum',
  // Grammar Connectors
  'ich bin','du bist','er ist','sie ist','wir sind','sie sind','es ist','war','waren','wird','würde','könnte','sollte','dürfte','muss','soll','bin gewesen','ist gewesen','war gewesen','werde','pflegte zu','fähig zu','will','brauche','versuche','mag','muss','über','oberhalb','quer','nach','gegen','entlang','unter','um','vor','hinter','unterhalb','neben','zwischen','jenseits','während','außer','von','innen','in','nahe','draußen','über','vorbei','seit','durch','zu','bis','auf','innerhalb','ohne','auch','schon','immer','nie','manchmal','oft','gewöhnlich','selten','noch','nur','sogar','sehr','zu','genug','fast','wirklich','ziemlich','eher','dann','jetzt','hier','dort','wo','wann','wie','was','welcher','wer','warum','weil','obwohl','es sei denn','während','ob','wenn','das','diese','jeder','alle','einige','kein','viele','wenige','mehrere','andere','gleich','verschieden','erste','letzte','nächste','neu','alt','und','aber','oder','weder','noch','für','außerdem','jedoch','deshalb','inzwischen','dennoch','folglich','stattdessen',
];

// ── Russian ──────────────────────────────────────────────────────────────────
const ru = [
  // Medical
  'головная боль','жар','тошнота','головокружение','аллергия','припадок','дыхание','боль','опухший','кровотечение','инфекция','рецепт','больница','клиника','медсестра','врач','инвалидная коляска','терапия','гипс','операция','инъекция','температура','кашель','сыпь','синяк','перелом','астма','диабет','эпилепсия','аутизм','сдвг','тревога','депрессия','лекарство','дозировка','симптом','диагноз','лечение','скорая помощь','неотложная помощь','кислород','пульс','давление','сердце','лёгкие','желудок','горло','ухо','глаз','кожа','кость','мышца','сустав','позвоночник','мозг','почка','печень','рвота','диарея','запор','усталость','бессонница','мигрень','пневмония','бронхит','анемия','инсульт','опухоль','биопсия','рентген','узи','томография','лаборатория','анализ','результаты','аптека','таблетка','капсула','сироп','ингалятор','небулайзер','катетер','повязка','швы','шина','костыль','ходунки','слуховой аппарат','очки','протез','аппарат ивл','монитор','капельница','жизненные показатели','карта','направление','специалист','педиатр','невролог','психиатр','кардиолог','стоматолог','окулист','хирург','фельдшер','сортировка','выздоровление','реабилитация','физиотерапия','трудотерапия','логопедия','паллиативный','хронический','острый','заразный','иммунитет','вакцина','ревакцинация','антибиотик','противовирусный','обезболивающее','седативное','наркоз','ортез','повязка на руку','пандус','доступный','инвалидность','нарушение','мобильность','спастичность','тремор','паралич','сотрясение','рваная рана','ожог','рана','абсцесс','воспаление','отёк','онемение','покалывание','одышка','боль в груди','живот','обморок','аллергическая реакция','глюкометр','инсулин','диализ','химиотерапия','лучевая терапия','прогноз','ремиссия','согласие','конфиденциально','медицинская карта',
  // Clinical / BCBA
  'поведение','подкрепление','подсказка','стимул','реакция','базовый уровень','данные','проба','антецедент','последствие','функция','избегание','внимание','материальный','сенсорный','частота','продолжительность','латентность','интервал','генерализация','поддержание','угасание','формирование','цепочка','моделирование','затухание','расписание','жетон','доска','оценка','предпочтение','зонд','овладение','критерий','график','тенденция','цель','задача','навык','усвоение','беглость','дискретный','естественная среда','случайное обучение','ключевой','просьба','название','интравербальный','эхоический','слушатель','рецептивный','экспрессивный','вербальное поведение','функциональный анализ','функциональная оценка','данные абв','анализ задач','обратная цепочка','прямая цепочка','иерархия подсказок','от минимума к максимуму','от максимума к минимуму','временная задержка','безошибочный','коррекция','дифференциальное подкрепление','дра','дро','дри','дрл','нкр','мотивационная операция','различительный стимул','условный подкрепитель','первичный подкрепитель','вторичный подкрепитель','переменное соотношение','фиксированное соотношение','переменный интервал','фиксированный интервал','межнаблюдательское согласие','целостность лечения','социальная валидность','единичный субъект','множественный базовый уровень','реверсивный дизайн','план поведенческого вмешательства','функциональная оценка поведения','индивидуальный образовательный план',
  // Daily Living
  'утро','день','вечер','ночь','завтрак','обед','ужин','перекус','душ','ванна','чистить зубы','расчёска','одеться','раздеться','готовить','убирать','мыть','сушить','складывать','подметать','пылесосить','протирать','покупки','магазин','деньги','платить','сдача','чек','кошелёк','сумка','лифт','лестница','переход','трафик','тротуар','здание','квартира','спальня','кухня','гостиная','ванная','гараж','сад','двор','сосед','офис','встреча','телефон','почта','календарь','запись','день рождения','праздник','выходные','будний день','понедельник','вторник','среда','четверг','пятница','суббота','воскресенье','январь','февраль','март','апрель','май','июнь','июль','август','сентябрь','октябрь','ноябрь','декабрь','часы','время','минута','час','сегодня','завтра','вчера','утренний распорядок','отход ко сну','будильник','проснуться','встать','сесть','стоять','лечь','ходить','бегать','прыгать','лазить','плавать','кататься','водить','парковка','автобус','поезд','метро','такси','самолёт','велосипед','самокат','шлем','ремень','ключ','замок','дверь','окно','свет','вентилятор','кондиционер','обогреватель','телевизор','пульт','компьютер','планшет','зарядка','батарея','розетка','выключатель','холодильник','микроволновка','духовка','плита','раковина','посудомоечная машина','стиральная машина','сушилка','мусор','переработка','питомец','кошка','собака','рыба','птица','зоопарк','музей','библиотека','парк','площадка','бассейн','спортзал','торговый центр','ресторан','кафе','пекарня','банк','почта','пожарная','полиция','погода','дождь','снег','солнце','облако','ветер','гроза','зонт','пальто','куртка','свитер','рубашка','брюки','юбка','платье','носки','обувь','сапоги','шапка','перчатки','шарф','зубная щётка','зубная паста','мыло','шампунь','полотенце','одеяло','подушка','кровать','стул','стол','письменный стол','диван','полка','ящик','шкаф','зеркало','картина','растение','цветок','дерево',
  // Grammar Connectors
  'я есть','ты есть','он есть','она есть','мы есть','они есть','был','была','были','будет','бы','мог бы','должен','может','надо','буду','был','была','будет','собираюсь','привык','способен','хочу','нужно','пытаюсь','нравится','должен','о','над','через','после','против','вдоль','среди','вокруг','до','за','ниже','рядом','между','за пределами','во время','кроме','из','внутри','в','близко','снаружи','поверх','мимо','с','сквозь','к','под','до','на','в пределах','без','также','уже','всегда','никогда','иногда','часто','обычно','редко','ещё','только','даже','очень','слишком','достаточно','почти','действительно','довольно','скорее','тогда','сейчас','здесь','там','где','когда','как','что','какой','кто','почему','потому что','хотя','если не','пока','если','этот','эта','эти','те','каждый','все','любой','некоторые','ни один','много','мало','несколько','другой','тот же','различный','первый','последний','следующий','новый','старый','и','но','или','ни','для','кроме того','однако','поэтому','тем временем','тем не менее','следовательно','вместо',
];

// ── Ukrainian ────────────────────────────────────────────────────────────────
const uk = [
  // Medical
  'головний біль','гарячка','нудота','запаморочення','алергія','напад','дихання','біль','набряклий','кровотеча','інфекція','рецепт','лікарня','клініка','медсестра','лікар','інвалідний візок','терапія','гіпс','операція','ін\'єкція','температура','кашель','висип','синець','перелом','астма','діабет','епілепсія','аутизм','зрдуг','тривога','депресія','ліки','дозування','симптом','діагноз','лікування','швидка допомога','невідкладна допомога','кисень','пульс','тиск','серце','легені','шлунок','горло','вухо','око','шкіра','кістка','м\'яз','суглоб','хребет','мозок','нирка','печінка','блювота','діарея','запор','втома','безсоння','мігрень','пневмонія','бронхіт','анемія','інсульт','пухлина','біопсія','рентген','узд','томографія','лабораторія','аналіз','результати','аптека','таблетка','капсула','сироп','інгалятор','небулайзер','катетер','пов\'язка','шви','шина','милиця','ходунки','слуховий апарат','окуляри','протез','апарат швл','монітор','крапельниця','показники','картка','направлення','спеціаліст','педіатр','невролог','психіатр','кардіолог','стоматолог','окуліст','хірург','фельдшер','сортування','одужання','реабілітація','фізіотерапія','трудотерапія','логопедія','паліативний','хронічний','гострий','заразний','імунітет','вакцина','ревакцинація','антибіотик','противірусний','знеболювальне','седативне','наркоз','ортез','пов\'язка на руку','пандус','доступний','інвалідність','порушення','мобільність','спастичність','тремор','параліч','струс','рвана рана','опік','рана','абсцес','запалення','набряк','оніміння','поколювання','задишка','біль у грудях','живіт','непритомність','алергічна реакція','глюкометр','інсулін','діаліз','хіміотерапія','променева терапія','прогноз','ремісія','згода','конфіденційно','медична картка',
  // Clinical / BCBA
  'поведінка','підкріплення','підказка','стимул','реакція','базовий рівень','дані','проба','антецедент','наслідок','функція','уникнення','увага','матеріальний','сенсорний','частота','тривалість','латентність','інтервал','генералізація','підтримання','згасання','формування','ланцюжок','моделювання','затухання','розклад','жетон','дошка','оцінка','уподобання','зонд','опанування','критерій','графік','тенденція','ціль','завдання','навичка','засвоєння','швидкість','дискретний','природне середовище','випадкове навчання','ключовий','прохання','назва','інтравербальний','ехоїчний','слухач','рецептивний','експресивний','вербальна поведінка','функціональний аналіз','функціональна оцінка','дані абв','аналіз завдань','зворотний ланцюжок','прямий ланцюжок','ієрархія підказок','від мінімуму до максимуму','від максимуму до мінімуму','часова затримка','безпомилковий','корекція','диференційне підкріплення','дра','дро','дрі','дрл','нкр','мотиваційна операція','розрізнювальний стимул','умовний підкріплювач','первинний підкріплювач','вторинний підкріплювач','змінне співвідношення','фіксоване співвідношення','змінний інтервал','фіксований інтервал','міжспостережницька згода','цілісність лікування','соціальна валідність','одиничний суб\'єкт','множинний базовий рівень','реверсивний дизайн','план поведінкового втручання','функціональна оцінка поведінки','індивідуальний освітній план',
  // Daily Living
  'ранок','день','вечір','ніч','сніданок','обід','вечеря','перекус','душ','ванна','чистити зуби','гребінець','одягнутися','роздягнутися','готувати','прибирати','мити','сушити','складати','підмітати','пилососити','витирати','покупки','магазин','гроші','платити','решта','чек','гаманець','сумка','ліфт','сходи','перехід','рух','тротуар','будівля','квартира','спальня','кухня','вітальня','ванна кімната','гараж','сад','двір','сусід','офіс','зустріч','телефон','пошта','календар','запис','день народження','свято','вихідні','будній день','понеділок','вівторок','середа','четвер','п\'ятниця','субота','неділя','січень','лютий','березень','квітень','травень','червень','липень','серпень','вересень','жовтень','листопад','грудень','годинник','час','хвилина','година','сьогодні','завтра','вчора','ранкова рутина','відхід до сну','будильник','прокинутися','встати','сісти','стояти','лягти','ходити','бігати','стрибати','лазити','плавати','кататися','водити','парковка','автобус','потяг','метро','таксі','літак','велосипед','самокат','шолом','ремінь','ключ','замок','двері','вікно','світло','вентилятор','кондиціонер','обігрівач','телевізор','пульт','комп\'ютер','планшет','зарядка','батарея','розетка','вимикач','холодильник','мікрохвильовка','духовка','плита','раковина','посудомийна машина','пральна машина','сушарка','сміття','переробка','домашній улюбленець','кіт','собака','риба','птах','зоопарк','музей','бібліотека','парк','майданчик','басейн','спортзал','торговий центр','ресторан','кафе','пекарня','банк','пошта','пожежна','поліція','погода','дощ','сніг','сонце','хмара','вітер','гроза','парасолька','пальто','куртка','светр','сорочка','штани','спідниця','сукня','шкарпетки','взуття','чоботи','шапка','рукавички','шарф','зубна щітка','зубна паста','мило','шампунь','рушник','ковдра','подушка','ліжко','стілець','стіл','письмовий стіл','диван','полиця','шухляда','шафа','дзеркало','картина','рослина','квітка','дерево',
  // Grammar Connectors
  'я є','ти є','він є','вона є','ми є','вони є','був','була','були','буде','б','міг би','повинен','може','треба','буду','був','була','буде','збираюсь','звик','здатний','хочу','потрібно','намагаюсь','подобається','мушу','про','над','через','після','проти','вздовж','серед','навколо','до','за','нижче','поруч','між','за межами','під час','крім','з','всередині','у','близько','зовні','поверх','повз','з','крізь','до','під','до','на','в межах','без','також','вже','завжди','ніколи','іноді','часто','зазвичай','рідко','ще','тільки','навіть','дуже','занадто','достатньо','майже','справді','досить','швидше','тоді','зараз','тут','там','де','коли','як','що','який','хто','чому','тому що','хоча','якщо не','поки','якщо','цей','ця','ці','ті','кожен','всі','будь-який','деякі','жоден','багато','мало','кілька','інший','той самий','різний','перший','останній','наступний','новий','старий','і','але','або','ні','для','крім того','однак','тому','тим часом','проте','отже','замість',
];

// ── Japanese ─────────────────────────────────────────────────────────────────
const ja = [
  // Medical
  '頭痛','熱','吐き気','めまい','アレルギー','発作','呼吸','痛み','腫れ','出血','感染','処方箋','病院','クリニック','看護師','医師','車椅子','治療','ギプス','手術','注射','体温','咳','発疹','あざ','骨折','喘息','糖尿病','てんかん','自閉症','注意欠陥','不安','うつ病','薬','用量','症状','診断','治療法','緊急','救急車','酸素','脈拍','血圧','心臓','肺','胃','喉','耳','目','皮膚','骨','筋肉','関節','脊椎','脳','腎臓','肝臓','嘔吐','下痢','便秘','疲労','不眠症','片頭痛','肺炎','気管支炎','貧血','脳卒中','腫瘍','生検','レントゲン','超音波','検査','研究室','検査','結果','薬局','錠剤','カプセル','シロップ','吸入器','ネブライザー','カテーテル','包帯','縫合','添え木','松葉杖','歩行器','補聴器','眼鏡','義肢','人工呼吸器','モニター','点滴','バイタルサイン','カルテ','紹介状','専門医','小児科医','神経科医','精神科医','心臓専門医','歯科医','眼科医','外科医','救急隊員','トリアージ','回復','リハビリテーション','理学療法','作業療法','言語療法','緩和','慢性','急性','感染性','免疫','ワクチン','追加接種','抗生物質','抗ウイルス薬','鎮痛剤','鎮静剤','麻酔','装具','スリング','スロープ','バリアフリー','障害','機能障害','移動性','痙縮','振戦','麻痺','脳震盪','裂傷','やけど','傷','膿瘍','炎症','むくみ','しびれ','ちくちく','息切れ','胸の痛み','腹部','失神','アレルギー反応','血糖値計','インスリン','透析','化学療法','放射線療法','予後','寛解','同意','機密','診療記録',
  // Clinical / BCBA
  '行動','強化','プロンプト','刺激','反応','基準線','データ','試行','先行事象','結果事象','機能','逃避','注目','有形物','感覚','頻度','持続時間','潜時','間隔','般化','維持','消去','シェイピング','連鎖化','モデリング','フェイディング','スケジュール','トークン','ボード','評価','選好','プローブ','習得','基準','グラフ','傾向','標的','目標','課題','スキル','獲得','流暢性','離散','自然環境','偶発的指導','中核','要求言語','報告言語','イントラバーバル','エコーイック','聞き手','受容','表出','言語行動','機能分析','機能評価','ABCデータ','課題分析','逆行連鎖','順行連鎖','プロンプト階層','最小から最大','最大から最小','時間遅延','無誤学習','修正','分化強化','DRA','DRO','DRI','DRL','NCR','確立操作','弁別刺激','条件性強化子','一次性強化子','二次性強化子','変動比率','固定比率','変動間隔','固定間隔','観察者間一致率','治療忠実度','社会的妥当性','単一事例','多層ベースライン','反転デザイン','行動介入計画','機能的行動評価','個別教育計画',
  // Daily Living
  '朝','午後','夕方','夜','朝食','昼食','夕食','おやつ','シャワー','お風呂','歯磨き','くし','着替え','脱ぐ','料理','掃除','洗う','乾かす','畳む','掃く','掃除機','拭く','買い物','店','お金','払う','おつり','レシート','財布','かばん','エレベーター','階段','横断歩道','交通','歩道','建物','アパート','寝室','台所','居間','浴室','車庫','庭','隣人','事務所','会議','電話','メール','カレンダー','予約','誕生日','祝日','週末','平日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日','一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月','時計','時間','分','時','今日','明日','昨日','朝の習慣','就寝','目覚まし','起きる','立つ','座る','立ち上がる','横になる','歩く','走る','跳ぶ','登る','泳ぐ','乗る','運転','駐車場','バス','電車','地下鉄','タクシー','飛行機','自転車','スクーター','ヘルメット','シートベルト','鍵','錠前','ドア','窓','照明','扇風機','エアコン','暖房','テレビ','リモコン','パソコン','タブレット','充電器','電池','コンセント','スイッチ','冷蔵庫','電子レンジ','オーブン','コンロ','流し台','食洗機','洗濯機','乾燥機','ごみ','リサイクル','ペット','猫','犬','魚','鳥','動物園','博物館','図書館','公園','遊び場','プール','ジム','ショッピングセンター','レストラン','カフェ','パン屋','銀行','郵便局','消防署','警察','天気','雨','雪','太陽','雲','風','嵐','傘','コート','ジャケット','セーター','シャツ','ズボン','スカート','ドレス','靴下','靴','ブーツ','帽子','手袋','マフラー','歯ブラシ','歯磨き粉','石鹸','シャンプー','タオル','毛布','枕','ベッド','椅子','テーブル','机','ソファ','棚','引き出し','クローゼット','鏡','絵','植物','花','木',
  // Grammar Connectors
  '私は','あなたは','彼は','彼女は','私たちは','彼らは','でした','だった','でしょう','だろう','できる','すべき','かもしれない','しなければ','するつもり','になる','したことがある','していた','するところ','以前は','できる','したい','する必要がある','しようとする','が好き','しなければならない','について','の上に','を横切って','の後に','に対して','に沿って','の間に','の周りに','の前に','の後ろに','の下に','のそばに','の間に','を超えて','の間','を除いて','から','の中に','の中へ','の近くに','の外に','を越えて','を過ぎて','以来','を通して','に向かって','の下に','まで','の上に','の範囲内','なしで','また','すでに','いつも','決して','時々','よく','たいてい','めったに','まだ','だけ','さえ','とても','あまりに','十分に','ほとんど','本当に','かなり','むしろ','それから','今','ここ','そこ','どこ','いつ','どう','何','どの','誰','なぜ','なぜなら','けれども','でなければ','の間','もし','この','その','これらの','それらの','各','すべての','どんな','いくつかの','何も','多くの','少しの','いくつかの','他の','同じ','異なる','最初の','最後の','次の','新しい','古い','と','しかし','または','でも','のために','さらに','しかしながら','したがって','その間','それにもかかわらず','結果として','代わりに',
];

// ── Korean ───────────────────────────────────────────────────────────────────
const ko = [
  // Medical
  '두통','열','메스꺼움','어지러움','알레르기','발작','호흡','통증','부어오름','출혈','감염','처방전','병원','클리닉','간호사','의사','휠체어','치료','깁스','수술','주사','체온','기침','발진','멍','골절','천식','당뇨병','간질','자폐증','주의력결핍','불안','우울증','약','용량','증상','진단','치료법','응급','구급차','산소','맥박','혈압','심장','폐','위','목','귀','눈','피부','뼈','근육','관절','척추','뇌','신장','간','구토','설사','변비','피로','불면증','편두통','폐렴','기관지염','빈혈','뇌졸중','종양','생검','엑스레이','초음파','스캔','검사실','검사','결과','약국','알약','캡슐','시럽','흡입기','네블라이저','카테터','붕대','봉합','부목','목발','보행기','보청기','안경','의족','인공호흡기','모니터','수액','활력징후','차트','의뢰','전문의','소아과의사','신경과의사','정신과의사','심장전문의','치과의사','안과의사','외과의사','응급구조사','분류','회복','재활','물리치료','작업치료','언어치료','완화','만성','급성','전염성','면역','백신','추가접종','항생제','항바이러스제','진통제','진정제','마취','보조기','슬링','경사로','접근가능','장애','손상','이동성','경직','떨림','마비','뇌진탕','열상','화상','상처','농양','염증','부기','무감각','저림','호흡곤란','가슴통증','복부','실신','알레르기반응','혈당측정기','인슐린','투석','화학요법','방사선치료','예후','관해','동의','기밀','진료기록',
  // Clinical / BCBA
  '행동','강화','촉구','자극','반응','기초선','데이터','시행','선행사건','후속결과','기능','도피','주의','유형물','감각','빈도','지속시간','잠재기','간격','일반화','유지','소거','형성','연쇄','모델링','퇴화','일정','토큰','보드','평가','선호','탐침','숙달','기준','그래프','추세','표적','목표','과제','기술','습득','유창성','개별','자연환경','우발적교수','중추','요구어','보고어','상호언어','반향어','청자','수용','표현','언어행동','기능분석','기능평가','ABC데이터','과제분석','역행연쇄','순행연쇄','촉구위계','최소에서최대','최대에서최소','시간지연','무오류','교정','차별강화','DRA','DRO','DRI','DRL','NCR','확립조작','변별자극','조건강화제','일차강화제','이차강화제','변동비율','고정비율','변동간격','고정간격','관찰자간일치도','치료충실도','사회적타당성','단일대상','다중기초선','반전설계','행동중재계획','기능적행동평가','개별화교육프로그램',
  // Daily Living
  '아침','오후','저녁','밤','아침식사','점심','저녁식사','간식','샤워','목욕','양치','빗','옷입기','옷벗기','요리','청소','씻기','말리기','접기','쓸기','청소기','닦기','장보기','가게','돈','지불','거스름돈','영수증','지갑','가방','엘리베이터','계단','횡단보도','교통','보도','건물','아파트','침실','부엌','거실','욕실','차고','정원','마당','이웃','사무실','회의','전화','이메일','달력','예약','생일','휴일','주말','평일','월요일','화요일','수요일','목요일','금요일','토요일','일요일','일월','이월','삼월','사월','오월','유월','칠월','팔월','구월','시월','십일월','십이월','시계','시간','분','시','오늘','내일','어제','아침루틴','취침','알람','일어나기','앉기','서기','눕기','걷기','달리기','뛰기','오르기','수영','타기','운전','주차장','버스','기차','지하철','택시','비행기','자전거','킥보드','헬멧','안전벨트','열쇠','자물쇠','문','창문','조명','선풍기','에어컨','히터','텔레비전','리모컨','컴퓨터','태블릿','충전기','배터리','콘센트','스위치','냉장고','전자레인지','오븐','가스레인지','싱크대','식기세척기','세탁기','건조기','쓰레기','재활용','반려동물','고양이','강아지','물고기','새','동물원','박물관','도서관','공원','놀이터','수영장','체육관','쇼핑몰','식당','카페','빵집','은행','우체국','소방서','경찰','날씨','비','눈','해','구름','바람','폭풍','우산','코트','재킷','스웨터','셔츠','바지','치마','원피스','양말','신발','부츠','모자','장갑','목도리','칫솔','치약','비누','샴푸','수건','이불','베개','침대','의자','탁자','책상','소파','선반','서랍','옷장','거울','그림','식물','꽃','나무',
  // Grammar Connectors
  '나는','너는','그는','그녀는','우리는','그들은','이었다','였다','할것이다','할수있다','해야한다','할지도모른다','해야만한다','될것이다','한적이있다','했었다','할예정이다','하곤했다','할수있는','하고싶다','할필요가있다','하려고하다','좋아하다','해야하다','에대해','위에','건너서','후에','맞서','따라','사이에','주위에','전에','뒤에','아래에','옆에','사이에','너머에','동안','제외하고','에서','안에','으로','가까이','바깥에','위로','지나서','이후로','통해서','향해','아래로','까지','위에','안에서','없이','또한','이미','항상','절대','때때로','자주','보통','거의않다','아직','단지','조차','매우','너무','충분히','거의','정말로','꽤','오히려','그때','지금','여기','거기','어디','언제','어떻게','무엇','어떤','누구','왜','왜냐하면','비록','않으면','동안','만약','이','그','이것들','그것들','각각','모든','어떤','몇몇','아무도','많은','적은','여러','다른','같은','다른','첫번째','마지막','다음','새로운','오래된','그리고','하지만','또는','도아닌','위해','게다가','그러나','그러므로','그동안','그럼에도','결과적으로','대신에',
];

// ── Chinese ──────────────────────────────────────────────────────────────────
const zh = [
  // Medical
  '头痛','发烧','恶心','头晕','过敏','癫痫发作','呼吸','疼痛','肿胀','出血','感染','处方','医院','诊所','护士','医生','轮椅','治疗','石膏','手术','注射','体温','咳嗽','皮疹','淤青','骨折','哮喘','糖尿病','癫痫','自闭症','多动症','焦虑','抑郁症','药物','剂量','症状','诊断','治疗方法','急诊','救护车','氧气','脉搏','血压','心脏','肺','胃','喉咙','耳朵','眼睛','皮肤','骨头','肌肉','关节','脊柱','大脑','肾脏','肝脏','呕吐','腹泻','便秘','疲劳','失眠','偏头痛','肺炎','支气管炎','贫血','中风','肿瘤','活检','X光','超声波','扫描','实验室','检查','结果','药房','药片','胶囊','糖浆','吸入器','雾化器','导管','绷带','缝合','夹板','拐杖','助行器','助听器','眼镜','假肢','呼吸机','监护仪','输液','生命体征','病历','转诊','专科医生','儿科医生','神经科医生','精神科医生','心脏病专家','牙医','眼科医生','外科医生','急救人员','分诊','康复','康复治疗','物理治疗','职业治疗','语言治疗','姑息','慢性','急性','传染性','免疫','疫苗','加强针','抗生素','抗病毒药','止痛药','镇静剂','麻醉','矫形器','吊带','坡道','无障碍','残疾','损伤','行动能力','痉挛','震颤','瘫痪','脑震荡','撕裂伤','烧伤','伤口','脓肿','炎症','水肿','麻木','刺痛','呼吸困难','胸痛','腹部','昏厥','过敏反应','血糖仪','胰岛素','透析','化疗','放疗','预后','缓解','知情同意','保密','病历记录',
  // Clinical / BCBA
  '行为','强化','提示','刺激','反应','基线','数据','试次','前因','后果','功能','逃避','注意','实物','感官','频率','持续时间','潜伏期','间隔','泛化','维持','消退','塑形','链接','示范','消退','时间表','代币','板','评估','偏好','探测','掌握','标准','图表','趋势','靶行为','目标','课题','技能','习得','流利度','离散','自然环境','随机教学','核心','要求语','命名','互动语','仿说','听者','接受性','表达性','言语行为','功能分析','功能评估','ABC数据','任务分析','逆向链接','正向链接','提示层级','从最少到最多','从最多到最少','时间延迟','无错误','纠正','差别强化','DRA','DRO','DRI','DRL','NCR','建立操作','区分性刺激','条件性强化物','初级强化物','次级强化物','变动比率','固定比率','变动间隔','固定间隔','观察者间一致性','治疗忠实度','社会效度','单一被试','多基线','反转设计','行为干预计划','功能性行为评估','个别化教育计划',
  // Daily Living
  '早上','下午','晚上','夜晚','早餐','午餐','晚餐','零食','淋浴','洗澡','刷牙','梳头','穿衣','脱衣','做饭','打扫','洗','擦干','折叠','扫地','吸尘','擦','购物','商店','钱','付钱','找零','收据','钱包','包','电梯','楼梯','人行横道','交通','人行道','建筑','公寓','卧室','厨房','客厅','浴室','车库','花园','院子','邻居','办公室','会议','电话','电子邮件','日历','预约','生日','假日','周末','工作日','星期一','星期二','星期三','星期四','星期五','星期六','星期日','一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月','时钟','时间','分钟','小时','今天','明天','昨天','早晨例程','就寝','闹钟','起床','坐下','站起来','躺下','走路','跑步','跳','爬','游泳','骑','开车','停车场','公交车','火车','地铁','出租车','飞机','自行车','滑板车','头盔','安全带','钥匙','锁','门','窗户','灯','风扇','空调','暖气','电视','遥控器','电脑','平板','充电器','电池','插座','开关','冰箱','微波炉','烤箱','炉灶','水槽','洗碗机','洗衣机','烘干机','垃圾','回收','宠物','猫','狗','鱼','鸟','动物园','博物馆','图书馆','公园','游乐场','游泳池','健身房','商场','餐厅','咖啡馆','面包店','银行','邮局','消防站','警察','天气','雨','雪','太阳','云','风','暴风雨','雨伞','外套','夹克','毛衣','衬衫','裤子','裙子','连衣裙','袜子','鞋','靴子','帽子','手套','围巾','牙刷','牙膏','肥皂','洗发水','毛巾','毯子','枕头','床','椅子','桌子','书桌','沙发','架子','抽屉','衣柜','镜子','画','植物','花','树',
  // Grammar Connectors
  '我是','你是','他是','她是','我们是','他们是','是的','曾经','将会','会','能','应该','可能','必须','将要','已经是','一直是','曾经是','打算','过去常常','能够','想要','需要','尝试','喜欢','不得不','关于','上面','穿过','之后','反对','沿着','之间','周围','之前','后面','下面','旁边','之间','超过','期间','除了','从','里面','进入','附近','外面','越过','经过','自从','通过','朝向','在下面','直到','在上面','在内','没有','也','已经','总是','从不','有时','经常','通常','很少','仍然','只是','甚至','非常','太','足够','几乎','真的','相当','宁可','然后','现在','这里','那里','哪里','什么时候','怎么','什么','哪个','谁','为什么','因为','虽然','除非','当','如果','这个','那个','这些','那些','每个','所有','任何','一些','没有','很多','少','几个','其他','相同','不同','第一','最后','下一个','新的','旧的','和','但是','或者','也不','为了','此外','然而','因此','同时','尽管如此','结果','反而',
];

// ── Arabic ───────────────────────────────────────────────────────────────────
const ar = [
  // Medical
  'صداع','حمى','غثيان','دوخة','حساسية','نوبة','تنفس','ألم','متورم','نزيف','عدوى','وصفة طبية','مستشفى','عيادة','ممرضة','طبيب','كرسي متحرك','علاج','جبيرة','جراحة','حقنة','درجة حرارة','سعال','طفح جلدي','كدمة','كسر','ربو','سكري','صرع','توحد','فرط الحركة','قلق','اكتئاب','دواء','جرعة','عرض','تشخيص','علاج','طوارئ','إسعاف','أكسجين','نبض','ضغط الدم','قلب','رئة','معدة','حلق','أذن','عين','جلد','عظم','عضلة','مفصل','عمود فقري','دماغ','كلية','كبد','قيء','إسهال','إمساك','إرهاق','أرق','صداع نصفي','التهاب رئوي','التهاب شعبي','فقر دم','سكتة دماغية','ورم','خزعة','أشعة سينية','موجات فوق صوتية','مسح','مختبر','فحص','نتائج','صيدلية','قرص','كبسولة','شراب','جهاز استنشاق','جهاز رذاذ','قسطرة','ضمادة','غرز','جبيرة','عكاز','مشاية','سماعة أذن','نظارات','طرف صناعي','جهاز تنفس','شاشة مراقبة','تنقيط وريدي','علامات حيوية','ملف طبي','تحويل','أخصائي','طبيب أطفال','طبيب أعصاب','طبيب نفسي','طبيب قلب','طبيب أسنان','طبيب عيون','جراح','مسعف','فرز','تعافي','تأهيل','علاج طبيعي','علاج وظيفي','علاج نطق','تلطيفي','مزمن','حاد','معدي','مناعة','لقاح','جرعة معززة','مضاد حيوي','مضاد فيروسات','مسكن','مهدئ','تخدير','دعامة','حمالة','منحدر','متاح','إعاقة','ضعف','حركة','تشنج','رعشة','شلل','ارتجاج','تمزق','حرق','جرح','خراج','التهاب','تورم','خدر','وخز','ضيق تنفس','ألم صدر','بطن','إغماء','تفاعل تحسسي','جهاز سكر','أنسولين','غسيل كلوي','علاج كيميائي','علاج إشعاعي','توقعات','هدأة','موافقة','سري','سجل طبي',
  // Clinical / BCBA
  'سلوك','تعزيز','تلقين','مثير','استجابة','خط أساس','بيانات','محاولة','سابقة','نتيجة','وظيفة','هروب','انتباه','ملموس','حسي','تكرار','مدة','كمون','فاصل','تعميم','صيانة','إطفاء','تشكيل','تسلسل','نمذجة','تلاشي','جدول','رمز','لوحة','تقييم','تفضيل','مسبار','إتقان','معيار','رسم بياني','اتجاه','هدف','غاية','مهارة','اكتساب','طلاقة','منفصل','بيئة طبيعية','تعليم عرضي','محوري','طلب','تسمية','لغة تفاعلية','صدى','مستمع','استقبالي','تعبيري','سلوك لفظي','تحليل وظيفي','تقييم وظيفي','بيانات أ ب ج','تحليل مهمة','تسلسل عكسي','تسلسل أمامي','تسلسل كلي','تدرج التلقين','أقل إلى أكثر','أكثر إلى أقل','تأخير زمني','بدون خطأ','تصحيح','تعزيز تفاضلي','دي آر إيه','دي آر أو','دي آر آي','دي آر إل','إن سي آر','عملية تحفيزية','مثير تمييزي','معزز مشروط','معزز أولي','معزز ثانوي','نسبة متغيرة','نسبة ثابتة','فاصل متغير','فاصل ثابت','اتفاق بين المراقبين','سلامة العلاج','صلاحية اجتماعية','موضوع واحد','خطوط أساس متعددة','تصميم انعكاسي','خطة تدخل سلوكي','تقييم سلوكي وظيفي','برنامج تعليمي فردي',
  // Daily Living
  'صباح','بعد الظهر','مساء','ليل','فطور','غداء','عشاء','وجبة خفيفة','دش','حمام','تنظيف الأسنان','مشط','لبس','خلع','طبخ','تنظيف','غسل','تجفيف','طي','كنس','مكنسة كهربائية','مسح','تسوق','متجر','مال','دفع','باقي','إيصال','محفظة','حقيبة','مصعد','سلالم','معبر مشاة','مرور','رصيف','مبنى','شقة','غرفة نوم','مطبخ','غرفة معيشة','مرآب','حديقة','فناء','جار','مكتب','اجتماع','هاتف','بريد','تقويم','موعد','عيد ميلاد','عطلة','نهاية الأسبوع','يوم عمل','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت','الأحد','يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر','ساعة','وقت','دقيقة','ساعة','اليوم','غداً','أمس','روتين صباحي','نوم','منبه','استيقاظ','جلوس','وقوف','استلقاء','مشي','جري','قفز','تسلق','سباحة','ركوب','قيادة','موقف','حافلة','قطار','مترو','تاكسي','طائرة','دراجة','سكوتر','خوذة','حزام أمان','مفتاح','قفل','باب','نافذة','ضوء','مروحة','مكيف','مدفأة','تلفزيون','جهاز تحكم','كمبيوتر','جهاز لوحي','شاحن','بطارية','مقبس','مفتاح كهربائي','ثلاجة','ميكروويف','فرن','موقد','حوض','غسالة صحون','غسالة','مجفف','قمامة','إعادة تدوير','حيوان أليف','قطة','كلب','سمك','طائر','حديقة حيوان','متحف','مكتبة','حديقة','ملعب','مسبح','صالة رياضية','مركز تجاري','مطعم','مقهى','مخبز','بنك','بريد','إطفاء','شرطة','طقس','مطر','ثلج','شمس','سحاب','رياح','عاصفة','مظلة','معطف','جاكيت','كنزة','قميص','بنطلون','تنورة','فستان','جوارب','حذاء','حذاء طويل','قبعة','قفازات','وشاح','فرشاة أسنان','معجون أسنان','صابون','شامبو','منشفة','بطانية','وسادة','سرير','كرسي','طاولة','مكتب','أريكة','رف','درج','خزانة','مرآة','صورة','نبات','زهرة','شجرة',
  // Grammar Connectors
  'أنا','أنت','هو','هي','نحن','هم','كان','كانت','كانوا','سوف','سيكون','يمكن','ينبغي','قد','يجب','سأكون','كنت','كان','سأذهب','اعتاد','قادر على','أريد','أحتاج','أحاول','أحب','يجب أن','حول','فوق','عبر','بعد','ضد','على طول','بين','حول','قبل','خلف','تحت','بجانب','بين','وراء','خلال','ما عدا','من','داخل','إلى','قرب','خارج','فوق','ماضي','منذ','عبر','نحو','تحت','حتى','على','ضمن','بدون','أيضاً','بالفعل','دائماً','أبداً','أحياناً','غالباً','عادةً','نادراً','لا يزال','فقط','حتى','جداً','أيضاً','كافي','تقريباً','حقاً','تماماً','بالأحرى','ثم','الآن','هنا','هناك','أين','متى','كيف','ماذا','أي','من','لماذا','لأن','بالرغم','ما لم','بينما','إذا','هذا','هذه','هؤلاء','أولئك','كل','جميع','أي','بعض','لا شيء','كثير','قليل','عدة','آخر','نفس','مختلف','أول','أخير','تالي','جديد','قديم','و','لكن','أو','ولا','من أجل','بالإضافة','ومع ذلك','لذلك','في غضون','مع ذلك','نتيجة','بدلاً',
];

export const CLINICAL_VOCABULARY: Record<SupportedLanguage, string[]> = {
  en, ro, es, fr, pt, de, ru, uk, ja, ko, zh, ar,
};

export function getClinicalVocabulary(lang: SupportedLanguage): string[] {
  return CLINICAL_VOCABULARY[lang] ?? CLINICAL_VOCABULARY.en;
}
