/**
 * Clinical vocabulary used by paid prediction and offline translation.
 *
 * Only independently keyed entries are allowed here. The original ~600-word
 * block was generated by zipping unequal per-locale arrays; once one locale
 * omitted an item, later translations were attached to the wrong English
 * concept. Wrong speech is more dangerous than an explicit missing
 * translation, so those legacy rows are intentionally excluded.
 */
import type { SupportedLanguage } from '@/engine/i18n';
import { CLINICAL_VOCAB_EXPANSION } from './clinicalVocabExpansion';

export interface VocabEntry {
  en: string;
  es?: string; fr?: string; pt?: string; ro?: string;
  uk?: string; ru?: string; de?: string; ja?: string; ko?: string;
  zh?: string; 'zh-Hans'?: string; 'zh-Hant'?: string; 'zh-HK'?: string;
  ar?: string; hi?: string; it?: string; pl?: string; he?: string;
  nl?: string; vi?: string; tl?: string; tr?: string; id?: string;
  bg?: string; am?: string; sw?: string; bn?: string;
}

/** Translation-safe, concept-keyed clinical vocabulary. */
export const CLINICAL_VOCAB: readonly VocabEntry[] = CLINICAL_VOCAB_EXPANSION;

function textFor(entry: VocabEntry, lang: SupportedLanguage): string | undefined {
  if (lang === 'en') return entry.en;
  return entry[lang as keyof VocabEntry] as string | undefined;
}

/** Returns exact concept mappings only; it never synthesizes a fallback pair. */
export function getClinicalDict(
  fromLang: SupportedLanguage,
  toLang: SupportedLanguage,
): Map<string, string> {
  const result = new Map<string, string>();
  for (const entry of CLINICAL_VOCAB) {
    const fromWord = textFor(entry, fromLang);
    const toWord = textFor(entry, toLang);
    if (fromWord && toWord && fromWord.toLowerCase() !== toWord.toLowerCase()) {
      result.set(fromWord.toLowerCase(), toWord);
    }
  }
  return result;
}

/**
 * Prediction words with real text for the requested locale. English fallback
 * is forbidden for non-English users because it creates mixed-language cards.
 */
export function getClinicalVocabulary(lang: SupportedLanguage): string[] {
  return CLINICAL_VOCAB.flatMap((entry) => {
    const text = textFor(entry, lang);
    return text ? [text] : [];
  });
}

/** @deprecated Use getClinicalDict for translation. */
export const CLINICAL_VOCABULARY: Partial<Record<SupportedLanguage, string[]>> = new Proxy(
  {} as Partial<Record<SupportedLanguage, string[]>>,
  { get: (_, lang) => getClinicalVocabulary(lang as SupportedLanguage) },
);
