/**
 * Offline Translation Dictionary (Part 1)
 *
 * 500 index-aligned entries across 6 languages: en, es, fr, de, ru, ro.
 * Entries 0-99: Common nouns | 100-199: Common verbs | 200-299: Common adjectives
 * Entries 300-399: Common phrases | 400-499: Time, numbers, connectors
 */

// eslint-disable-next-line prefer-const
let _OFFLINE_DICT_1: Record<string, string[]> = {
  en: [
    'house','car','dog','cat','water','food','school','book','phone','door','window','table','chair','bed','sun','moon','tree','flower','fish','bird','mother','father','child','baby','boy','girl','man','woman','doctor','teacher','friend','family','brother','sister','head','hand','foot','eye','ear','mouth','nose','heart','tooth','hair','face','body','arm','leg','back','stomach','milk','bread','rice','meat','egg','cheese','butter','sugar','salt','apple','banana','orange','cake','soup','tea','coffee','ball','toy','game','doll','picture','song','story','letter','word','name','number','color','red','blue','green','yellow','white','black','money','store','street','bus','train','airplane','boat','bicycle','shoe','shirt','pants','hat','coat','dress','sock','bag',
    'be','have','do','go','come','see','know','want','think','say','tell','give','take','make','get','put','find','help','try','ask','eat','drink','sleep','wake','walk','run','sit','stand','play','read','write','draw','sing','dance','cook','wash','clean','open','close','turn','stop','start','wait','listen','look','watch','speak','call','buy','pay','work','learn','teach','show','bring','carry','hold','touch','feel','hear','love','like','need','use','move','live','die','grow','fall','fly','swim','drive','ride','climb','jump','push','pull','throw','catch','cut','break','fix','build','cry','laugh','smile','kiss','hug','remember','forget','understand','believe','hope','wish','dream','choose','change','follow','meet','leave',
    'good','bad','big','small','long','short','tall','new','old','young','hot','cold','warm','fast','slow','happy','sad','angry','tired','hungry','thirsty','sick','strong','weak','clean','dirty','wet','dry','hard','soft','heavy','light','loud','quiet','dark','bright','beautiful','ugly','easy','difficult','right','wrong','true','false','safe','dangerous','important','funny','serious','nice','kind','mean','brave','smart','stupid','lazy','busy','free','rich','poor','cheap','expensive','full','empty','open','closed','ready','broken','same','different','other','next','last','first','only','many','few','more','less','all','every','some','any','own','real','sure','sorry','afraid','alone','alive','dead','early','late','far','near','deep','high','low','sweet','sour',
    'good morning','good afternoon','good evening','good night','how are you','I am fine','thank you','you are welcome','excuse me','I am sorry','please help','I need help','I am hungry','I am thirsty','I am tired','I am sick','it hurts','I feel good','I feel bad','I love you','I miss you','come here','go away','sit down','stand up','wake up','calm down','hurry up','slow down','be careful','watch out','wait for me','look at me','listen to me','tell me','show me','help me','give me','I want','I need','I like','I can','I cannot','what is this','where is','how much','what time','turn left','turn right','go straight','stop here','open the door','close the door','turn on','turn off','wash hands','brush teeth','get dressed','go to bed','time to eat','let us go','well done','try again','one more','all done','not yet','right now','over there','come back','I know','I do not know','I understand','I do not understand','yes please','no thank you','of course','no problem','see you later','take care','happy birthday','have a nice day','how old','what color','how many','which one','do you want','can I have','may I','I would like','my name is','nice to meet you','where do you live','I live in','what happened','are you okay','do not worry','it is okay','I am here','good job','let me see',
    'today','tomorrow','yesterday','morning','afternoon','evening','night','now','later','soon','always','never','sometimes','already','again','here','there','up','down','in','out','on','off','yes','no','and','but','or','because','if','when','where','what','who','how','why','this','that','very','too','also','only','just','before','after','during','with','without','for','from','to','at','between','under','over','behind','front','left','right','inside','outside','near','far','together','alone','more','less','enough','almost','really','maybe','hello','goodbye','okay','once','twice','zero','one','two','three','four','five','six','seven','eight','nine','ten','twenty','hundred','thousand','first','second','third','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'
  ],
  es: [
    'casa','coche','perro','gato','agua','comida','escuela','libro','teléfono','puerta','ventana','mesa','silla','cama','sol','luna','árbol','flor','pez','pájaro','madre','padre','niño','bebé','chico','chica','hombre','mujer','doctor','maestro','amigo','familia','hermano','hermana','cabeza','mano','pie','ojo','oreja','boca','nariz','corazón','diente','pelo','cara','cuerpo','brazo','pierna','espalda','estómago','leche','pan','arroz','carne','huevo','queso','mantequilla','azúcar','sal','manzana','plátano','naranja','pastel','sopa','té','café','pelota','juguete','juego','muñeca','imagen','canción','historia','carta','palabra','nombre','número','color','rojo','azul','verde','amarillo','blanco','negro','dinero','tienda','calle','autobús','tren','avión','barco','bicicleta','zapato','camisa','pantalón','sombrero','abrigo','vestido','calcetín','bolsa',
    'ser','tener','hacer','ir','venir','ver','saber','querer','pensar','decir','contar','dar','tomar','fabricar','obtener','poner','encontrar','ayudar','intentar','preguntar','comer','beber','dormir','despertar','caminar','correr','sentar','estar de pie','jugar','leer','escribir','dibujar','cantar','bailar','cocinar','lavar','limpiar','abrir','cerrar','girar','parar','empezar','esperar','escuchar','mirar','observar','hablar','llamar','comprar','pagar','trabajar','aprender','enseñar','mostrar','traer','llevar','sostener','tocar','sentir','oír','amar','gustar','necesitar','usar','mover','vivir','morir','crecer','caer','volar','nadar','conducir','montar','escalar','saltar','empujar','tirar','lanzar','atrapar','cortar','romper','arreglar','construir','llorar','reír','sonreír','besar','abrazar','recordar','olvidar','entender','creer','esperar','desear','soñar','elegir','cambiar','seguir','conocer','salir',
    'bueno','malo','grande','pequeño','largo','corto','alto','nuevo','viejo','joven','caliente','frío','cálido','rápido','lento','feliz','triste','enojado','cansado','hambriento','sediento','enfermo','fuerte','débil','limpio','sucio','mojado','seco','duro','suave','pesado','ligero','ruidoso','silencioso','oscuro','brillante','hermoso','feo','fácil','difícil','correcto','incorrecto','verdadero','falso','seguro','peligroso','importante','gracioso','serio','agradable','amable','cruel','valiente','inteligente','estúpido','perezoso','ocupado','libre','rico','pobre','barato','caro','lleno','vacío','abierto','cerrado','listo','roto','mismo','diferente','otro','siguiente','último','primero','solo','muchos','pocos','más','menos','todo','cada','algunos','cualquier','propio','real','seguro','lo siento','asustado','solo','vivo','muerto','temprano','tarde','lejos','cerca','profundo','alto','bajo','dulce','agrio',
    'buenos días','buenas tardes','buenas noches','buenas noches','cómo estás','estoy bien','gracias','de nada','disculpe','lo siento','por favor ayuda','necesito ayuda','tengo hambre','tengo sed','estoy cansado','estoy enfermo','me duele','me siento bien','me siento mal','te amo','te extraño','ven aquí','vete','siéntate','levántate','despierta','cálmate','apúrate','ve despacio','ten cuidado','cuidado','espérame','mírame','escúchame','dime','muéstrame','ayúdame','dame','quiero','necesito','me gusta','puedo','no puedo','qué es esto','dónde está','cuánto cuesta','qué hora es','gira a la izquierda','gira a la derecha','sigue derecho','para aquí','abre la puerta','cierra la puerta','enciende','apaga','lávate las manos','cepíllate los dientes','vístete','ve a la cama','hora de comer','vamos','bien hecho','inténtalo de nuevo','uno más','todo listo','todavía no','ahora mismo','por allá','regresa','lo sé','no lo sé','entiendo','no entiendo','sí por favor','no gracias','por supuesto','no hay problema','nos vemos luego','cuídate','feliz cumpleaños','que tengas un buen día','cuántos años','de qué color','cuántos','cuál','quieres','puedo tener','puedo','me gustaría','mi nombre es','mucho gusto','dónde vives','vivo en','qué pasó','estás bien','no te preocupes','está bien','estoy aquí','buen trabajo','déjame ver',
    'hoy','mañana','ayer','mañana','tarde','noche','noche','ahora','luego','pronto','siempre','nunca','a veces','ya','otra vez','aquí','allí','arriba','abajo','en','fuera','sobre','apagado','sí','no','y','pero','o','porque','si','cuando','dónde','qué','quién','cómo','por qué','esto','eso','muy','también','también','solo','justo','antes','después','durante','con','sin','para','de','a','en','entre','debajo','sobre','detrás','frente','izquierda','derecha','dentro','fuera','cerca','lejos','juntos','solo','más','menos','suficiente','casi','realmente','quizás','hola','adiós','está bien','una vez','dos veces','cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','veinte','cien','mil','primero','segundo','tercero','lunes','martes','miércoles','jueves','viernes','sábado','domingo'
  ],
  fr: [
    'maison','voiture','chien','chat','eau','nourriture','école','livre','téléphone','porte','fenêtre','table','chaise','lit','soleil','lune','arbre','fleur','poisson','oiseau','mère','père','enfant','bébé','garçon','fille','homme','femme','docteur','professeur','ami','famille','frère','sœur','tête','main','pied','œil','oreille','bouche','nez','cœur','dent','cheveux','visage','corps','bras','jambe','dos','estomac','lait','pain','riz','viande','œuf','fromage','beurre','sucre','sel','pomme','banane','orange','gâteau','soupe','thé','café','balle','jouet','jeu','poupée','image','chanson','histoire','lettre','mot','nom','numéro','couleur','rouge','bleu','vert','jaune','blanc','noir','argent','magasin','rue','bus','train','avion','bateau','vélo','chaussure','chemise','pantalon','chapeau','manteau','robe','chaussette','sac',
    'être','avoir','faire','aller','venir','voir','savoir','vouloir','penser','dire','raconter','donner','prendre','fabriquer','obtenir','mettre','trouver','aider','essayer','demander','manger','boire','dormir','réveiller','marcher','courir','asseoir','se lever','jouer','lire','écrire','dessiner','chanter','danser','cuisiner','laver','nettoyer','ouvrir','fermer','tourner','arrêter','commencer','attendre','écouter','regarder','observer','parler','appeler','acheter','payer','travailler','apprendre','enseigner','montrer','apporter','porter','tenir','toucher','sentir','entendre','aimer','aimer bien','avoir besoin','utiliser','bouger','vivre','mourir','grandir','tomber','voler','nager','conduire','monter','grimper','sauter','pousser','tirer','lancer','attraper','couper','casser','réparer','construire','pleurer','rire','sourire','embrasser','serrer','se souvenir','oublier','comprendre','croire','espérer','souhaiter','rêver','choisir','changer','suivre','rencontrer','partir',
    'bon','mauvais','grand','petit','long','court','grand','nouveau','vieux','jeune','chaud','froid','tiède','rapide','lent','heureux','triste','en colère','fatigué','affamé','assoiffé','malade','fort','faible','propre','sale','mouillé','sec','dur','doux','lourd','léger','bruyant','silencieux','sombre','lumineux','beau','laid','facile','difficile','juste','faux','vrai','faux','sûr','dangereux','important','drôle','sérieux','agréable','gentil','méchant','courageux','intelligent','stupide','paresseux','occupé','libre','riche','pauvre','bon marché','cher','plein','vide','ouvert','fermé','prêt','cassé','même','différent','autre','prochain','dernier','premier','seul','beaucoup','peu','plus','moins','tout','chaque','quelques','aucun','propre','réel','sûr','désolé','effrayé','seul','vivant','mort','tôt','tard','loin','proche','profond','haut','bas','sucré','aigre',
    'bonjour','bon après-midi','bonsoir','bonne nuit','comment allez-vous','je vais bien','merci','de rien','excusez-moi','je suis désolé','aidez-moi s\'il vous plaît','j\'ai besoin d\'aide','j\'ai faim','j\'ai soif','je suis fatigué','je suis malade','ça fait mal','je me sens bien','je me sens mal','je t\'aime','tu me manques','viens ici','va-t\'en','assieds-toi','lève-toi','réveille-toi','calme-toi','dépêche-toi','ralentis','fais attention','attention','attends-moi','regarde-moi','écoute-moi','dis-moi','montre-moi','aide-moi','donne-moi','je veux','j\'ai besoin','j\'aime','je peux','je ne peux pas','qu\'est-ce que c\'est','où est','combien','quelle heure est-il','tourne à gauche','tourne à droite','va tout droit','arrête-toi ici','ouvre la porte','ferme la porte','allume','éteins','lave-toi les mains','brosse-toi les dents','habille-toi','va au lit','c\'est l\'heure de manger','allons-y','bien joué','essaie encore','encore un','tout est fini','pas encore','maintenant','là-bas','reviens','je sais','je ne sais pas','je comprends','je ne comprends pas','oui s\'il vous plaît','non merci','bien sûr','pas de problème','à plus tard','prends soin de toi','joyeux anniversaire','bonne journée','quel âge','quelle couleur','combien','lequel','veux-tu','puis-je avoir','puis-je','je voudrais','je m\'appelle','enchanté','où habites-tu','j\'habite à','que s\'est-il passé','ça va','ne t\'inquiète pas','c\'est bon','je suis ici','bon travail','laisse-moi voir',
    'aujourd\'hui','demain','hier','matin','après-midi','soir','nuit','maintenant','plus tard','bientôt','toujours','jamais','parfois','déjà','encore','ici','là','haut','bas','dans','dehors','sur','éteint','oui','non','et','mais','ou','parce que','si','quand','où','quoi','qui','comment','pourquoi','ceci','cela','très','trop','aussi','seulement','juste','avant','après','pendant','avec','sans','pour','de','à','à','entre','sous','sur','derrière','devant','gauche','droite','intérieur','extérieur','près','loin','ensemble','seul','plus','moins','assez','presque','vraiment','peut-être','bonjour','au revoir','d\'accord','une fois','deux fois','zéro','un','deux','trois','quatre','cinq','six','sept','huit','neuf','dix','vingt','cent','mille','premier','deuxième','troisième','lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche'
  ],
  de: [
    'Haus','Auto','Hund','Katze','Wasser','Essen','Schule','Buch','Telefon','Tür','Fenster','Tisch','Stuhl','Bett','Sonne','Mond','Baum','Blume','Fisch','Vogel','Mutter','Vater','Kind','Baby','Junge','Mädchen','Mann','Frau','Arzt','Lehrer','Freund','Familie','Bruder','Schwester','Kopf','Hand','Fuß','Auge','Ohr','Mund','Nase','Herz','Zahn','Haar','Gesicht','Körper','Arm','Bein','Rücken','Magen','Milch','Brot','Reis','Fleisch','Ei','Käse','Butter','Zucker','Salz','Apfel','Banane','Orange','Kuchen','Suppe','Tee','Kaffee','Ball','Spielzeug','Spiel','Puppe','Bild','Lied','Geschichte','Brief','Wort','Name','Nummer','Farbe','rot','blau','grün','gelb','weiß','schwarz','Geld','Geschäft','Straße','Bus','Zug','Flugzeug','Boot','Fahrrad','Schuh','Hemd','Hose','Hut','Mantel','Kleid','Socke','Tasche',
    'sein','haben','tun','gehen','kommen','sehen','wissen','wollen','denken','sagen','erzählen','geben','nehmen','machen','bekommen','legen','finden','helfen','versuchen','fragen','essen','trinken','schlafen','aufwachen','gehen','laufen','sitzen','stehen','spielen','lesen','schreiben','zeichnen','singen','tanzen','kochen','waschen','putzen','öffnen','schließen','drehen','stoppen','anfangen','warten','zuhören','schauen','beobachten','sprechen','anrufen','kaufen','bezahlen','arbeiten','lernen','lehren','zeigen','bringen','tragen','halten','berühren','fühlen','hören','lieben','mögen','brauchen','benutzen','bewegen','leben','sterben','wachsen','fallen','fliegen','schwimmen','fahren','reiten','klettern','springen','drücken','ziehen','werfen','fangen','schneiden','brechen','reparieren','bauen','weinen','lachen','lächeln','küssen','umarmen','erinnern','vergessen','verstehen','glauben','hoffen','wünschen','träumen','wählen','ändern','folgen','treffen','verlassen',
    'gut','schlecht','groß','klein','lang','kurz','groß','neu','alt','jung','heiß','kalt','warm','schnell','langsam','glücklich','traurig','wütend','müde','hungrig','durstig','krank','stark','schwach','sauber','schmutzig','nass','trocken','hart','weich','schwer','leicht','laut','leise','dunkel','hell','schön','hässlich','einfach','schwierig','richtig','falsch','wahr','falsch','sicher','gefährlich','wichtig','lustig','ernst','nett','freundlich','gemein','mutig','klug','dumm','faul','beschäftigt','frei','reich','arm','billig','teuer','voll','leer','offen','geschlossen','bereit','kaputt','gleich','verschieden','andere','nächste','letzte','erste','einzige','viele','wenige','mehr','weniger','alle','jede','einige','irgendein','eigen','echt','sicher','tut mir leid','ängstlich','allein','lebendig','tot','früh','spät','weit','nah','tief','hoch','niedrig','süß','sauer',
    'guten Morgen','guten Tag','guten Abend','gute Nacht','wie geht es Ihnen','mir geht es gut','danke','bitte','entschuldigung','es tut mir leid','bitte helfen Sie','ich brauche Hilfe','ich habe Hunger','ich habe Durst','ich bin müde','ich bin krank','es tut weh','ich fühle mich gut','ich fühle mich schlecht','ich liebe dich','ich vermisse dich','komm her','geh weg','setz dich','steh auf','wach auf','beruhige dich','beeil dich','langsamer','sei vorsichtig','pass auf','warte auf mich','schau mich an','hör mir zu','sag mir','zeig mir','hilf mir','gib mir','ich will','ich brauche','ich mag','ich kann','ich kann nicht','was ist das','wo ist','wie viel','wie spät ist es','biege links ab','biege rechts ab','geh geradeaus','halt hier','öffne die Tür','schließe die Tür','einschalten','ausschalten','Hände waschen','Zähne putzen','anziehen','ins Bett gehen','Zeit zum Essen','lass uns gehen','gut gemacht','versuch es nochmal','noch eins','alles fertig','noch nicht','jetzt sofort','da drüben','komm zurück','ich weiß','ich weiß nicht','ich verstehe','ich verstehe nicht','ja bitte','nein danke','natürlich','kein Problem','bis später','pass auf dich auf','alles Gute zum Geburtstag','schönen Tag noch','wie alt','welche Farbe','wie viele','welches','möchtest du','kann ich haben','darf ich','ich möchte','mein Name ist','freut mich','wo wohnst du','ich wohne in','was ist passiert','geht es dir gut','mach dir keine Sorgen','es ist in Ordnung','ich bin hier','gute Arbeit','lass mich sehen',
    'heute','morgen','gestern','Morgen','Nachmittag','Abend','Nacht','jetzt','später','bald','immer','nie','manchmal','schon','wieder','hier','dort','oben','unten','in','aus','an','aus','ja','nein','und','aber','oder','weil','wenn','wann','wo','was','wer','wie','warum','dies','das','sehr','zu','auch','nur','gerade','vorher','nachher','während','mit','ohne','für','von','zu','bei','zwischen','unter','über','hinter','vorne','links','rechts','innen','außen','nah','weit','zusammen','allein','mehr','weniger','genug','fast','wirklich','vielleicht','hallo','auf Wiedersehen','okay','einmal','zweimal','null','eins','zwei','drei','vier','fünf','sechs','sieben','acht','neun','zehn','zwanzig','hundert','tausend','erste','zweite','dritte','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'
  ],
  ru: [
    'дом','машина','собака','кошка','вода','еда','школа','книга','телефон','дверь','окно','стол','стул','кровать','солнце','луна','дерево','цветок','рыба','птица','мать','отец','ребёнок','малыш','мальчик','девочка','мужчина','женщина','врач','учитель','друг','семья','брат','сестра','голова','рука','нога','глаз','ухо','рот','нос','сердце','зуб','волосы','лицо','тело','рука','нога','спина','живот','молоко','хлеб','рис','мясо','яйцо','сыр','масло','сахар','соль','яблоко','банан','апельсин','торт','суп','чай','кофе','мяч','игрушка','игра','кукла','картинка','песня','история','письмо','слово','имя','номер','цвет','красный','синий','зелёный','жёлтый','белый','чёрный','деньги','магазин','улица','автобус','поезд','самолёт','лодка','велосипед','ботинок','рубашка','штаны','шляпа','пальто','платье','носок','сумка',
    'быть','иметь','делать','идти','приходить','видеть','знать','хотеть','думать','говорить','рассказывать','давать','брать','создавать','получать','класть','находить','помогать','пытаться','спрашивать','есть','пить','спать','просыпаться','ходить','бегать','сидеть','стоять','играть','читать','писать','рисовать','петь','танцевать','готовить','мыть','убирать','открывать','закрывать','поворачивать','останавливать','начинать','ждать','слушать','смотреть','наблюдать','говорить','звонить','покупать','платить','работать','учиться','учить','показывать','приносить','нести','держать','трогать','чувствовать','слышать','любить','нравиться','нуждаться','использовать','двигаться','жить','умирать','расти','падать','летать','плавать','водить','ездить','лазить','прыгать','толкать','тянуть','бросать','ловить','резать','ломать','чинить','строить','плакать','смеяться','улыбаться','целовать','обнимать','помнить','забывать','понимать','верить','надеяться','желать','мечтать','выбирать','менять','следовать','встречать','уходить',
    'хороший','плохой','большой','маленький','длинный','короткий','высокий','новый','старый','молодой','горячий','холодный','тёплый','быстрый','медленный','счастливый','грустный','злой','усталый','голодный','жаждущий','больной','сильный','слабый','чистый','грязный','мокрый','сухой','твёрдый','мягкий','тяжёлый','лёгкий','громкий','тихий','тёмный','яркий','красивый','уродливый','лёгкий','трудный','правильный','неправильный','правдивый','ложный','безопасный','опасный','важный','смешной','серьёзный','приятный','добрый','злой','смелый','умный','глупый','ленивый','занятый','свободный','богатый','бедный','дешёвый','дорогой','полный','пустой','открытый','закрытый','готовый','сломанный','одинаковый','разный','другой','следующий','последний','первый','единственный','много','мало','больше','меньше','весь','каждый','некоторый','любой','собственный','настоящий','уверенный','извините','испуганный','одинокий','живой','мёртвый','ранний','поздний','далёкий','близкий','глубокий','высокий','низкий','сладкий','кислый',
    'доброе утро','добрый день','добрый вечер','спокойной ночи','как дела','я в порядке','спасибо','пожалуйста','извините','мне жаль','помогите пожалуйста','мне нужна помощь','я голоден','я хочу пить','я устал','я болен','мне больно','я чувствую себя хорошо','я чувствую себя плохо','я люблю тебя','я скучаю по тебе','иди сюда','уходи','садись','встань','проснись','успокойся','поторопись','помедленнее','будь осторожен','осторожно','подожди меня','посмотри на меня','послушай меня','скажи мне','покажи мне','помоги мне','дай мне','я хочу','мне нужно','мне нравится','я могу','я не могу','что это','где находится','сколько стоит','который час','поверни налево','поверни направо','иди прямо','остановись здесь','открой дверь','закрой дверь','включи','выключи','вымой руки','почисти зубы','одевайся','ложись спать','пора есть','пойдём','молодец','попробуй ещё раз','ещё один','всё готово','ещё нет','прямо сейчас','вон там','вернись','я знаю','я не знаю','я понимаю','я не понимаю','да пожалуйста','нет спасибо','конечно','нет проблем','увидимся позже','береги себя','с днём рождения','хорошего дня','сколько лет','какой цвет','сколько','который','ты хочешь','можно мне','можно','я бы хотел','меня зовут','приятно познакомиться','где ты живёшь','я живу в','что случилось','ты в порядке','не волнуйся','всё хорошо','я здесь','хорошая работа','дай мне посмотреть',
    'сегодня','завтра','вчера','утро','день','вечер','ночь','сейчас','позже','скоро','всегда','никогда','иногда','уже','снова','здесь','там','вверх','вниз','в','из','на','выключено','да','нет','и','но','или','потому что','если','когда','где','что','кто','как','почему','это','то','очень','тоже','также','только','просто','до','после','во время','с','без','для','от','к','в','между','под','над','за','перед','лево','право','внутри','снаружи','близко','далеко','вместе','одному','больше','меньше','достаточно','почти','действительно','может быть','привет','до свидания','хорошо','один раз','дважды','ноль','один','два','три','четыре','пять','шесть','семь','восемь','девять','десять','двадцать','сто','тысяча','первый','второй','третий','понедельник','вторник','среда','четверг','пятница','суббота','воскресенье'
  ],
  ro: [
    'casă','mașină','câine','pisică','apă','mâncare','școală','carte','telefon','ușă','fereastră','masă','scaun','pat','soare','lună','copac','floare','pește','pasăre','mamă','tată','copil','bebeluș','băiat','fată','bărbat','femeie','doctor','profesor','prieten','familie','frate','soră','cap','mână','picior','ochi','ureche','gură','nas','inimă','dinte','păr','față','corp','braț','picior','spate','stomac','lapte','pâine','orez','carne','ou','brânză','unt','zahăr','sare','măr','banană','portocală','tort','supă','ceai','cafea','minge','jucărie','joc','păpușă','imagine','cântec','poveste','scrisoare','cuvânt','nume','număr','culoare','roșu','albastru','verde','galben','alb','negru','bani','magazin','stradă','autobuz','tren','avion','barcă','bicicletă','pantof','cămașă','pantaloni','pălărie','palton','rochie','șosetă','geantă',
    'a fi','a avea','a face','a merge','a veni','a vedea','a ști','a vrea','a gândi','a spune','a povesti','a da','a lua','a fabrica','a obține','a pune','a găsi','a ajuta','a încerca','a întreba','a mânca','a bea','a dormi','a trezi','a merge','a alerga','a ședea','a sta în picioare','a juca','a citi','a scrie','a desena','a cânta','a dansa','a găti','a spăla','a curăța','a deschide','a închide','a întoarce','a opri','a începe','a aștepta','a asculta','a privi','a urmări','a vorbi','a suna','a cumpăra','a plăti','a lucra','a învăța','a preda','a arăta','a aduce','a duce','a ține','a atinge','a simți','a auzi','a iubi','a plăcea','a avea nevoie','a folosi','a mișca','a trăi','a muri','a crește','a cădea','a zbura','a înota','a conduce','a călări','a urca','a sări','a împinge','a trage','a arunca','a prinde','a tăia','a sparge','a repara','a construi','a plânge','a râde','a zâmbi','a săruta','a îmbrățișa','a aminti','a uita','a înțelege','a crede','a spera','a dori','a visa','a alege','a schimba','a urma','a întâlni','a pleca',
    'bun','rău','mare','mic','lung','scurt','înalt','nou','vechi','tânăr','fierbinte','rece','cald','rapid','lent','fericit','trist','supărat','obosit','flămând','însetat','bolnav','puternic','slab','curat','murdar','ud','uscat','tare','moale','greu','ușor','tare','liniștit','întunecat','luminos','frumos','urât','ușor','dificil','corect','greșit','adevărat','fals','sigur','periculos','important','amuzant','serios','drăguț','amabil','rău','curajos','deștept','prost','leneș','ocupat','liber','bogat','sărac','ieftin','scump','plin','gol','deschis','închis','gata','stricat','același','diferit','alt','următor','ultimul','primul','singurul','mulți','puțini','mai mult','mai puțin','tot','fiecare','unii','orice','propriu','real','sigur','îmi pare rău','speriat','singur','viu','mort','devreme','târziu','departe','aproape','adânc','înalt','jos','dulce','acru',
    'bună dimineața','bună ziua','bună seara','noapte bună','ce mai faci','sunt bine','mulțumesc','cu plăcere','scuzați-mă','îmi pare rău','vă rog ajutați-mă','am nevoie de ajutor','mi-e foame','mi-e sete','sunt obosit','sunt bolnav','mă doare','mă simt bine','mă simt rău','te iubesc','mi-e dor de tine','vino aici','pleacă','așează-te','ridică-te','trezește-te','calmează-te','grăbește-te','încetinește','fii atent','atenție','așteaptă-mă','uită-te la mine','ascultă-mă','spune-mi','arată-mi','ajută-mă','dă-mi','vreau','am nevoie','îmi place','pot','nu pot','ce este asta','unde este','cât costă','cât este ceasul','virează la stânga','virează la dreapta','mergi drept','oprește-te aici','deschide ușa','închide ușa','pornește','oprește','spală-te pe mâini','spală-te pe dinți','îmbracă-te','du-te la culcare','e timpul să mâncăm','hai să mergem','bravo','încearcă din nou','încă unul','totul gata','încă nu','chiar acum','acolo','întoarce-te','știu','nu știu','înțeleg','nu înțeleg','da vă rog','nu mulțumesc','bineînțeles','nicio problemă','ne vedem mai târziu','ai grijă de tine','la mulți ani','o zi frumoasă','câți ani','ce culoare','câți','care','vrei','pot să am','pot','aș vrea','mă numesc','încântat de cunoștință','unde locuiești','locuiesc în','ce s-a întâmplat','ești bine','nu-ți face griji','e în regulă','sunt aici','treabă bună','lasă-mă să văd',
    'astăzi','mâine','ieri','dimineață','după-amiază','seară','noapte','acum','mai târziu','curând','întotdeauna','niciodată','uneori','deja','din nou','aici','acolo','sus','jos','în','afară','pe','oprit','da','nu','și','dar','sau','pentru că','dacă','când','unde','ce','cine','cum','de ce','acesta','acela','foarte','prea','de asemenea','doar','chiar','înainte','după','în timpul','cu','fără','pentru','de la','la','la','între','sub','peste','în spate','în față','stânga','dreapta','înăuntru','afară','aproape','departe','împreună','singur','mai mult','mai puțin','destul','aproape','chiar','poate','salut','la revedere','bine','o dată','de două ori','zero','unu','doi','trei','patru','cinci','șase','șapte','opt','nouă','zece','douăzeci','o sută','o mie','primul','al doilea','al treilea','luni','marți','miercuri','joi','vineri','sâmbătă','duminică'
  ],
  pt: [
    'casa','carro','cachorro','gato','água','comida','escola','livro','telefone','porta','janela','mesa','cadeira','cama','sol','lua','árvore','flor','peixe','pássaro','mãe','pai','criança','bebê','menino','menina','homem','mulher','médico','professor','amigo','família','irmão','irmã','cabeça','mão','pé','olho','ouvido','boca','nariz','coração','dente','cabelo','rosto','corpo','braço','perna','costas','estômago','leite','pão','arroz','carne','ovo','queijo','manteiga','açúcar','sal','maçã','banana','laranja','bolo','sopa','chá','café','bola','brinquedo','jogo','boneca','imagem','música','história','carta','palavra','nome','número','cor','vermelho','azul','verde','amarelo','branco','preto','dinheiro','loja','rua','ônibus','trem','avião','barco','bicicleta','sapato','camisa','calça','chapéu','casaco','vestido','meia','mala',
    'ser','ter','fazer','ir','vir','ver','saber','querer','pensar','dizer','contar','dar','pegar','fazer','pegar','colocar','encontrar','ajudar','tentar','perguntar','comer','beber','dormir','acordar','caminhar','correr','sentar','ficar','brincar','ler','escrever','desenhar','cantar','dançar','cozinhar','lavar','limpar','abrir','fechar','virar','parar','começar','esperar','ouvir','olhar','assistir','falar','chamar','comprar','pagar','trabalhar','aprender','ensinar','mostrar','trazer','carregar','segurar','tocar','sentir','ouvir','amar','gostar','precisar','usar','mover','viver','morrer','crescer','cair','voar','nadar','dirigir','andar','subir','pular','empurrar','puxar','jogar','pegar','cortar','quebrar','consertar','construir','chorar','rir','sorrir','beijar','abraçar','lembrar','esquecer','entender','acreditar','esperar','desejar','sonhar','escolher','mudar','seguir','encontrar','sair',
    'bom','ruim','grande','pequeno','longo','curto','alto','novo','velho','jovem','quente','frio','quente','rápido','lento','feliz','triste','bravo','cansado','com fome','com sede','doente','forte','fraco','limpo','sujo','molhado','seco','duro','macio','pesado','leve','alto','silencioso','escuro','brilhante','bonito','feio','fácil','difícil','certo','errado','verdadeiro','falso','seguro','perigoso','importante','engraçado','sério','legal','gentil','malvado','corajoso','inteligente','estúpido','preguiçoso','ocupado','livre','rico','pobre','barato','caro','cheio','vazio','aberto','fechado','pronto','quebrado','igual','diferente','outro','próximo','último','primeiro','único','muitos','poucos','mais','menos','todos','cada','alguns','qualquer','próprio','real','certeza','desculpe','com medo','sozinho','vivo','morto','cedo','tarde','longe','perto','profundo','alto','baixo','doce','azedo',
    'bom dia','boa tarde','boa noite','boa noite','como você está','estou bem','obrigado','de nada','com licença','me desculpe','por favor, me ajude','preciso de ajuda','estou com fome','estou com sede','estou cansado','estou doente','está doendo','me sinto bem','me sinto mal','eu te amo','sinto sua falta','venha aqui','vá embora','sente-se','levante-se','acorde','acalme-se','se apresse','devagar','cuidado','cuidado','me espere','me olhe','me ouça','me conte','me mostre','me ajude','me dê','quero','preciso','gosto','posso','não posso','o que é isso','onde está','quanto custa','que horas são','vire à esquerda','vire à direita','siga em frente','pare aqui','abra a porta','feche a porta','ligue','desligue','lave as mãos','escove os dentes','se vista','vá para a cama','hora de comer','vamos lá','bem feito','tente de novo','mais uma vez','já acabou','ainda não','agora','lá','volte','eu sei','não sei','eu entendo','não entendo','sim, por favor','não, obrigado','claro','sem problema','até mais','cuide-se','feliz aniversário','tenha um bom dia','quantos anos','que cor','quantos','qual','você quer','posso ter','posso','gostaria de','meu nome é','prazer em conhecê-lo','onde você mora','moro em','o que aconteceu','você está bem','não se preocupe','tudo bem','estou aqui','bom trabalho','deixe-me ver',
    'hoje','amanhã','ontem','manhã','tarde','noite','noite','agora','mais tarde','em breve','sempre','nunca','às vezes','já','novamente','aqui','lá','para cima','para baixo','em','fora','em cima','fora','sim','não','e','mas','ou','porque','se','quando','onde','o que','quem','como','por que','este','isso','muito','muito','também','apenas','apenas','antes','depois','durante','com','sem','para','de','para','em','entre','sob','sobre','atrás','frente','esquerda','direita','dentro','fora','perto','longe','juntos','sozinho','mais','menos','suficiente','quase','realmente','talvez','olá','adeus','okay','uma vez','duas vezes','zero','um','dois','três','quatro','cinco','seis','sete','oito','nove','dez','vinte','cem','mil','primeiro','segundo','terceiro','segunda-feira','terça-feira','quarta-feira','quinta-feira','sexta-feira','sábado','domingo'
  ],
  uk: [
    'дім','автомобіль','собака','кіт','вода','їжа','школа','книга','телефон','двері','вікно','стіл','стілець','ліжко','сонце','місяць','дерево','квітка','риба','птах','мама','тато','дитина','малюк','хлопець','дівчина','чоловік','жінка','лікар','вчитель','друг','сім\'я','брат','сестра','голова','рука','нога','око','вухо','рот','нос','серце','зуб','волосся','лице','тіло','рука','нога','спина','живот','молоко','хліб','риж','м\'ясо','яйце','сир','масло','цукор','сіль','яблуко','банан','апельсин','торт','суп','чай','кава','мича','іграшка','гра','лялька','картинка','пісня','повість','лист','слово','ім\'я','число','колір','червоний','синій','зелений','жовтий','білий','чорний','гроші','магазин','вулиця','автобус','потяг','літак','човен','велосипед','чобіт','сорочка','штани','капелюх','пальто','сукня','чорта','сумка',
    'бути','мати','робити','ходити','приходити','бачити','знати','хотіти','думати','говорити','розв\'язати','давати','брати','робити','отримувати','клавдати','знайти','допомагати','спробувати','питати','їсти','пиймати','спати','прокинутися','ходити','бігти','сидіти','стояти','грати','читати','писати','малювати','співати','танцювати','готувати','мити','чистити','відкривати','закривати','вертіти','зупинятися','починати','чекати','слухати','дивитися','дивитися','говорити','зв\'язатися','купати','платити','працювати','вчитися','вчити','показувати','принести','нести','тримати','дотикатися','відчувати','чути','кохати','подобатися','потрібно','використовувати','рухатися','живти','помирати','зростати','падати','літати','плавати','водити','їхати','лазити','скакати','тиснути','тягнути','кидати','ловити','різати','ламати','ремонтувати','будувати','плакати','сміятися','уśmieятися','цілувати','обіймати','пам\'ятати','забувати','розуміти','вірити','надіятися','бажати','спати','вибирати','змінювати','слідувати','зустрічатися','залишати',
    'добрий','злий','великий','малий','довгий','короткий','високий','новий','старий','молодий','гарячий','холодний','теплий','швидкий','повільний','щасливий','сумний','злий','втомлений','голодний','спраглий','хворий','силений','слабкий','чистий','брудний','мокрий','сухий','твердий','м’який','важкий','легкий','гучний','тихий','темний','яскравий','красивий','відстебний','легкий','складний','правильний','неправильний','істинний','хибний','безпечний','небезпечний','важливий','смішний','суворий','приємний','добрий','злий','бравий','розумний','глупий','лінивий','зайнятий','вільний','багатий','бідний','дешевий','дорогий','повний','пустий','відкритий','закритий','готовий','зламаний','такий самий','різний','інший','наступний','останній','перший','єдиний','багато','мало','більше','менше','все','кожен','деякі','будь-який','власний','справжній','впевнений','вибач','страх','одинокий','живий','мертвий','ранній','пізний','далекий','близький','глибокий','високий','низький','солодкий','кислий',
    'добре ранку','добре дня','добре вечора','доброї ночі','як справи','мені добре','дякую','на здоров\'я','відпardon','вибачте','допоможіть будь ласка','мені потрібна допомога','я голодний','я спраглий','я втомився','мені погано','це болить','мені добре','мені погано','я тебе кохаю','я тебе скучу','підйди сюди','відходь','сідай','встань','прокинься','спокійніше','швидше','повільніше','будь обережний','бережіться','почекайте на мене','поглянь на мене','відгукнись на мене','расскажи мені','покажи мені','допоможи мені','дай мені','я хочу','мені потрібно','мені подобається','я можу','я не можу','що це','де','скільки коштує','що за час','поверни наліво','поверни направо','їдь прямо','зупинись тут','відкрий двері','закрий двері','ввімкни','вимкни','помий руки','почисти зуби','одягнись','лігай спати','пора їсти','давай підемо','добре зроблено','спробуй ще раз','ще раз','все готово','ще не','зараз','там','повернись','я знаю','я не знаю','я розумію','я не розумію','так, будь ласка','ні, дякую','звісно','не проблема','бачимось пізніше','бережіть себе','щасливого дня народження','приємного дня','скільки тобі років','який колір','скільки','який','хочеш','можу я','чи можу я','я б хотів','мене звати','приємно познайомитися','де ти живеш','я живу','що сталося','ти в порядку','не хвилюйся','це добре','я тут','добре зроблено','дай мені подивитися',
    'сьогодні','завтра','вчора','ранок','день','вечір','ноч','зараз','пізніше','скоро','завжди','ніколи','іноді','вже','знову','тут','там','вгору','вниз','в','вон','на','від','так','ні','і','але','або','бо','якщо','коли','де','що','хто','як','чому','цей','той','дуже','дуже','також','лише','тільки','до','після','під час','з','без','для','з','до','в','між','під','над','позади','спереду','ліворуч','праворуч','всередині','ззовні','біля','далеко','разом','один','більше','менше','достатньо','майже','дійсно','можливо','привіт','бувай','добре','один раз','двічі','нуль','один','два','три','чотири','п\'ять','шість','сім','вісім','дев\'ять','десять','двадцять','сто','тисяча','перший','другий','третій','понеділок','вівторок','середа','четвер','п\'ятниця','субота','неділя'
  ],
  'zh-Hans': [
    '房子','汽车','狗','猫','水','食物','学校','书','电话','门','窗户','桌子','椅子','床','太阳','月亮','树','花','鱼','鸟','妈妈','爸爸','孩子','婴儿','男孩','女孩','男人','女人','医生','老师','朋友','家庭','哥哥','姐姐','头','手','脚','眼睛','耳朵','嘴巴','鼻子','心脏','牙齿','头发','脸','身体','胳膊','腿','后背','胃','牛奶','面包','米饭','肉','鸡蛋','奶酪','黄油','糖','盐','苹果','香蕉','橙子','蛋糕','汤','茶','咖啡','球','玩具','游戏','娃娃','图片','歌曲','故事','信','单词','名字','数字','颜色','红色','蓝色','绿色','黄色','白色','黑色','钱','商店','街道','公共汽车','火车','飞机','船','自行车','鞋子','衬衫','裤子','帽子','外套','裙子','袜子','包',
    '是','有','做','去','来','看','知道','想要','认为','说','告诉','给','拿','做','得到','放','找到','帮助','尝试','问','吃','喝','睡觉','醒来','走','跑','坐','站','玩','读','写','画','唱歌','跳舞','做饭','洗','打扫','打开','关闭','转动','停止','开始','等待','听','看','观看','说话','打电话','买','支付','工作','学习','教','展示','带来','携带','拿住','触摸','感觉','听到','爱','喜欢','需要','使用','移动','生活','死亡','生长','落下','飞','游泳','开车','骑','爬','跳','推','拉','扔','接住','切','打破','修理','建造','哭','笑','微笑','吻','拥抱','记得','忘记','理解','相信','希望','愿望','做梦','选择','改变','跟随','遇见','离开',
    '好','坏','大','小','长','短','高','新','旧','年轻','热','冷','暖和','快','慢','快乐','悲伤','生气','累','饿','渴','生病','强壮','虚弱','干净','脏','湿','干','硬','软','重','轻','大声','安静','黑暗','明亮','美丽','丑陋','容易','困难','正确','错误','真实','虚假','安全','危险','重要','有趣','严肃','好','善良','刻薄','勇敢','聪明','愚蠢','懒惰','忙碌','自由','富有','贫穷','便宜','昂贵','满的','空的','打开','关闭','准备好了','坏了','相同的','不同的','其他的','下一个','最后一个','第一个','唯一的','许多','少数','更多','更少','全部','每个','一些','任何','自己的','真实的','确定','抱歉','害怕','孤独','活着','死了','早','晚','远','近','深','高','低','甜','酸',
    '早上好','下午好','晚上好','晚安','你好吗','我很好','谢谢','不客气','对不起','我很抱歉','请帮忙','我需要帮助','我饿了','我渴了','我累了','我生病了','我疼','我感觉很好','我感觉不好','我爱你','我想你','过来','走开','坐下','站起来','醒来','冷静点','快点','慢点','小心点','当心','等我','看着我','听我说','告诉我','给我看','帮帮我','给我','我要','我需要','我喜欢','我会','我不会','这是什么','在哪里','多少钱','几点了','左转','右转','直走','在这里停车','开门','关门','打开','关闭','洗手','刷牙','穿衣服','上床睡觉','该吃饭了','我们走吧','做得好','再试一次','再来一次','完成了','还没有','现在','那边','回来','我知道','我不知道','我明白','我不明白','好的','不用了','当然可以','没问题','一会儿见','保重','生日快乐','祝你一天愉快','多大了','什么颜色','多少','哪一个','你想要吗','我可以有','我可以吗','我想要','我叫','很高兴见到你','你住在哪里','我住在','发生了什么','你没事吧','别担心','没关系','我在这里','干得好','让我看看',
    '今天','明天','昨天','早晨','下午','晚上','夜晚','现在','稍后','很快','总是','从不','有时','已经','再次','这里','那里','上','下','在...里','出来','在...上','离开','是','不是','和','但是','或者','因为','如果','什么时候','哪里','什么','谁','怎么','为什么','这个','那个','非常','太','也','只有','仅仅','在...之前','在...之后','在...期间','和...一起','没有','为了','从','到','在','在...之间','在...下面','在...上面','在...后面','前面','左边','右边','在...里面','在...外面','附近','远处','一起','独自','更多','更少','足够','几乎','真的','可能','你好','再见','好的','一次','两次','零','一','二','三','四','五','六','七','八','九','十','二十','一百','一千','第一','第二','第三','星期一','星期二','星期三','星期四','星期五','星期六','星期日'
  ],
  'zh-Hant': [
    '房子','汽車','狗','貓','水','食物','學校','書','電話','門','窗戶','桌子','椅子','床','太陽','月亮','樹','花','魚','鳥','媽媽','爸爸','孩子','寶寶','男孩','女孩','男人','女人','醫生','老師','朋友','家庭','哥哥','姐姐','頭','手','腳','眼睛','耳朵','嘴巴','鼻子','心臟','牙齒','頭髮','臉','身體','手臂','腿','背部','胃','牛奶','麵包','米','肉','雞蛋','起司','奶油','糖','鹽','蘋果','香蕉','橘子','蛋糕','湯','茶','咖啡','球','玩具','遊戲','娃娃','圖片','歌','故事','信','字','名字','數字','顏色','紅色','藍色','綠色','黃色','白色','黑色','錢','商店','街道','公車','火車','飛機','船','自行車','鞋子','襯衫','褲子','帽子','外套','裙子','襪子','袋子',
    '是','有','做','去','來','看','知道','想要','想','說','告訴','給','拿','做','得到','放','找到','幫助','嘗試','問','吃','喝','睡覺','醒來','走','跑','坐','站','玩','讀','寫','畫','唱歌','跳舞','煮飯','洗','清潔','打開','關上','轉','停止','開始','等','聽','看','看','說話','打電話','買','付錢','工作','學習','教','展示','帶','搬','拿著','觸摸','感覺','聽到','愛','喜歡','需要','使用','移動','居住','死亡','生長','掉落','飛','游泳','開車','騎','爬','跳','推','拉','扔','接住','切','打破','修理','建造','哭','笑','微笑','吻','擁抱','記住','忘記','理解','相信','希望','希望','夢想','選擇','改變','跟隨','見面','離開',
    '好','壞','大','小','長','短','高','新','舊','年輕','熱','冷','溫暖','快','慢','開心','難過','生氣','累','餓','渴','生病','強壯','虛弱','乾淨','骯髒','濕','乾','硬','軟','重','輕','大聲','安靜','暗','亮','漂亮','醜','容易','困難','對','錯','真實','虛假','安全','危險','重要','有趣','嚴肅','好','善良','刻薄','勇敢','聰明','愚蠢','懶','忙','自由','富有','貧窮','便宜','昂貴','滿的','空的','打開','關閉','準備好','壞了','一樣','不同','其他','下一個','上一個','第一個','唯一','許多','少數','更多','更少','全部','每個','一些','任何','自己的','真實的','確定','抱歉','害怕','孤單','活著','死了','早','晚','遠','近','深','高','低','甜','酸',
    '早安','午安','晚安','晚安','你好嗎','我很好','謝謝','不客氣','請問','對不起','請幫我','我需要幫助','我餓了','我渴了','我累了','我生病了','我痛','我感覺很好','我感覺不好','我愛你','我想你','過來','走開','坐下','站起來','醒醒','冷靜點','快點','慢點','小心','注意','等我','看我','聽我說','告訴我','給我看','幫我','給我','我想要','我需要','我喜歡','我可以','我不能','這是什麼','在哪裡','多少錢','幾點','左轉','右轉','直走','在這裡停','打開門','關上門','打開','關掉','洗手','刷牙','穿衣服','去睡覺','該吃飯了','我們走吧','做得好','再試一次','再來一次','完成了','還沒有','現在','在那裡','回來','我知道','我不知道','我懂','我不懂','好的','不用了','當然可以','沒問題','待會見','保重','生日快樂','祝你有美好的一天','幾歲','什麼顏色','多少','哪一個','你想要','我可以有','我可以','我想要','我叫','很高興認識你','你住哪裡','我住在','發生了什麼事','你沒事吧','別擔心','沒關係','我在这里','做得好','讓我看看',
    '今天','明天','昨天','早上','下午','晚上','夜晚','現在','稍後','很快','總是','從不','有時候','已經','再次','這裡','那裡','上','下','在...裡','出來','在...上','關掉','是的','不是','和','但是','或者','因為','如果','當...時候','在哪裡','什麼','誰','怎麼','為什麼','這個','那個','非常','太','也','只有','只是','在...之前','在...之後','在...期間','和...一起','沒有','為了','從','到','在','在...之間','在...下面','在...上面','在...後面','前面','左邊','右邊','在...裡面','在...外面','附近','遠處','一起','單獨','更多','更少','足夠','幾乎','真的','也許','你好','再見','好的','一次','兩次','零','一','二','三','四','五','六','七','八','九','十','二十','一百','一千','第一','第二','第三','星期一','星期二','星期三','星期四','星期五','星期六','星期日'
  ],
  'zh-HK': [
    '屋企','車','狗','貓','水','食物','學校','書','電話','門','窗','枱','椅','牀','太陽','月亮','樹','花','魚','雀仔','媽媽','爸爸','小朋友','BB','細路','女仔','男人','女人','醫生','老師','朋友','家庭','哥哥','姐姐','頭','手','腳','眼','耳','口','鼻','心','牙','頭髮','臉','身軀','手臋','腳','背','肚','牛奶','包','飯','肉','雞蛋','芝士','牛油','糖','鹽','蘋果','香蕉','橙','蛋糕','湯','茶','咖啡','波','玩具','遊戲','公仔','相片','歌','故事','信','字','名','數字','顏色','紅色','藍色','綠色','黃色','白色','黑色','錢','舖頭','街','巴士','火車','飛機','船','單車','鞋','恤衫','褲','帽','大衣','裙','襪','袋',
    '係','有','做','去','嚟','見','知','想','谂','講','話','畀','拿','整','搵','放','搵到','幫','試','問','食','飲','瞓','醒','行','跑','坐','企','玩','睇','寫','畫','唱','跳','煮','洗','掃','開','關','轉','停','開始','等','聽','睇','睇','講','打','買','俾錢','做','學','教','示','帶','拎','揸','摸','覺','聽見','愛','鍾意','要','用','搬','住','死','大','跌','飛','游','揸車','騎','爬','跳','推','拉','掟','捉','剪','拗斷','修','起','喊','笑','笑','吻','抱','記起','忘記','明白','信','希望','願望','夢','揀','改','跟','見','走',
    'good','bad','big','small','long','short','tall','new','old','young','hot','cold','warm','fast','slow','happy','sad','angry','tired','hungry','thirsty','sick','strong','weak','clean','dirty','wet','dry','hard','soft','heavy','light','loud','quiet','dark','bright','beautiful','ugly','easy','difficult','right','wrong','true','false','safe','dangerous','important','funny','serious','nice','kind','mean','brave','smart','stupid','lazy','busy','free','rich','poor','cheap','expensive','full','empty','open','closed','ready','broken','same','different','other','next','last','first','only','many','few','more','less','all','every','some','any','own','real','sure','sorry','afraid','alone','alive','dead','early','late','far','near','deep','high','low','sweet','sour',
    '早晨','午後好','晚間好','晚安','你點樣','我冇事','多謝','唔使客氣','借借步','對唔住','幫幫手','我需要幫忙','我餓咗','我渴咗','我好累','我唔舒服','好痛','我好開心','我唔開心','我愛你','我好挂住你','嚟到呢度','走開','坐低','企起身','醒醒','冷靜啲','快啲','慢啲','小心啲','睇住啲','等我下','睇住我','聽住我','講俾我聽','俾我睇','幫幫我','俾我','我想要','我需要','我鍾意','我做得到','我做不到','呢個係咩','喺邊度','幾多錢','幾點','向左轉','向右轉','直頭行','喺呢度停','開門','關門','開啲','關啲','洗手','刷牙','換衫','瞓覺','食嘅時間','我哋走吧','做得好','再試一次','再嚟一次','搞掂喇','仲未','即刻','喺度','返嚟','我知','我唔知','我明白','我唔明白','得啦','唔該','冇問題','冇問題','等會見','保重','生日快樂','祝你有個好日','幾大','咩色','幾多','邊個','你想要','可以俾我','可以唔可以','我想','我叫','見到你真好','你住邊','我住','發生咗咩','你冇事吧','冇咩','冇咩','我喺度','做得好','俾我睇下',
    '今日','明日','昨日','早晨','下午','黃昏','夜晚','而家','之後','快啲','成日','從未','有時','已經','再','呢度','嗰度','上','落','入面','出面','上面','下面','啲','冇','同埋','但是','或者','因為','如果','幾時','邊度','咩','邊個','點樣','點解','呢個','嗰個','好','太','都','淨係','淨係','之前','之後','期間','同','冇','為','由','去','喺','之間','底','頂','後面','前面','左邊','右邊','入面','出面','附近','遠','一齊','單獨','多啲','少啲','夠','差唔多','真係','可能','喂','拜拜','得','一次','兩次','零','一','兩','三','四','五','六','七','八','九','十','二十','一百','一千','第一','第二','第三','星期一','星期二','星期三','星期四','星期五','星期六','星期日'
  ],
  ja: [
    '家','車','犬','猫','水','食べ物','学校','本','電話','ドア','窓','テーブル','椅子','ベッド','太陽','月','木','花','魚','鳥','母','父','子供','赤ちゃん','男の子','女の子','男','女','医者','先生','友達','家族','兄','姉','頭','手','足','目','耳','口','鼻','心','歯','髪','顔','体','腕','脚','背中','お腹','牛乳','パン','米','肉','卵','チーズ','バター','砂糖','塩','リンゴ','バナナ','オレンジ','ケーキ','スープ','茶','コーヒー','ボール','おもちゃ','ゲーム','人形','絵','歌','物語','手紙','言葉','名前','数字','色','赤','青','緑','黄色','白','黒','お金','店','通り','バス','電車','飛行機','船','自転車','靴','シャツ','パンツ','帽子','コート','ドレス','靴下','バッグ',
    'いる','もつ','する','いく','くる','みる','しる','ほしい','おもう','いう','つげる','あたえる','とる','つくる','える','おく','みつける','たすける','ためる','きく','たべる','のむ','ねる','さめる','あるく','はしる','すわる','たつ','あそぶ','よむ','かく','えをかく','うたう','おどる','つくる','あらう','そうじする','あける','しめる','まわす','とめる','はじめる','まつ','きく','みる','みる','はなす','よぶ','かう','はらう','はたらく','まなぶ','おしえる','みせる','もってくる','かつぐ','もつ','さわる','かんじる','きく','あいする','すきだ','いる','つかう','うごく','すむ','しぬ','おおきくなる','おちる','とぶ','およぐ','うん転する','のる','のぼる','とぶ','おす','ひく','なげる','とらえる','きる','こわす','なおす','つくる','なく','わらう','ほほえむ','キスする','だきしめる','おぼえている','わすれる','わかる','しんじる','のぞむ','ねがう','ゆめをみる','えらぶ','かえる','ついていく','あう','でる',
    '良い','悪い','大きい','小さい','長い','短い','背の高い','新しい','古い','若い','熱い','寒い','暖かい','速い','遅い','幸せな','悲しい','怒っている','疲れている','空腹な','喉が乾いている','病気な','強い','弱い','きれいな','汚い','濡れている','乾いている','硬い','柔らかい','重い','軽い','大きい','静かな','暗い','明るい','美しい','醜い','簡単な','難しい','正しい','間違っている','本当の','偽の','安全な','危険な','重要な','面白い','真剣な','良い','親切な','意地悪な','勇敢な','賢い','愚かな','怠惰な','忙しい','自由な','裕福な','貧しい','安い','高い','満たされた','空の','開いている','閉じている','準備ができている','壊れている','同じ','異なる','他の','次の','最後の','最初の','唯一の','多くの','少ない','もっと','少ない','全部','毎','いくつかの','いくつかの','自分の','本当の','確かな','申し訳ない','怖がっている','一人でいる','生きている','死んでいる','早い','遅い','遠い','近い','深い','高い','低い','甘い','酸っぱい',
    'おはようございます','こんにちは','こんばんは','おやすみなさい','お元気ですか','私は大丈夫です','ありがとう','どういたしまして','すみません','ごめんなさい','助けてください','私は助けてほしいです','私はお腹が空いています','私は喉が渇いています','私は疲れたです','私は具合が悪いです','痛いです','私は気分が良いです','私は気分が悪いです','あなたを愛しています','あなたが恋しいです','こちらへ来てください','行かないでください','座ってください','立ってください','起きてください','落ち着いてください','急いでください','ゆっくりしてください','気をつけてください','気をつけて','待ってください','見てください','聞いてください','教えてください','見せてください','助けてください','ください','私はほしいです','私は必要です','私は好きです','私はできます','私はできません','これは何ですか','どこにありますか','いくらですか','何時ですか','左に曲がってください','右に曲がってください','まっすぐ行ってください','ここで止まってください','ドアを開けてください','ドアを閉めてください','つけてください','消してください','手を洗ってください','歯を磨いてください','服を着てください','寝てください','食べましょう','行きましょう','よくできました','また試してみてください','もう一回','終わりました','まだです','今すぐ','あそこ','戻ってきてください','私は知っています','私は知りません','私は理解しました','私は理解できません','はい、どうぞ','いいえ、けっこうです','もちろんです','問題ありません','また後で','お元気で','お誕生日おめでとう','よい一日を','何歳ですか','何色ですか','何個ですか','どれですか','ほしいですか','くれますか','よろしいですか','私はほしいです','私の名前は','はじめまして','どこに住んでいますか','私は住んでいます','何が起きましたか','大丈夫ですか','心配しないでください','大丈夫です','私はいます','よくできました','見せて',
    '今日','明日','昨日','朝','午後','夕方','夜','今','後で','すぐに','いつも','決して','ときどき','もう','また','ここ','那里','上','下','中','外','上','下','はい','いいえ','そして','でも','または','なぜなら','もし','いつ','どこ','何','誰','どのように','なぜ','これ','それ','とても','あまりにも','また','だけ','ちょうど','前','後','間','一緒に','なしで','〜のために','から','〜に','〜で','間','下','上','後ろ','前','左','右','中','外','近く','遠く','一緒に','一人で','もっと','もっと少なく','十分','ほとんど','本当に','もしかしたら','こんにちは','さようなら','はい','一度','二度','零','一','二','三','四','五','六','七','八','九','十','二十','百','千','最初','二番目','三番目','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日'
  ],
  ko: [
    '집','차','개','고양이','물','음식','학교','책','전화','문','창문','테이블','의자','침대','태양','달','나무','꽃','물고기','새','어머니','아버지','아이','아기','소년','소녀','남자','여자','의사','교사','친구','가족','형제','자매','머리','손','발','눈','귀','입','코','심장','이빨','머리카락','얼굴','몸','팔','다리','등','배','우유','빵','밥','고기','계란','치즈','버터','설탕','소금','사과','바나나','오렌지','케이크','국','차','커피','공','완구','게임','인형','사진','노래','이야기','편지','단어','이름','숫자','색깔','빨간색','파란색','초록색','노란색','하얀색','검은색','돈','가게','거리','버스','기차','비행기','배','자전거','신발','셔츠','바지','모자','코트','드레스','양말','가방',
    '있다','가지다','하다','가다','오다','보다','알다','원하다','생각하다','말하다','말하다','주다','가지다','만들다','받다','놓다','찾다','돕다','시도하다','물어보다','먹다','마시다','자다','깨어나다','걷다','뛰다','앉다','서다','놀다','읽다','쓰다','그리다','노래하다','춤추다','요리하다','씻다','청소하다','열다','닫다','돌리다','그만두다','시작하다','기다리다','듣다','보다','보기','말하다','전화하다','사다','지불하다','일하다','배우다','가르치다','보여주다','가져오다','들고가다','잡다','터치하다','느끼다','듣다','사랑하다','좋아하다','필요하다','사용하다','이동하다','살다','죽다','자라다','떨어지다','날다','헤엄치다','운전하다','타다','오르다','뛰다','밀다','당기다','던지다','잡다','자르다','깨지다','수리하다','짓다','울다','웃다','미소짓다','키스하다','안아주다','기억하다','잊다','이해하다','믿다','희망하다','소원하다','꿈꾸다','선택하다','바꾸다','따르다','만나다','떠나다',
    '좋은','나쁜','큰','작은','긴','짧은','키 큰','새로운','오래된','젊은','뜨거운','차가운','뜻뜻한','빠른','느린','행복한','슬픈','화난','피곤한','배가 고픈','목이 마른','아픈','강한','약한','깨끗한','더러운','젖은','마른','단단한','부드러운','무거운','가벼운','시끄러운','조용한','어두운','밝은','아름다운','못생긴','쉬운','어려운','옳은','틀린','진실된','거짓된','안전한','위험한','중요한','재미있는','진지한','착한','친절한','무례한','용감한','똑똑한','바보 같은','게으른','바쁜','자유로운','부유한','가난한','저렴한','비싼','가득 찬','비어 있는','열린','닫힌','준비된','고장 난','같은','다른','다른','다음의','마지막의','첫 번째의','유일한','많은','적은','더 많은','덜 많은','모든','각각의','일부','어떤','자신의','진짜','확실한','미안한','무서운','홀로인','살아 있는','죽은','조기의','늦은','먼','가까운','깊은','높은','낮은','달콤한','신',
    '좋은 아침','좋은 오후','좋은 저녁','안녕히 주무세요','어떻게 지내세요','잘 지내요','감사합니다','천만에요','실례합니다','죄송합니다','도와주세요','도움이 필요해요','배가 고파요','목이 말라요','피곤해요','아파요','아파요','기분이 좋아요','기분이 나쁘요','사랑해요','그립어요','여기로 와요','가세요','앉아요','일어나요','일어나세요','조용히 해요','빨리 해요','천천히 해요','조심해요','주의해요','기다려요','나 좀 봐요','나 말 들어요','말해줘요','보여줘요','도와줘요','줘요','원해요','필요해요','좋아해요','할 수 있어요','할 수 없어요','이게 뭐야','어디 있어','얼마야','몇 시야','왼쪽으로 꺾어요','오른쪽으로 꺾어요','직진해요','여기서 멈춰요','문을 열어요','문을 닫아요','켜요','끄세요','손을 씻어요','이를 닦아요','옷을 입어요','자러 가요','밥 먹을 시간이야','가자','잘했어요','다시 해봐','한 번 더','다 했어요','아직 아니야','지금','저기','돌아와요','아는 거야','모르겠어요','알겠어요','모르겠어요','네, 좋아요','아니요, 괜찮아요','물론이죠','상관없어요','나중에 봐요','잘 지내세요','생일 축하해요','좋은 하루 보내세요','몇 살이야','무슨 색깔이야','몇 개야','어떤 거야','원해?','줄 수 있어?','해도 돼?','원해요','제 이름은','만나서 반가워요','어디 살아요','저는 ~에 살아요','무슨 일이야','괜찮아?','걱정하지 마세요','괜찮아요','여기 있어요','잘했어요','보여줘',
    '오늘','내일','어제','아침','오후','저녁','밤','지금','나중에','곧','항상','절대','때로는','이미','다시','여기','거기','위로','아래로','안으로','밖으로','위에','아래에','네','아니요','그리고','하지만','또는','왜냐하면','만약','언제','어디','무엇','누가','어떻게','왜','이것','그것','매우','너무','또한','오직','그저','전에','후에','동안','와','없이','위해','에서','로','에','사이에','아래에','위에','뒤에','앞에','왼쪽','오른쪽','안에','밖으로','가까이','멀리','함께','혼자','더','덜','충분히','거의','정말','아마','안녕','잘가','좋아','한 번','두 번','영','하나','둘','셋','넷','다섯','여섯','일곱','여덟','아홉','열','스물','백','천','첫째','둘째','셋째','월요일','화요일','수요일','목요일','금요일','토요일','일요일'
  ],
  ar: [
    'بيت','سيارة','كلب','قطة','ماء','طعام','مدرسة','كتاب','هاتف','باب','نافذة','طاولة','كرسي','سرير','شمس','قمر','شجرة','زهور','سمكة','طير','أم','أب','طفل','طفل','صبي','فتاة','رجل','امرأة','طبيب','معلم','صديق','عائلة','أخ','أخت','رأس','يد','قدم','عين','أذن','فم','أنف','قلب','سنان','شعر','وجه','جسم','ذراع','ساق','ظهر','بطن','حليب','خبز','أرز','لحم','بيضة','جبن','زبدة','سكر','ملح','تفاحة','موز','برتقال','كعكة','حساء','شاي','قهوة','كرة','لعبة','لعبة','دمية','صورة','أغنية','قصة','رسالة','كلمة','اسم','رقم','لون','أحمر','أزرق','أخضر','أصفر','أبيض','أسود','مال','متجر','شارع','حافلة','قطار','طائرة','سفينة','دراجة','حذاء','قميص','بنطلون','قبعة','معطف','فستان','جورب','حقيبة',
    'كَوْن','لَدَيَّ','فَعَل','ذَهَب','جَاءَ','رَأَى','عَلِم','أَرَادَ','فَكَّر','قَالَ','أَخْبَرَ','أَعْطَى','أَخَذَ','صَنَعَ','حَصَلَ','وَضَعَ','وَجَدَ','سَاعَدَ','جَرَّبَ','سَأَلَ','أَكَلَ','شَرِبَ','نَامَ','اسْتَيْقَظَ','مَشَى','رَكَضَ','جَلَسَ','وَقَفَ','لَعِبَ','قَرَأَ','كَتَبَ','رَسَمَ','غَنَّى','رَقَصَ','طَبَخَ','غَسَلَ','نَظَفَ','فَتَحَ','غَلَقَ','دَارَ','تَوَقَّفَ','بَدَأَ','انْتَظَرَ','اسْتَمَعَ','نَظَرَ','شَاهَدَ','تَكَلَّمَ','دَعَا','اشْتَرَى','دَفَعَ','عَمِلَ','تَعَلَّمَ','عَلَّمَ','أَرَاهُ','أَتَى','حَمَلَ','أَمْسَكَ','لَمَسَ','شَعَرَ','سَمِعَ','أَحَبَّ','أَعْجَبَ','حَاجَ','اسْتَخْدَمَ','حَرَكَ','عَاشَ','مَاتَ','نَمَى','سَقَطَ','طَارَ','سَبَحَ','قَادَ','رَكِبَ','تَصَعَّدَ','قَفَزَ','دَفَعَ','جَذَبَ','رَمَى','أَخَذَ','قَطَعَ','كَسَرَ','أَصْلَحَ','بَنَى','بَكَى','ضَحِكَ','تَبَسَّمَ','قَبَّلَ','عَانَقَ','تَذَكَّرَ','نَسِيَ','فَهِمَ','صَدَّقَ','رَجَا','تَمَنَّى','حَلَمَ','اخْتَارَ','تَغَيَّرَ','تَبِعَ','لَقِيَ','غَادَرَ',
    'good','bad','big','small','long','short','tall','new','old','young','hot','cold','warm','fast','slow','happy','sad','angry','tired','hungry','thirsty','sick','strong','weak','clean','dirty','wet','dry','hard','soft','heavy','light','loud','quiet','dark','bright','beautiful','ugly','easy','difficult','right','wrong','true','false','safe','dangerous','important','funny','serious','nice','kind','mean','brave','smart','stupid','lazy','busy','free','rich','poor','cheap','expensive','full','empty','open','closed','ready','broken','same','different','other','next','last','first','only','many','few','more','less','all','every','some','any','own','real','sure','sorry','afraid','alone','alive','dead','early','late','far','near','deep','high','low','sweet','sour',
    'good morning','good afternoon','good evening','good night','how are you','I am fine','thank you','you are welcome','excuse me','I am sorry','please help','I need help','I am hungry','I am thirsty','I am tired','I am sick','it hurts','I feel good','I feel bad','I love you','I miss you','come here','go away','sit down','stand up','wake up','calm down','hurry up','slow down','be careful','watch out','wait for me','look at me','listen to me','tell me','show me','help me','give me','I want','I need','I like','I can','I cannot','what is this','where is','how much','what time','turn left','turn right','go straight','stop here','open the door','close the door','turn on','turn off','wash hands','brush teeth','get dressed','go to bed','time to eat','let us go','well done','try again','one more','all done','not yet','right now','over there','come back','I know','I do not know','I understand','I do not understand','yes please','no thank you','of course','no problem','see you later','take care','happy birthday','have a nice day','how old','what color','how many','which one','do you want','can I have','may I','I would like','my name is','nice to meet you','where do you live','I live in','what happened','are you okay','do not worry','it is okay','I am here','good job','let me see',
    'اليوم','غدًا','أمس','الصباح','الظهيرة','المساء','الليل','الآن','لاحقًا','قريبًا','دائمًا','أبدًا','أحيانًا','بالفعل','مرة أخرى','هنا','هناك','أعلى','أسفل','في','خارج','على','من','نعم','لا','و','لكن','أو','لأن','إذا','متى','أين','ماذا','من','كيف','لماذا','هذا','ذلك','جدا','كثيرًا','أيضًا','فقط','بالفعل','قبل','بعد','خلال','مع','بدون','ل','من','إلى','في','بين','تحت','فوق','خلف','أمام','يسار','يمين','داخل','خارج','قريب','بعيد','معًا','وحيد','أكثر','أقل','كفاية','كاد','بالفعل','ربما','مرحبا','وداعًا','حسنًا','مرة واحدة','مرتين','صفر','واحد','اثنان','ثلاثة','أربعة','خمسة','ستة','سبعة','ثمانية','تسعة','عشرة','عشرون','مائة','ألف','أول','ثاني','ثالث','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت','الأحد'
  ],
};

export const OFFLINE_DICT_1 = _OFFLINE_DICT_1;

// Runtime validation: all language arrays must have the same length
const _dictValues = Object.values(OFFLINE_DICT_1);
const _expectedLength = _dictValues[0]?.length;
if (_expectedLength && _dictValues.some(arr => arr.length !== _expectedLength)) {
  console.error('[offlineDictionary] Language array length mismatch — translations may be misaligned');
}
