/**
 * Offline Translation Dictionary (Part 1)
 *
 * 500 index-aligned entries across 6 languages: en, es, fr, de, ru, ro.
 * Entries 0-99: Common nouns | 100-199: Common verbs | 200-299: Common adjectives
 * Entries 300-399: Common phrases | 400-499: Time, numbers, connectors
 */

// eslint-disable-next-line prefer-const
let _OFFLINE_DICT_1: Record<string, string[]> = {
  en: [
    'house','car','dog','cat','water','food','school','book','phone','door','window','table','chair','bed','sun','moon','tree','flower','fish','bird','mother','father','child','baby','boy','girl','man','woman','doctor','teacher','friend','family','brother','sister','head','hand','foot','eye','ear','mouth','nose','heart','tooth','hair','face','body','arm','leg','back','stomach','milk','bread','rice','meat','egg','cheese','butter','sugar','salt','apple','banana','orange','cake','soup','tea','coffee','ball','toy','game','doll','picture','song','story','letter','word','name','number','color','red','blue','green','yellow','white','black','money','store','street','bus','train','airplane','boat','bicycle','shoe','shirt','pants','hat','coat','dress','sock','bag',
    'be','have','do','go','come','see','know','want','think','say','tell','give','take','make','get','put','find','help','try','ask','eat','drink','sleep','wake','walk','run','sit','stand','play','read','write','draw','sing','dance','cook','wash','clean','open','close','turn','stop','start','wait','listen','look','watch','speak','call','buy','pay','work','learn','teach','show','bring','carry','hold','touch','feel','hear','love','like','need','use','move','live','die','grow','fall','fly','swim','drive','ride','climb','jump','push','pull','throw','catch','cut','break','fix','build','cry','laugh','smile','kiss','hug','remember','forget','understand','believe','hope','wish','dream','choose','change','follow','meet','leave',
    'good','bad','big','small','long','short','tall','new','old','young','hot','cold','warm','fast','slow','happy','sad','angry','tired','hungry','thirsty','sick','strong','weak','clean','dirty','wet','dry','hard','soft','heavy','light','loud','quiet','dark','bright','beautiful','ugly','easy','difficult','right','wrong','true','false','safe','dangerous','important','funny','serious','nice','kind','mean','brave','smart','stupid','lazy','busy','free','rich','poor','cheap','expensive','full','empty','open','closed','ready','broken','same','different','other','next','last','first','only','many','few','more','less','all','every','some','any','own','real','sure','sorry','afraid','alone','alive','dead','early','late','far','near','deep','high','low','sweet','sour',
    'good morning','good afternoon','good evening','good night','how are you','I am fine','thank you','you are welcome','excuse me','I am sorry','please help','I need help','I am hungry','I am thirsty','I am tired','I am sick','it hurts','I feel good','I feel bad','I love you','I miss you','come here','go away','sit down','stand up','wake up','calm down','hurry up','slow down','be careful','watch out','wait for me','look at me','listen to me','tell me','show me','help me','give me','I want','I need','I like','I can','I cannot','what is this','where is','how much','what time','turn left','turn right','go straight','stop here','open the door','close the door','turn on','turn off','wash hands','brush teeth','get dressed','go to bed','time to eat','let us go','well done','try again','one more','all done','not yet','right now','over there','come back','I know','I do not know','I understand','I do not understand','yes please','no thank you','of course','no problem','see you later','take care','happy birthday','have a nice day','how old','what color','how many','which one','do you want','can I have','may I','I would like','my name is','nice to meet you','where do you live','I live in','what happened','are you okay','do not worry','it is okay','I am here','good job','let me see',
    'today','tomorrow','yesterday','morning','afternoon','evening','night','now','later','soon','always','never','sometimes','already','again','here','there','up','down','in','out','on','off','yes','no','and','but','or','because','if','when','where','what','who','how','why','this','that','very','too','also','only','just','before','after','during','with','without','for','from','to','at','between','under','over','behind','front','left','right','inside','outside','near','far','together','alone','more','less','enough','almost','really','maybe','hello','goodbye','okay','once','twice','zero','one','two','three','four','five','six','seven','eight','nine','ten','twenty','hundred','thousand','first','second','third','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'
  ],
  es: [
    'casa','coche','perro','gato','agua','comida','escuela','libro','teléfono','puerta','ventana','mesa','silla','cama','sol','luna','árbol','flor','pez','pájaro','madre','padre','niño','bebé','chico','chica','hombre','mujer','doctor','maestro','amigo','familia','hermano','hermana','cabeza','mano','pie','ojo','oreja','boca','nariz','corazón','diente','pelo','cara','cuerpo','brazo','pierna','espalda','estómago','leche','pan','arroz','carne','huevo','queso','mantequilla','azúcar','sal','manzana','plátano','naranja','pastel','sopa','té','café','pelota','juguete','juego','muñeca','imagen','canción','historia','carta','palabra','nombre','número','color','rojo','azul','verde','amarillo','blanco','negro','dinero','tienda','calle','autobús','tren','avión','barco','bicicleta','zapato','camisa','pantalón','sombrero','abrigo','vestido','calcetín','bolsa',
    'ser','tener','hacer','ir','venir','ver','saber','querer','pensar','decir','contar','dar','tomar','fabricar','obtener','poner','encontrar','ayudar','intentar','preguntar','comer','beber','dormir','despertar','caminar','correr','sentar','estar de pie','jugar','leer','escribir','dibujar','cantar','bailar','cocinar','lavar','limpiar','abrir','cerrar','girar','parar','empezar','esperar','escuchar','mirar','observar','hablar','llamar','comprar','pagar','trabajar','aprender','enseñar','mostrar','traer','llevar','sostener','tocar','sentir','oír','amar','gustar','necesitar','usar','mover','vivir','morir','crecer','caer','volar','nadar','conducir','montar','escalar','saltar','empujar','tirar','lanzar','atrapar','cortar','romper','arreglar','construir','llorar','reír','sonreír','besar','abrazar','recordar','olvidar','entender','creer','esperar','desear','soñar','elegir','cambiar','seguir','conocer','salir',
    'bueno','malo','grande','pequeño','largo','corto','alto','nuevo','viejo','joven','caliente','frío','cálido','rápido','lento','feliz','triste','enojado','cansado','hambriento','sediento','enfermo','fuerte','débil','limpio','sucio','mojado','seco','duro','suave','pesado','ligero','ruidoso','silencioso','oscuro','brillante','hermoso','feo','fácil','difícil','correcto','incorrecto','verdadero','falso','seguro','peligroso','importante','gracioso','serio','agradable','amable','cruel','valiente','inteligente','estúpido','perezoso','ocupado','libre','rico','pobre','barato','caro','lleno','vacío','abierto','cerrado','listo','roto','mismo','diferente','otro','siguiente','último','primero','solo','muchos','pocos','más','menos','todo','cada','algunos','cualquier','propio','real','seguro','lo siento','asustado','solo','vivo','muerto','temprano','tarde','lejos','cerca','profundo','alto','bajo','dulce','agrio',
    'buenos días','buenas tardes','buenas noches','buenas noches','cómo estás','estoy bien','gracias','de nada','disculpe','lo siento','por favor ayuda','necesito ayuda','tengo hambre','tengo sed','estoy cansado','estoy enfermo','me duele','me siento bien','me siento mal','te amo','te extraño','ven aquí','vete','siéntate','levántate','despierta','cálmate','apúrate','ve despacio','ten cuidado','cuidado','espérame','mírame','escúchame','dime','muéstrame','ayúdame','dame','quiero','necesito','me gusta','puedo','no puedo','qué es esto','dónde está','cuánto cuesta','qué hora es','gira a la izquierda','gira a la derecha','sigue derecho','para aquí','abre la puerta','cierra la puerta','enciende','apaga','lávate las manos','cepíllate los dientes','vístete','ve a la cama','hora de comer','vamos','bien hecho','inténtalo de nuevo','uno más','todo listo','todavía no','ahora mismo','por allá','regresa','lo sé','no lo sé','entiendo','no entiendo','sí por favor','no gracias','por supuesto','no hay problema','nos vemos luego','cuídate','feliz cumpleaños','que tengas un buen día','cuántos años','de qué color','cuántos','cuál','quieres','puedo tener','puedo','me gustaría','mi nombre es','mucho gusto','dónde vives','vivo en','qué pasó','estás bien','no te preocupes','está bien','estoy aquí','buen trabajo','déjame ver',
    'hoy','mañana','ayer','mañana','tarde','noche','noche','ahora','luego','pronto','siempre','nunca','a veces','ya','otra vez','aquí','allí','arriba','abajo','en','fuera','sobre','apagado','sí','no','y','pero','o','porque','si','cuando','dónde','qué','quién','cómo','por qué','esto','eso','muy','también','también','solo','justo','antes','después','durante','con','sin','para','de','a','en','entre','debajo','sobre','detrás','frente','izquierda','derecha','dentro','fuera','cerca','lejos','juntos','solo','más','menos','suficiente','casi','realmente','quizás','hola','adiós','está bien','una vez','dos veces','cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','veinte','cien','mil','primero','segundo','tercero','lunes','martes','miércoles','jueves','viernes','sábado','domingo'
  ],
  fr: [
    'maison','voiture','chien','chat','eau','nourriture','école','livre','téléphone','porte','fenêtre','table','chaise','lit','soleil','lune','arbre','fleur','poisson','oiseau','mère','père','enfant','bébé','garçon','fille','homme','femme','docteur','professeur','ami','famille','frère','sœur','tête','main','pied','œil','oreille','bouche','nez','cœur','dent','cheveux','visage','corps','bras','jambe','dos','estomac','lait','pain','riz','viande','œuf','fromage','beurre','sucre','sel','pomme','banane','orange','gâteau','soupe','thé','café','balle','jouet','jeu','poupée','image','chanson','histoire','lettre','mot','nom','numéro','couleur','rouge','bleu','vert','jaune','blanc','noir','argent','magasin','rue','bus','train','avion','bateau','vélo','chaussure','chemise','pantalon','chapeau','manteau','robe','chaussette','sac',
    'être','avoir','faire','aller','venir','voir','savoir','vouloir','penser','dire','raconter','donner','prendre','fabriquer','obtenir','mettre','trouver','aider','essayer','demander','manger','boire','dormir','réveiller','marcher','courir','asseoir','se lever','jouer','lire','écrire','dessiner','chanter','danser','cuisiner','laver','nettoyer','ouvrir','fermer','tourner','arrêter','commencer','attendre','écouter','regarder','observer','parler','appeler','acheter','payer','travailler','apprendre','enseigner','montrer','apporter','porter','tenir','toucher','sentir','entendre','aimer','aimer bien','avoir besoin','utiliser','bouger','vivre','mourir','grandir','tomber','voler','nager','conduire','monter','grimper','sauter','pousser','tirer','lancer','attraper','couper','casser','réparer','construire','pleurer','rire','sourire','embrasser','serrer','se souvenir','oublier','comprendre','croire','espérer','souhaiter','rêver','choisir','changer','suivre','rencontrer','partir',
    'bon','mauvais','grand','petit','long','court','grand','nouveau','vieux','jeune','chaud','froid','tiède','rapide','lent','heureux','triste','en colère','fatigué','affamé','assoiffé','malade','fort','faible','propre','sale','mouillé','sec','dur','doux','lourd','léger','bruyant','silencieux','sombre','lumineux','beau','laid','facile','difficile','juste','faux','vrai','faux','sûr','dangereux','important','drôle','sérieux','agréable','gentil','méchant','courageux','intelligent','stupide','paresseux','occupé','libre','riche','pauvre','bon marché','cher','plein','vide','ouvert','fermé','prêt','cassé','même','différent','autre','prochain','dernier','premier','seul','beaucoup','peu','plus','moins','tout','chaque','quelques','aucun','propre','réel','sûr','désolé','effrayé','seul','vivant','mort','tôt','tard','loin','proche','profond','haut','bas','sucré','aigre',
    'bonjour','bon après-midi','bonsoir','bonne nuit','comment allez-vous','je vais bien','merci','de rien','excusez-moi','je suis désolé','aidez-moi s\'il vous plaît','j\'ai besoin d\'aide','j\'ai faim','j\'ai soif','je suis fatigué','je suis malade','ça fait mal','je me sens bien','je me sens mal','je t\'aime','tu me manques','viens ici','va-t\'en','assieds-toi','lève-toi','réveille-toi','calme-toi','dépêche-toi','ralentis','fais attention','attention','attends-moi','regarde-moi','écoute-moi','dis-moi','montre-moi','aide-moi','donne-moi','je veux','j\'ai besoin','j\'aime','je peux','je ne peux pas','qu\'est-ce que c\'est','où est','combien','quelle heure est-il','tourne à gauche','tourne à droite','va tout droit','arrête-toi ici','ouvre la porte','ferme la porte','allume','éteins','lave-toi les mains','brosse-toi les dents','habille-toi','va au lit','c\'est l\'heure de manger','allons-y','bien joué','essaie encore','encore un','tout est fini','pas encore','maintenant','là-bas','reviens','je sais','je ne sais pas','je comprends','je ne comprends pas','oui s\'il vous plaît','non merci','bien sûr','pas de problème','à plus tard','prends soin de toi','joyeux anniversaire','bonne journée','quel âge','quelle couleur','combien','lequel','veux-tu','puis-je avoir','puis-je','je voudrais','je m\'appelle','enchanté','où habites-tu','j\'habite à','que s\'est-il passé','ça va','ne t\'inquiète pas','c\'est bon','je suis ici','bon travail','laisse-moi voir',
    'aujourd\'hui','demain','hier','matin','après-midi','soir','nuit','maintenant','plus tard','bientôt','toujours','jamais','parfois','déjà','encore','ici','là','haut','bas','dans','dehors','sur','éteint','oui','non','et','mais','ou','parce que','si','quand','où','quoi','qui','comment','pourquoi','ceci','cela','très','trop','aussi','seulement','juste','avant','après','pendant','avec','sans','pour','de','à','à','entre','sous','sur','derrière','devant','gauche','droite','intérieur','extérieur','près','loin','ensemble','seul','plus','moins','assez','presque','vraiment','peut-être','bonjour','au revoir','d\'accord','une fois','deux fois','zéro','un','deux','trois','quatre','cinq','six','sept','huit','neuf','dix','vingt','cent','mille','premier','deuxième','troisième','lundi','mardi','mercredi','jeudi','vendredi','samedi','dimanche'
  ],
  de: [
    'Haus','Auto','Hund','Katze','Wasser','Essen','Schule','Buch','Telefon','Tür','Fenster','Tisch','Stuhl','Bett','Sonne','Mond','Baum','Blume','Fisch','Vogel','Mutter','Vater','Kind','Baby','Junge','Mädchen','Mann','Frau','Arzt','Lehrer','Freund','Familie','Bruder','Schwester','Kopf','Hand','Fuß','Auge','Ohr','Mund','Nase','Herz','Zahn','Haar','Gesicht','Körper','Arm','Bein','Rücken','Magen','Milch','Brot','Reis','Fleisch','Ei','Käse','Butter','Zucker','Salz','Apfel','Banane','Orange','Kuchen','Suppe','Tee','Kaffee','Ball','Spielzeug','Spiel','Puppe','Bild','Lied','Geschichte','Brief','Wort','Name','Nummer','Farbe','rot','blau','grün','gelb','weiß','schwarz','Geld','Geschäft','Straße','Bus','Zug','Flugzeug','Boot','Fahrrad','Schuh','Hemd','Hose','Hut','Mantel','Kleid','Socke','Tasche',
    'sein','haben','tun','gehen','kommen','sehen','wissen','wollen','denken','sagen','erzählen','geben','nehmen','machen','bekommen','legen','finden','helfen','versuchen','fragen','essen','trinken','schlafen','aufwachen','gehen','laufen','sitzen','stehen','spielen','lesen','schreiben','zeichnen','singen','tanzen','kochen','waschen','putzen','öffnen','schließen','drehen','stoppen','anfangen','warten','zuhören','schauen','beobachten','sprechen','anrufen','kaufen','bezahlen','arbeiten','lernen','lehren','zeigen','bringen','tragen','halten','berühren','fühlen','hören','lieben','mögen','brauchen','benutzen','bewegen','leben','sterben','wachsen','fallen','fliegen','schwimmen','fahren','reiten','klettern','springen','drücken','ziehen','werfen','fangen','schneiden','brechen','reparieren','bauen','weinen','lachen','lächeln','küssen','umarmen','erinnern','vergessen','verstehen','glauben','hoffen','wünschen','träumen','wählen','ändern','folgen','treffen','verlassen',
    'gut','schlecht','groß','klein','lang','kurz','groß','neu','alt','jung','heiß','kalt','warm','schnell','langsam','glücklich','traurig','wütend','müde','hungrig','durstig','krank','stark','schwach','sauber','schmutzig','nass','trocken','hart','weich','schwer','leicht','laut','leise','dunkel','hell','schön','hässlich','einfach','schwierig','richtig','falsch','wahr','falsch','sicher','gefährlich','wichtig','lustig','ernst','nett','freundlich','gemein','mutig','klug','dumm','faul','beschäftigt','frei','reich','arm','billig','teuer','voll','leer','offen','geschlossen','bereit','kaputt','gleich','verschieden','andere','nächste','letzte','erste','einzige','viele','wenige','mehr','weniger','alle','jede','einige','irgendein','eigen','echt','sicher','tut mir leid','ängstlich','allein','lebendig','tot','früh','spät','weit','nah','tief','hoch','niedrig','süß','sauer',
    'guten Morgen','guten Tag','guten Abend','gute Nacht','wie geht es Ihnen','mir geht es gut','danke','bitte','entschuldigung','es tut mir leid','bitte helfen Sie','ich brauche Hilfe','ich habe Hunger','ich habe Durst','ich bin müde','ich bin krank','es tut weh','ich fühle mich gut','ich fühle mich schlecht','ich liebe dich','ich vermisse dich','komm her','geh weg','setz dich','steh auf','wach auf','beruhige dich','beeil dich','langsamer','sei vorsichtig','pass auf','warte auf mich','schau mich an','hör mir zu','sag mir','zeig mir','hilf mir','gib mir','ich will','ich brauche','ich mag','ich kann','ich kann nicht','was ist das','wo ist','wie viel','wie spät ist es','biege links ab','biege rechts ab','geh geradeaus','halt hier','öffne die Tür','schließe die Tür','einschalten','ausschalten','Hände waschen','Zähne putzen','anziehen','ins Bett gehen','Zeit zum Essen','lass uns gehen','gut gemacht','versuch es nochmal','noch eins','alles fertig','noch nicht','jetzt sofort','da drüben','komm zurück','ich weiß','ich weiß nicht','ich verstehe','ich verstehe nicht','ja bitte','nein danke','natürlich','kein Problem','bis später','pass auf dich auf','alles Gute zum Geburtstag','schönen Tag noch','wie alt','welche Farbe','wie viele','welches','möchtest du','kann ich haben','darf ich','ich möchte','mein Name ist','freut mich','wo wohnst du','ich wohne in','was ist passiert','geht es dir gut','mach dir keine Sorgen','es ist in Ordnung','ich bin hier','gute Arbeit','lass mich sehen',
    'heute','morgen','gestern','Morgen','Nachmittag','Abend','Nacht','jetzt','später','bald','immer','nie','manchmal','schon','wieder','hier','dort','oben','unten','in','aus','an','aus','ja','nein','und','aber','oder','weil','wenn','wann','wo','was','wer','wie','warum','dies','das','sehr','zu','auch','nur','gerade','vorher','nachher','während','mit','ohne','für','von','zu','bei','zwischen','unter','über','hinter','vorne','links','rechts','innen','außen','nah','weit','zusammen','allein','mehr','weniger','genug','fast','wirklich','vielleicht','hallo','auf Wiedersehen','okay','einmal','zweimal','null','eins','zwei','drei','vier','fünf','sechs','sieben','acht','neun','zehn','zwanzig','hundert','tausend','erste','zweite','dritte','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'
  ],
  ru: [
    'дом','машина','собака','кошка','вода','еда','школа','книга','телефон','дверь','окно','стол','стул','кровать','солнце','луна','дерево','цветок','рыба','птица','мать','отец','ребёнок','малыш','мальчик','девочка','мужчина','женщина','врач','учитель','друг','семья','брат','сестра','голова','рука','нога','глаз','ухо','рот','нос','сердце','зуб','волосы','лицо','тело','рука','нога','спина','живот','молоко','хлеб','рис','мясо','яйцо','сыр','масло','сахар','соль','яблоко','банан','апельсин','торт','суп','чай','кофе','мяч','игрушка','игра','кукла','картинка','песня','история','письмо','слово','имя','номер','цвет','красный','синий','зелёный','жёлтый','белый','чёрный','деньги','магазин','улица','автобус','поезд','самолёт','лодка','велосипед','ботинок','рубашка','штаны','шляпа','пальто','платье','носок','сумка',
    'быть','иметь','делать','идти','приходить','видеть','знать','хотеть','думать','говорить','рассказывать','давать','брать','создавать','получать','класть','находить','помогать','пытаться','спрашивать','есть','пить','спать','просыпаться','ходить','бегать','сидеть','стоять','играть','читать','писать','рисовать','петь','танцевать','готовить','мыть','убирать','открывать','закрывать','поворачивать','останавливать','начинать','ждать','слушать','смотреть','наблюдать','говорить','звонить','покупать','платить','работать','учиться','учить','показывать','приносить','нести','держать','трогать','чувствовать','слышать','любить','нравиться','нуждаться','использовать','двигаться','жить','умирать','расти','падать','летать','плавать','водить','ездить','лазить','прыгать','толкать','тянуть','бросать','ловить','резать','ломать','чинить','строить','плакать','смеяться','улыбаться','целовать','обнимать','помнить','забывать','понимать','верить','надеяться','желать','мечтать','выбирать','менять','следовать','встречать','уходить',
    'хороший','плохой','большой','маленький','длинный','короткий','высокий','новый','старый','молодой','горячий','холодный','тёплый','быстрый','медленный','счастливый','грустный','злой','усталый','голодный','жаждущий','больной','сильный','слабый','чистый','грязный','мокрый','сухой','твёрдый','мягкий','тяжёлый','лёгкий','громкий','тихий','тёмный','яркий','красивый','уродливый','лёгкий','трудный','правильный','неправильный','правдивый','ложный','безопасный','опасный','важный','смешной','серьёзный','приятный','добрый','злой','смелый','умный','глупый','ленивый','занятый','свободный','богатый','бедный','дешёвый','дорогой','полный','пустой','открытый','закрытый','готовый','сломанный','одинаковый','разный','другой','следующий','последний','первый','единственный','много','мало','больше','меньше','весь','каждый','некоторый','любой','собственный','настоящий','уверенный','извините','испуганный','одинокий','живой','мёртвый','ранний','поздний','далёкий','близкий','глубокий','высокий','низкий','сладкий','кислый',
    'доброе утро','добрый день','добрый вечер','спокойной ночи','как дела','я в порядке','спасибо','пожалуйста','извините','мне жаль','помогите пожалуйста','мне нужна помощь','я голоден','я хочу пить','я устал','я болен','мне больно','я чувствую себя хорошо','я чувствую себя плохо','я люблю тебя','я скучаю по тебе','иди сюда','уходи','садись','встань','проснись','успокойся','поторопись','помедленнее','будь осторожен','осторожно','подожди меня','посмотри на меня','послушай меня','скажи мне','покажи мне','помоги мне','дай мне','я хочу','мне нужно','мне нравится','я могу','я не могу','что это','где находится','сколько стоит','который час','поверни налево','поверни направо','иди прямо','остановись здесь','открой дверь','закрой дверь','включи','выключи','вымой руки','почисти зубы','одевайся','ложись спать','пора есть','пойдём','молодец','попробуй ещё раз','ещё один','всё готово','ещё нет','прямо сейчас','вон там','вернись','я знаю','я не знаю','я понимаю','я не понимаю','да пожалуйста','нет спасибо','конечно','нет проблем','увидимся позже','береги себя','с днём рождения','хорошего дня','сколько лет','какой цвет','сколько','который','ты хочешь','можно мне','можно','я бы хотел','меня зовут','приятно познакомиться','где ты живёшь','я живу в','что случилось','ты в порядке','не волнуйся','всё хорошо','я здесь','хорошая работа','дай мне посмотреть',
    'сегодня','завтра','вчера','утро','день','вечер','ночь','сейчас','позже','скоро','всегда','никогда','иногда','уже','снова','здесь','там','вверх','вниз','в','из','на','выключено','да','нет','и','но','или','потому что','если','когда','где','что','кто','как','почему','это','то','очень','тоже','также','только','просто','до','после','во время','с','без','для','от','к','в','между','под','над','за','перед','лево','право','внутри','снаружи','близко','далеко','вместе','одному','больше','меньше','достаточно','почти','действительно','может быть','привет','до свидания','хорошо','один раз','дважды','ноль','один','два','три','четыре','пять','шесть','семь','восемь','девять','десять','двадцать','сто','тысяча','первый','второй','третий','понедельник','вторник','среда','четверг','пятница','суббота','воскресенье'
  ],
  ro: [
    'casă','mașină','câine','pisică','apă','mâncare','școală','carte','telefon','ușă','fereastră','masă','scaun','pat','soare','lună','copac','floare','pește','pasăre','mamă','tată','copil','bebeluș','băiat','fată','bărbat','femeie','doctor','profesor','prieten','familie','frate','soră','cap','mână','picior','ochi','ureche','gură','nas','inimă','dinte','păr','față','corp','braț','picior','spate','stomac','lapte','pâine','orez','carne','ou','brânză','unt','zahăr','sare','măr','banană','portocală','tort','supă','ceai','cafea','minge','jucărie','joc','păpușă','imagine','cântec','poveste','scrisoare','cuvânt','nume','număr','culoare','roșu','albastru','verde','galben','alb','negru','bani','magazin','stradă','autobuz','tren','avion','barcă','bicicletă','pantof','cămașă','pantaloni','pălărie','palton','rochie','șosetă','geantă',
    'a fi','a avea','a face','a merge','a veni','a vedea','a ști','a vrea','a gândi','a spune','a povesti','a da','a lua','a fabrica','a obține','a pune','a găsi','a ajuta','a încerca','a întreba','a mânca','a bea','a dormi','a trezi','a merge','a alerga','a ședea','a sta în picioare','a juca','a citi','a scrie','a desena','a cânta','a dansa','a găti','a spăla','a curăța','a deschide','a închide','a întoarce','a opri','a începe','a aștepta','a asculta','a privi','a urmări','a vorbi','a suna','a cumpăra','a plăti','a lucra','a învăța','a preda','a arăta','a aduce','a duce','a ține','a atinge','a simți','a auzi','a iubi','a plăcea','a avea nevoie','a folosi','a mișca','a trăi','a muri','a crește','a cădea','a zbura','a înota','a conduce','a călări','a urca','a sări','a împinge','a trage','a arunca','a prinde','a tăia','a sparge','a repara','a construi','a plânge','a râde','a zâmbi','a săruta','a îmbrățișa','a aminti','a uita','a înțelege','a crede','a spera','a dori','a visa','a alege','a schimba','a urma','a întâlni','a pleca',
    'bun','rău','mare','mic','lung','scurt','înalt','nou','vechi','tânăr','fierbinte','rece','cald','rapid','lent','fericit','trist','supărat','obosit','flămând','însetat','bolnav','puternic','slab','curat','murdar','ud','uscat','tare','moale','greu','ușor','tare','liniștit','întunecat','luminos','frumos','urât','ușor','dificil','corect','greșit','adevărat','fals','sigur','periculos','important','amuzant','serios','drăguț','amabil','rău','curajos','deștept','prost','leneș','ocupat','liber','bogat','sărac','ieftin','scump','plin','gol','deschis','închis','gata','stricat','același','diferit','alt','următor','ultimul','primul','singurul','mulți','puțini','mai mult','mai puțin','tot','fiecare','unii','orice','propriu','real','sigur','îmi pare rău','speriat','singur','viu','mort','devreme','târziu','departe','aproape','adânc','înalt','jos','dulce','acru',
    'bună dimineața','bună ziua','bună seara','noapte bună','ce mai faci','sunt bine','mulțumesc','cu plăcere','scuzați-mă','îmi pare rău','vă rog ajutați-mă','am nevoie de ajutor','mi-e foame','mi-e sete','sunt obosit','sunt bolnav','mă doare','mă simt bine','mă simt rău','te iubesc','mi-e dor de tine','vino aici','pleacă','așează-te','ridică-te','trezește-te','calmează-te','grăbește-te','încetinește','fii atent','atenție','așteaptă-mă','uită-te la mine','ascultă-mă','spune-mi','arată-mi','ajută-mă','dă-mi','vreau','am nevoie','îmi place','pot','nu pot','ce este asta','unde este','cât costă','cât este ceasul','virează la stânga','virează la dreapta','mergi drept','oprește-te aici','deschide ușa','închide ușa','pornește','oprește','spală-te pe mâini','spală-te pe dinți','îmbracă-te','du-te la culcare','e timpul să mâncăm','hai să mergem','bravo','încearcă din nou','încă unul','totul gata','încă nu','chiar acum','acolo','întoarce-te','știu','nu știu','înțeleg','nu înțeleg','da vă rog','nu mulțumesc','bineînțeles','nicio problemă','ne vedem mai târziu','ai grijă de tine','la mulți ani','o zi frumoasă','câți ani','ce culoare','câți','care','vrei','pot să am','pot','aș vrea','mă numesc','încântat de cunoștință','unde locuiești','locuiesc în','ce s-a întâmplat','ești bine','nu-ți face griji','e în regulă','sunt aici','treabă bună','lasă-mă să văd',
    'astăzi','mâine','ieri','dimineață','după-amiază','seară','noapte','acum','mai târziu','curând','întotdeauna','niciodată','uneori','deja','din nou','aici','acolo','sus','jos','în','afară','pe','oprit','da','nu','și','dar','sau','pentru că','dacă','când','unde','ce','cine','cum','de ce','acesta','acela','foarte','prea','de asemenea','doar','chiar','înainte','după','în timpul','cu','fără','pentru','de la','la','la','între','sub','peste','în spate','în față','stânga','dreapta','înăuntru','afară','aproape','departe','împreună','singur','mai mult','mai puțin','destul','aproape','chiar','poate','salut','la revedere','bine','o dată','de două ori','zero','unu','doi','trei','patru','cinci','șase','șapte','opt','nouă','zece','douăzeci','o sută','o mie','primul','al doilea','al treilea','luni','marți','miercuri','joi','vineri','sâmbătă','duminică'
  ],
};

export const OFFLINE_DICT_1 = _OFFLINE_DICT_1;

// Runtime validation: all language arrays must have the same length
const _dictValues = Object.values(OFFLINE_DICT_1);
const _expectedLength = _dictValues[0]?.length;
if (_expectedLength && _dictValues.some(arr => arr.length !== _expectedLength)) {
  console.error('[offlineDictionary] Language array length mismatch — translations may be misaligned');
}
