import { Phrase } from '@/types';

const p = (id: string, categoryId: string, text: string, sortOrder: number): Phrase => ({
  id, categoryId, text, sortOrder, isCustom: false, usageCount: 0,
});

export const DEFAULT_PHRASES: Phrase[] = [
  // Core Words — Pronouns
  p('cw-i', 'core-pronouns', 'I', 0),
  p('cw-you', 'core-pronouns', 'You', 1),
  p('cw-he', 'core-pronouns', 'He', 2),
  p('cw-she', 'core-pronouns', 'She', 3),
  p('cw-it', 'core-pronouns', 'It', 4),
  p('cw-we', 'core-pronouns', 'We', 5),
  p('cw-they', 'core-pronouns', 'They', 6),
  p('cw-me', 'core-pronouns', 'Me', 7),
  p('cw-my', 'core-pronouns', 'My', 8),
  p('cw-your', 'core-pronouns', 'Your', 9),
  p('cw-his', 'core-pronouns', 'His', 10),
  p('cw-her', 'core-pronouns', 'Her', 11),
  p('cw-this', 'core-pronouns', 'This', 12),
  p('cw-that', 'core-pronouns', 'That', 13),

  // Core Words — Verbs
  p('cw-want', 'core-verbs', 'Want', 0),
  p('cw-like', 'core-verbs', 'Like', 1),
  p('cw-have', 'core-verbs', 'Have', 2),
  p('cw-do', 'core-verbs', 'Do', 3),
  p('cw-can', 'core-verbs', 'Can', 4),
  p('cw-need', 'core-verbs', 'Need', 5),
  p('cw-know', 'core-verbs', 'Know', 6),
  p('cw-see', 'core-verbs', 'See', 7),
  p('cw-think', 'core-verbs', 'Think', 8),
  p('cw-feel', 'core-verbs', 'Feel', 9),
  p('cw-say', 'core-verbs', 'Say', 10),
  p('cw-tell', 'core-verbs', 'Tell', 11),
  p('cw-try', 'core-verbs', 'Try', 12),
  p('cw-let', 'core-verbs', 'Let', 13),
  p('cw-help', 'core-verbs', 'Help', 14),
  p('cw-make', 'core-verbs', 'Make', 15),
  p('cw-come', 'core-verbs', 'Come', 16),
  p('cw-go-core', 'core-verbs', 'Go', 17),
  p('cw-get-core', 'core-verbs', 'Get', 18),
  p('cw-put-core', 'core-verbs', 'Put', 19),

  // Core Words — Descriptors
  p('cw-more', 'core-descriptors', 'More', 0),
  p('cw-not', 'core-descriptors', 'Not', 1),
  p('cw-no-core', 'core-descriptors', 'No', 2),
  p('cw-yes-core', 'core-descriptors', 'Yes', 3),
  p('cw-all', 'core-descriptors', 'All', 4),
  p('cw-some', 'core-descriptors', 'Some', 5),
  p('cw-other', 'core-descriptors', 'Other', 6),
  p('cw-very', 'core-descriptors', 'Very', 7),
  p('cw-here', 'core-descriptors', 'Here', 8),
  p('cw-there', 'core-descriptors', 'There', 9),
  p('cw-up', 'core-descriptors', 'Up', 10),
  p('cw-down', 'core-descriptors', 'Down', 11),
  p('cw-in', 'core-descriptors', 'In', 12),
  p('cw-out', 'core-descriptors', 'Out', 13),
  p('cw-on', 'core-descriptors', 'On', 14),
  p('cw-off', 'core-descriptors', 'Off', 15),
  p('cw-done', 'core-descriptors', 'Done', 16),
  p('cw-again', 'core-descriptors', 'Again', 17),
  p('cw-too', 'core-descriptors', 'Too', 18),
  p('cw-same-core', 'core-descriptors', 'Same', 19),

  // Core Words — Little Words
  p('cw-is', 'core-little-words', 'Is', 0),
  p('cw-the', 'core-little-words', 'The', 1),
  p('cw-a', 'core-little-words', 'A', 2),
  p('cw-and', 'core-little-words', 'And', 3),
  p('cw-but', 'core-little-words', 'But', 4),
  p('cw-or', 'core-little-words', 'Or', 5),
  p('cw-to', 'core-little-words', 'To', 6),
  p('cw-for', 'core-little-words', 'For', 7),
  p('cw-with', 'core-little-words', 'With', 8),
  p('cw-at', 'core-little-words', 'At', 9),
  p('cw-of', 'core-little-words', 'Of', 10),
  p('cw-about', 'core-little-words', 'About', 11),
  p('cw-because', 'core-little-words', 'Because', 12),
  p('cw-if', 'core-little-words', 'If', 13),
  p('cw-when-core', 'core-little-words', 'When', 14),
  p('cw-where-core', 'core-little-words', 'Where', 15),

  // Help / Needs
  p('help-all-done', 'help-needs', 'All done', 0),
  p('help-break', 'help-needs', 'Take a break', 1),
  p('help-need-help', 'help-needs', 'I need help', 2),
  p('help-hungry', 'help-needs', 'I am hungry', 3),
  p('help-thirsty', 'help-needs', 'I am thirsty', 4),
  p('help-bathroom', 'help-needs', 'Bathroom', 5),
  p('help-yes', 'help-needs', 'Yes', 6),
  p('help-no', 'help-needs', 'No', 7),
  p('help-stop', 'help-needs', 'Stop', 8),
  p('help-more', 'help-needs', 'More', 9),
  p('help-want', 'help-needs', 'I want', 10),
  p('help-dont-want', 'help-needs', "I don't want", 11),
  p('help-hurts', 'help-needs', 'It hurts', 12),
  p('help-tired', 'help-needs', 'I am tired', 13),

  // Quick Talk
  p('qt-hello', 'quick-talk', 'Hello', 0),
  p('qt-goodbye', 'quick-talk', 'Goodbye', 1),
  p('qt-thank-you', 'quick-talk', 'Thank you', 2),
  p('qt-please', 'quick-talk', 'Please', 3),
  p('qt-excuse-me', 'quick-talk', 'Excuse me', 4),
  p('qt-dont-understand', 'quick-talk', "I don't understand", 5),
  p('qt-wait', 'quick-talk', 'Wait', 6),
  p('qt-come-here', 'quick-talk', 'Come here', 7),
  p('qt-how-are-you', 'quick-talk', 'How are you?', 8),
  p('qt-im-good', 'quick-talk', "I'm good", 9),
  p('qt-sorry', 'quick-talk', 'Sorry', 10),
  p('qt-i-dont-know', 'quick-talk', "I don't know", 11),
  p('qt-my-name', 'quick-talk', 'My name is', 12),
  p('qt-nice-meet', 'quick-talk', 'Nice to meet you', 13),
  p('qt-see-later', 'quick-talk', 'See you later', 14),
  p('qt-youre-welcome', 'quick-talk', "You're welcome", 15),

  // Feelings
  p('fe-happy', 'feelings', 'Happy', 0),
  p('fe-sad', 'feelings', 'Sad', 1),
  p('fe-angry', 'feelings', 'Angry', 2),
  p('fe-scared', 'feelings', 'Scared', 3),
  p('fe-excited', 'feelings', 'Excited', 4),
  p('fe-frustrated', 'feelings', 'Frustrated', 5),
  p('fe-bored', 'feelings', 'Bored', 6),
  p('fe-surprised', 'feelings', 'Surprised', 7),
  p('fe-confused', 'feelings', 'Confused', 8),
  p('fe-proud', 'feelings', 'Proud', 9),
  p('fe-nervous', 'feelings', 'Nervous', 10),
  p('fe-silly', 'feelings', 'Silly', 11),
  p('fe-love', 'feelings', 'I love you', 12),
  p('fe-hurt', 'feelings', 'My feelings are hurt', 13),

  // Actions
  p('ac-go', 'actions', 'Go', 0),
  p('ac-stop', 'actions', 'Stop', 1),
  p('ac-eat', 'actions', 'Eat', 2),
  p('ac-drink', 'actions', 'Drink', 3),
  p('ac-play', 'actions', 'Play', 4),
  p('ac-read', 'actions', 'Read', 5),
  p('ac-watch', 'actions', 'Watch', 6),
  p('ac-listen', 'actions', 'Listen', 7),
  p('ac-open', 'actions', 'Open', 8),
  p('ac-close', 'actions', 'Close', 9),
  p('ac-give', 'actions', 'Give', 10),
  p('ac-take', 'actions', 'Take', 11),
  p('ac-look', 'actions', 'Look', 12),
  p('ac-sit', 'actions', 'Sit', 13),
  p('ac-stand', 'actions', 'Stand up', 14),
  p('ac-walk', 'actions', 'Walk', 15),
  p('ac-run', 'actions', 'Run', 16),
  p('ac-write', 'actions', 'Write', 17),
  p('ac-draw', 'actions', 'Draw', 18),
  p('ac-make', 'actions', 'Make', 19),
  p('ac-put', 'actions', 'Put', 20),
  p('ac-get', 'actions', 'Get', 21),
  p('ac-turn', 'actions', 'Turn', 22),
  p('ac-wash', 'actions', 'Wash', 23),

  // Describing Words
  p('dw-big', 'describing', 'Big', 0),
  p('dw-small', 'describing', 'Small', 1),
  p('dw-hot', 'describing', 'Hot', 2),
  p('dw-cold', 'describing', 'Cold', 3),
  p('dw-good', 'describing', 'Good', 4),
  p('dw-bad', 'describing', 'Bad', 5),
  p('dw-fast', 'describing', 'Fast', 6),
  p('dw-slow', 'describing', 'Slow', 7),
  p('dw-new', 'describing', 'New', 8),
  p('dw-old', 'describing', 'Old', 9),
  p('dw-same', 'describing', 'Same', 10),
  p('dw-different', 'describing', 'Different', 11),
  p('dw-funny', 'describing', 'Funny', 12),
  p('dw-pretty', 'describing', 'Pretty', 13),
  p('dw-yucky', 'describing', 'Yucky', 14),
  p('dw-favorite', 'describing', 'Favorite', 15),

  // Questions
  p('qu-what', 'questions', 'What?', 0),
  p('qu-where', 'questions', 'Where?', 1),
  p('qu-when', 'questions', 'When?', 2),
  p('qu-who', 'questions', 'Who?', 3),
  p('qu-why', 'questions', 'Why?', 4),
  p('qu-how', 'questions', 'How?', 5),
  p('qu-which', 'questions', 'Which one?', 6),
  p('qu-how-many', 'questions', 'How many?', 7),
  p('qu-can-i', 'questions', 'Can I?', 8),
  p('qu-is-it', 'questions', 'Is it?', 9),
  p('qu-whats-that', 'questions', "What's that?", 10),
  p('qu-where-going', 'questions', 'Where are we going?', 11),

  // People
  p('pp-mom', 'people-social', 'Mom', 0),
  p('pp-dad', 'people-social', 'Dad', 1),
  p('pp-teacher', 'people-social', 'Teacher', 2),
  p('pp-friend', 'people-social', 'Friend', 3),
  p('pp-family', 'people-social', 'Family', 4),
  p('pp-doctor', 'people-social', 'Doctor', 5),
  p('pp-brother', 'people-social', 'Brother', 6),
  p('pp-sister', 'people-social', 'Sister', 7),
  p('pp-grandma', 'people-social', 'Grandma', 8),
  p('pp-grandpa', 'people-social', 'Grandpa', 9),
  p('pp-baby', 'people-social', 'Baby', 10),
  p('pp-boy', 'people-social', 'Boy', 11),
  p('pp-girl', 'people-social', 'Girl', 12),
  p('pp-therapist', 'people-social', 'Therapist', 13),

  // Food & Drink
  p('fd-water', 'food-ordering', 'Water', 0),
  p('fd-juice', 'food-ordering', 'Juice', 1),
  p('fd-milk', 'food-ordering', 'Milk', 2),
  p('fd-pizza', 'food-ordering', 'Pizza', 3),
  p('fd-sandwich', 'food-ordering', 'Sandwich', 4),
  p('fd-chicken', 'food-ordering', 'Chicken', 5),
  p('fd-fries', 'food-ordering', 'Fries', 6),
  p('fd-fruit', 'food-ordering', 'Fruit', 7),
  p('fd-snack', 'food-ordering', 'Snack', 8),
  p('fd-more', 'food-ordering', 'More please', 9),
  p('fd-no-thanks', 'food-ordering', 'No thanks', 10),
  p('fd-cookie', 'food-ordering', 'Cookie', 11),
  p('fd-apple', 'food-ordering', 'Apple', 12),
  p('fd-banana', 'food-ordering', 'Banana', 13),
  p('fd-cereal', 'food-ordering', 'Cereal', 14),
  p('fd-cheese', 'food-ordering', 'Cheese', 15),
  p('fd-ice-cream', 'food-ordering', 'Ice cream', 16),
  p('fd-crackers', 'food-ordering', 'Crackers', 17),

  // Places
  p('pl-home', 'places-plans', 'Home', 0),
  p('pl-school', 'places-plans', 'School', 1),
  p('pl-park', 'places-plans', 'Park', 2),
  p('pl-store', 'places-plans', 'Store', 3),
  p('pl-restaurant', 'places-plans', 'Restaurant', 4),
  p('pl-library', 'places-plans', 'Library', 5),
  p('pl-pool', 'places-plans', 'Pool', 6),
  p('pl-car', 'places-plans', 'Car', 7),
  p('pl-outside', 'places-plans', 'Outside', 8),
  p('pl-inside', 'places-plans', 'Inside', 9),
  p('pl-bathroom', 'places-plans', 'Bathroom', 10),
  p('pl-bedroom', 'places-plans', 'Bedroom', 11),
  p('pl-kitchen', 'places-plans', 'Kitchen', 12),
  p('pl-playground', 'places-plans', 'Playground', 13),

  // School / Work
  p('sw-class', 'school-work', 'Class', 0),
  p('sw-homework', 'school-work', 'Homework', 1),
  p('sw-computer', 'school-work', 'Computer', 2),
  p('sw-book', 'school-work', 'Book', 3),
  p('sw-pencil', 'school-work', 'Pencil', 4),
  p('sw-question', 'school-work', 'I have a question', 5),
  p('sw-finished', 'school-work', "I'm finished", 6),
  p('sw-help', 'school-work', 'I need help with this', 7),
  p('sw-paper', 'school-work', 'Paper', 8),
  p('sw-table', 'school-work', 'Table', 9),
  p('sw-chair', 'school-work', 'Chair', 10),
  p('sw-art', 'school-work', 'Art', 11),
  p('sw-music', 'school-work', 'Music', 12),
  p('sw-recess', 'school-work', 'Recess', 13),

  // Health / Body
  p('hb-head', 'health-body', 'Head', 0),
  p('hb-tummy', 'health-body', 'Tummy', 1),
  p('hb-hand', 'health-body', 'Hand', 2),
  p('hb-foot', 'health-body', 'Foot', 3),
  p('hb-eye', 'health-body', 'Eye', 4),
  p('hb-ear', 'health-body', 'Ear', 5),
  p('hb-mouth', 'health-body', 'Mouth', 6),
  p('hb-nose', 'health-body', 'Nose', 7),
  p('hb-hurts', 'health-body', 'It hurts', 8),
  p('hb-sick', 'health-body', 'I feel sick', 9),
  p('hb-medicine', 'health-body', 'Medicine', 10),
  p('hb-teeth', 'health-body', 'Teeth', 11),
  p('hb-back', 'health-body', 'Back', 12),
  p('hb-arm', 'health-body', 'Arm', 13),

  // Time
  p('ti-now', 'time', 'Now', 0),
  p('ti-later', 'time', 'Later', 1),
  p('ti-today', 'time', 'Today', 2),
  p('ti-tomorrow', 'time', 'Tomorrow', 3),
  p('ti-yesterday', 'time', 'Yesterday', 4),
  p('ti-morning', 'time', 'Morning', 5),
  p('ti-afternoon', 'time', 'Afternoon', 6),
  p('ti-night', 'time', 'Night', 7),
  p('ti-before', 'time', 'Before', 8),
  p('ti-after', 'time', 'After', 9),
  p('ti-first', 'time', 'First', 10),
  p('ti-last', 'time', 'Last', 11),

  // Animals
  p('an-dog', 'animals', 'Dog', 0),
  p('an-cat', 'animals', 'Cat', 1),
  p('an-fish', 'animals', 'Fish', 2),
  p('an-bird', 'animals', 'Bird', 3),
  p('an-horse', 'animals', 'Horse', 4),
  p('an-cow', 'animals', 'Cow', 5),
  p('an-pig', 'animals', 'Pig', 6),
  p('an-rabbit', 'animals', 'Rabbit', 7),
  p('an-bear', 'animals', 'Bear', 8),
  p('an-elephant', 'animals', 'Elephant', 9),
  p('an-duck', 'animals', 'Duck', 10),
  p('an-butterfly', 'animals', 'Butterfly', 11),

  // Colors
  p('co-red', 'colors', 'Red', 0),
  p('co-blue', 'colors', 'Blue', 1),
  p('co-green', 'colors', 'Green', 2),
  p('co-yellow', 'colors', 'Yellow', 3),
  p('co-orange', 'colors', 'Orange', 4),
  p('co-purple', 'colors', 'Purple', 5),
  p('co-pink', 'colors', 'Pink', 6),
  p('co-black', 'colors', 'Black', 7),
  p('co-white', 'colors', 'White', 8),
  p('co-brown', 'colors', 'Brown', 9),

  // Clothes
  p('cl-shirt', 'clothes', 'Shirt', 0),
  p('cl-pants', 'clothes', 'Pants', 1),
  p('cl-shoes', 'clothes', 'Shoes', 2),
  p('cl-socks', 'clothes', 'Socks', 3),
  p('cl-jacket', 'clothes', 'Jacket', 4),
  p('cl-hat', 'clothes', 'Hat', 5),
  p('cl-dress', 'clothes', 'Dress', 6),
  p('cl-pajamas', 'clothes', 'Pajamas', 7),
  p('cl-underwear', 'clothes', 'Underwear', 8),
  p('cl-boots', 'clothes', 'Boots', 9),

  // Transportation
  p('tr-car', 'transport', 'Car', 0),
  p('tr-bus', 'transport', 'Bus', 1),
  p('tr-train', 'transport', 'Train', 2),
  p('tr-airplane', 'transport', 'Airplane', 3),
  p('tr-bike', 'transport', 'Bike', 4),
  p('tr-truck', 'transport', 'Truck', 5),
  p('tr-boat', 'transport', 'Boat', 6),
  p('tr-walk', 'transport', 'Walk', 7),
  p('tr-wheelchair', 'transport', 'Wheelchair', 8),
  p('tr-scooter', 'transport', 'Scooter', 9),

  // Weather
  p('we-sunny', 'weather', 'Sunny', 0),
  p('we-rainy', 'weather', 'Rainy', 1),
  p('we-cloudy', 'weather', 'Cloudy', 2),
  p('we-snowy', 'weather', 'Snowy', 3),
  p('we-windy', 'weather', 'Windy', 4),
  p('we-hot', 'weather', 'Hot', 5),
  p('we-cold', 'weather', 'Cold', 6),
  p('we-storm', 'weather', 'Storm', 7),

  // Toys & Fun
  p('tf-ball', 'toys-fun', 'Ball', 0),
  p('tf-blocks', 'toys-fun', 'Blocks', 1),
  p('tf-doll', 'toys-fun', 'Doll', 2),
  p('tf-puzzle', 'toys-fun', 'Puzzle', 3),
  p('tf-game', 'toys-fun', 'Game', 4),
  p('tf-movie', 'toys-fun', 'Movie', 5),
  p('tf-music', 'toys-fun', 'Music', 6),
  p('tf-bubbles', 'toys-fun', 'Bubbles', 7),
  p('tf-swing', 'toys-fun', 'Swing', 8),
  p('tf-slide', 'toys-fun', 'Slide', 9),
  p('tf-coloring', 'toys-fun', 'Coloring', 10),
  p('tf-tablet', 'toys-fun', 'Tablet', 11),
];
