import { Phrase } from '@/types';

const p = (id: string, categoryId: string, text: string, sortOrder: number): Phrase => ({
  id, categoryId, text, sortOrder, isCustom: false, usageCount: 0,
});

export const DEFAULT_PHRASES: Phrase[] = [
  // Core Words — Pronouns
  p('cw-i', 'core-pronouns', 'I', 0),
  p('cw-you', 'core-pronouns', 'You', 1),
  p('cw-he', 'core-pronouns', 'He', 2),
  p('cw-she', 'core-pronouns', 'She', 3),
  p('cw-it', 'core-pronouns', 'It', 4),
  p('cw-we', 'core-pronouns', 'We', 5),
  p('cw-they', 'core-pronouns', 'They', 6),
  p('cw-me', 'core-pronouns', 'Me', 7),
  p('cw-my', 'core-pronouns', 'My', 8),
  p('cw-your', 'core-pronouns', 'Your', 9),
  p('cw-his', 'core-pronouns', 'His', 10),
  p('cw-her', 'core-pronouns', 'Her', 11),
  p('cw-this', 'core-pronouns', 'This', 12),
  p('cw-that', 'core-pronouns', 'That', 13),
  p('cw-us', 'core-pronouns', 'Us', 14),
  p('cw-them', 'core-pronouns', 'Them', 15),
  p('cw-mine', 'core-pronouns', 'Mine', 16),
  p('cw-yours', 'core-pronouns', 'Yours', 17),
  p('cw-theirs', 'core-pronouns', 'Theirs', 18),
  p('cw-ours', 'core-pronouns', 'Ours', 19),
  p('cw-hers', 'core-pronouns', 'Hers', 20),
  p('cw-myself', 'core-pronouns', 'Myself', 21),
  p('cw-yourself', 'core-pronouns', 'Yourself', 22),
  p('cw-themselves', 'core-pronouns', 'Themselves', 23),
  p('cw-ourselves', 'core-pronouns', 'Ourselves', 24),
  p('cw-each-other', 'core-pronouns', 'Each other', 25),
  p('cw-anyone', 'core-pronouns', 'Anyone', 26),
  p('cw-someone', 'core-pronouns', 'Someone', 27),
  p('cw-everyone', 'core-pronouns', 'Everyone', 28),
  p('cw-no-one', 'core-pronouns', 'No one', 29),
  p('cw-nobody', 'core-pronouns', 'Nobody', 30),
  p('cw-whose', 'core-pronouns', 'Whose', 31),

  // Core Words — Verbs
  p('cw-want', 'core-verbs', 'Want', 0),
  p('cw-like', 'core-verbs', 'Like', 1),
  p('cw-have', 'core-verbs', 'Have', 2),
  p('cw-do', 'core-verbs', 'Do', 3),
  p('cw-can', 'core-verbs', 'Can', 4),
  p('cw-need', 'core-verbs', 'Need', 5),
  p('cw-know', 'core-verbs', 'Know', 6),
  p('cw-see', 'core-verbs', 'See', 7),
  p('cw-think', 'core-verbs', 'Think', 8),
  p('cw-feel', 'core-verbs', 'Feel', 9),
  p('cw-say', 'core-verbs', 'Say', 10),
  p('cw-tell', 'core-verbs', 'Tell', 11),
  p('cw-try', 'core-verbs', 'Try', 12),
  p('cw-let', 'core-verbs', 'Let', 13),
  p('cw-help', 'core-verbs', 'Help', 14),
  p('cw-make', 'core-verbs', 'Make', 15),
  p('cw-come', 'core-verbs', 'Come', 16),
  p('cw-go-core', 'core-verbs', 'Go', 17),
  p('cw-get-core', 'core-verbs', 'Get', 18),
  p('cw-put-core', 'core-verbs', 'Put', 19),
  p('cw-wait', 'core-verbs', 'Wait', 20),
  p('cw-stop', 'core-verbs', 'Stop', 21),
  p('cw-start', 'core-verbs', 'Start', 22),
  p('cw-finish', 'core-verbs', 'Finish', 23),
  p('cw-begin', 'core-verbs', 'Begin', 24),
  p('cw-end', 'core-verbs', 'End', 25),
  p('cw-stay', 'core-verbs', 'Stay', 26),
  p('cw-leave', 'core-verbs', 'Leave', 27),
  p('cw-look', 'core-verbs', 'Look', 28),
  p('cw-watch', 'core-verbs', 'Watch', 29),
  p('cw-hear', 'core-verbs', 'Hear', 30),
  p('cw-listen', 'core-verbs', 'Listen', 31),
  p('cw-smell', 'core-verbs', 'Smell', 32),
  p('cw-taste', 'core-verbs', 'Taste', 33),
  p('cw-touch', 'core-verbs', 'Touch', 34),
  p('cw-hold', 'core-verbs', 'Hold', 35),
  p('cw-grab', 'core-verbs', 'Grab', 36),
  p('cw-push', 'core-verbs', 'Push', 37),
  p('cw-pull', 'core-verbs', 'Pull', 38),
  p('cw-lift', 'core-verbs', 'Lift', 39),
  p('cw-carry', 'core-verbs', 'Carry', 40),
  p('cw-drop', 'core-verbs', 'Drop', 41),
  p('cw-throw', 'core-verbs', 'Throw', 42),
  p('cw-catch', 'core-verbs', 'Catch', 43),
  p('cw-open', 'core-verbs', 'Open', 44),
  p('cw-close', 'core-verbs', 'Close', 45),
  p('cw-turn', 'core-verbs', 'Turn', 46),
  p('cw-move', 'core-verbs', 'Move', 47),
  p('cw-sit', 'core-verbs', 'Sit', 48),
  p('cw-stand', 'core-verbs', 'Stand', 49),
  p('cw-walk', 'core-verbs', 'Walk', 50),
  p('cw-run', 'core-verbs', 'Run', 51),
  p('cw-jump', 'core-verbs', 'Jump', 52),
  p('cw-climb', 'core-verbs', 'Climb', 53),
  p('cw-fall', 'core-verbs', 'Fall', 54),
  p('cw-rest', 'core-verbs', 'Rest', 55),
  p('cw-sleep', 'core-verbs', 'Sleep', 56),
  p('cw-wake', 'core-verbs', 'Wake', 57),
  p('cw-dream', 'core-verbs', 'Dream', 58),
  p('cw-eat', 'core-verbs', 'Eat', 59),
  p('cw-drink', 'core-verbs', 'Drink', 60),
  p('cw-bite', 'core-verbs', 'Bite', 61),
  p('cw-chew', 'core-verbs', 'Chew', 62),
  p('cw-swallow', 'core-verbs', 'Swallow', 63),
  p('cw-spit', 'core-verbs', 'Spit', 64),
  p('cw-talk', 'core-verbs', 'Talk', 65),
  p('cw-speak', 'core-verbs', 'Speak', 66),
  p('cw-whisper', 'core-verbs', 'Whisper', 67),
  p('cw-shout', 'core-verbs', 'Shout', 68),
  p('cw-sing', 'core-verbs', 'Sing', 69),
  p('cw-laugh', 'core-verbs', 'Laugh', 70),
  p('cw-cry', 'core-verbs', 'Cry', 71),
  p('cw-smile', 'core-verbs', 'Smile', 72),
  p('cw-read', 'core-verbs', 'Read', 73),
  p('cw-write', 'core-verbs', 'Write', 74),
  p('cw-draw', 'core-verbs', 'Draw', 75),
  p('cw-paint', 'core-verbs', 'Paint', 76),
  p('cw-color', 'core-verbs', 'Color', 77),
  p('cw-cut', 'core-verbs', 'Cut', 78),
  p('cw-glue', 'core-verbs', 'Glue', 79),
  p('cw-build', 'core-verbs', 'Build', 80),
  p('cw-break', 'core-verbs', 'Break', 81),
  p('cw-fix', 'core-verbs', 'Fix', 82),
  p('cw-clean', 'core-verbs', 'Clean', 83),
  p('cw-wash', 'core-verbs', 'Wash', 84),
  p('cw-find', 'core-verbs', 'Find', 85),
  p('cw-look-for', 'core-verbs', 'Look for', 86),
  p('cw-lose', 'core-verbs', 'Lose', 87),
  p('cw-save', 'core-verbs', 'Save', 88),
  p('cw-keep', 'core-verbs', 'Keep', 89),
  p('cw-buy', 'core-verbs', 'Buy', 90),
  p('cw-sell', 'core-verbs', 'Sell', 91),
  p('cw-pay', 'core-verbs', 'Pay', 92),
  p('cw-trade', 'core-verbs', 'Trade', 93),
  p('cw-send', 'core-verbs', 'Send', 94),
  p('cw-bring', 'core-verbs', 'Bring', 95),
  p('cw-take', 'core-verbs', 'Take', 96),
  p('cw-give', 'core-verbs', 'Give', 97),
  p('cw-share', 'core-verbs', 'Share', 98),
  p('cw-ask', 'core-verbs', 'Ask', 99),
  p('cw-answer', 'core-verbs', 'Answer', 100),
  p('cw-show', 'core-verbs', 'Show', 101),
  p('cw-hide', 'core-verbs', 'Hide', 102),
  p('cw-learn', 'core-verbs', 'Learn', 103),
  p('cw-teach', 'core-verbs', 'Teach', 104),
  p('cw-study', 'core-verbs', 'Study', 105),
  p('cw-practice', 'core-verbs', 'Practice', 106),
  p('cw-work', 'core-verbs', 'Work', 107),
  p('cw-play', 'core-verbs', 'Play', 108),
  p('cw-win', 'core-verbs', 'Win', 109),
  p('cw-try-again', 'core-verbs', 'Try again', 110),
  p('cw-hug', 'core-verbs', 'Hug', 111),
  p('cw-kiss', 'core-verbs', 'Kiss', 112),
  p('cw-pet', 'core-verbs', 'Pet', 113),
  p('cw-tickle', 'core-verbs', 'Tickle', 114),
  p('cw-wait-for-me', 'core-verbs', 'Wait for me', 115),
  p('cw-help-me', 'core-verbs', 'Help me', 116),
  p('cw-show-me', 'core-verbs', 'Show me', 117),
  p('cw-tell-me', 'core-verbs', 'Tell me', 118),
  p('cw-stop-that', 'core-verbs', 'Stop that', 119),
  p('cw-don-t-do-that', 'core-verbs', "Don't do that", 120),
  p('cw-i-want-to', 'core-verbs', 'I want to', 121),
  p('cw-i-do-not-want', 'core-verbs', 'I do not want', 122),
  p('cw-let-me-try', 'core-verbs', 'Let me try', 123),
  p('cw-let-me-see', 'core-verbs', 'Let me see', 124),

  // Core Words — Descriptors
  p('cw-more', 'core-descriptors', 'More', 0),
  p('cw-not', 'core-descriptors', 'Not', 1),
  p('cw-no-core', 'core-descriptors', 'No', 2),
  p('cw-yes-core', 'core-descriptors', 'Yes', 3),
  p('cw-all', 'core-descriptors', 'All', 4),
  p('cw-some', 'core-descriptors', 'Some', 5),
  p('cw-other', 'core-descriptors', 'Other', 6),
  p('cw-very', 'core-descriptors', 'Very', 7),
  p('cw-here', 'core-descriptors', 'Here', 8),
  p('cw-there', 'core-descriptors', 'There', 9),
  p('cw-up', 'core-descriptors', 'Up', 10),
  p('cw-down', 'core-descriptors', 'Down', 11),
  p('cw-in', 'core-descriptors', 'In', 12),
  p('cw-out', 'core-descriptors', 'Out', 13),
  p('cw-on', 'core-descriptors', 'On', 14),
  p('cw-off', 'core-descriptors', 'Off', 15),
  p('cw-done', 'core-descriptors', 'Done', 16),
  p('cw-again', 'core-descriptors', 'Again', 17),
  p('cw-too', 'core-descriptors', 'Too', 18),
  p('cw-same-core', 'core-descriptors', 'Same', 19),
  p('cw-little', 'core-descriptors', 'Little', 20),
  p('cw-lots', 'core-descriptors', 'Lots', 21),
  p('cw-many', 'core-descriptors', 'Many', 22),
  p('cw-few', 'core-descriptors', 'Few', 23),
  p('cw-every', 'core-descriptors', 'Every', 24),
  p('cw-any', 'core-descriptors', 'Any', 25),
  p('cw-only', 'core-descriptors', 'Only', 26),
  p('cw-just', 'core-descriptors', 'Just', 27),
  p('cw-full', 'core-descriptors', 'Full', 28),
  p('cw-empty', 'core-descriptors', 'Empty', 29),
  p('cw-open-2', 'core-descriptors', 'Open', 30),
  p('cw-closed', 'core-descriptors', 'Closed', 31),
  p('cw-easy', 'core-descriptors', 'Easy', 32),
  p('cw-hard', 'core-descriptors', 'Hard', 33),
  p('cw-soft', 'core-descriptors', 'Soft', 34),
  p('cw-loud', 'core-descriptors', 'Loud', 35),
  p('cw-quiet', 'core-descriptors', 'Quiet', 36),
  p('cw-bright', 'core-descriptors', 'Bright', 37),
  p('cw-dark', 'core-descriptors', 'Dark', 38),
  p('cw-heavy', 'core-descriptors', 'Heavy', 39),
  p('cw-light', 'core-descriptors', 'Light', 40),
  p('cw-above', 'core-descriptors', 'Above', 41),
  p('cw-below', 'core-descriptors', 'Below', 42),
  p('cw-beside', 'core-descriptors', 'Beside', 43),
  p('cw-between', 'core-descriptors', 'Between', 44),
  p('cw-near', 'core-descriptors', 'Near', 45),
  p('cw-far', 'core-descriptors', 'Far', 46),
  p('cw-around', 'core-descriptors', 'Around', 47),
  p('cw-through', 'core-descriptors', 'Through', 48),
  p('cw-over', 'core-descriptors', 'Over', 49),
  p('cw-under', 'core-descriptors', 'Under', 50),
  p('cw-across', 'core-descriptors', 'Across', 51),
  p('cw-behind', 'core-descriptors', 'Behind', 52),
  p('cw-ahead', 'core-descriptors', 'Ahead', 53),
  p('cw-always', 'core-descriptors', 'Always', 54),
  p('cw-never', 'core-descriptors', 'Never', 55),
  p('cw-often', 'core-descriptors', 'Often', 56),
  p('cw-sometimes', 'core-descriptors', 'Sometimes', 57),
  p('cw-maybe', 'core-descriptors', 'Maybe', 58),
  p('cw-almost', 'core-descriptors', 'Almost', 59),
  p('cw-already', 'core-descriptors', 'Already', 60),
  p('cw-still', 'core-descriptors', 'Still', 61),
  p('cw-yet', 'core-descriptors', 'Yet', 62),
  p('cw-right-now', 'core-descriptors', 'Right now', 63),
  p('cw-right-here', 'core-descriptors', 'Right here', 64),
  p('cw-way-too-much', 'core-descriptors', 'Way too much', 65),
  p('cw-not-enough', 'core-descriptors', 'Not enough', 66),

  // Core Words — Little Words
  p('cw-is', 'core-little-words', 'Is', 0),
  p('cw-the', 'core-little-words', 'The', 1),
  p('cw-a', 'core-little-words', 'A', 2),
  p('cw-and', 'core-little-words', 'And', 3),
  p('cw-but', 'core-little-words', 'But', 4),
  p('cw-or', 'core-little-words', 'Or', 5),
  p('cw-to', 'core-little-words', 'To', 6),
  p('cw-for', 'core-little-words', 'For', 7),
  p('cw-with', 'core-little-words', 'With', 8),
  p('cw-at', 'core-little-words', 'At', 9),
  p('cw-of', 'core-little-words', 'Of', 10),
  p('cw-about', 'core-little-words', 'About', 11),
  p('cw-because', 'core-little-words', 'Because', 12),
  p('cw-if', 'core-little-words', 'If', 13),
  p('cw-when-core', 'core-little-words', 'When', 14),
  p('cw-where-core', 'core-little-words', 'Where', 15),
  p('cw-by', 'core-little-words', 'By', 16),
  p('cw-from', 'core-little-words', 'From', 17),
  p('cw-since', 'core-little-words', 'Since', 18),
  p('cw-until', 'core-little-words', 'Until', 19),
  p('cw-into', 'core-little-words', 'Into', 20),
  p('cw-onto', 'core-little-words', 'Onto', 21),
  p('cw-off-of', 'core-little-words', 'Off of', 22),
  p('cw-away', 'core-little-words', 'Away', 23),
  p('cw-back', 'core-little-words', 'Back', 24),
  p('cw-beside-2', 'core-little-words', 'Beside', 25),
  p('cw-past', 'core-little-words', 'Past', 26),
  p('cw-among', 'core-little-words', 'Among', 27),
  p('cw-during', 'core-little-words', 'During', 28),
  p('cw-while', 'core-little-words', 'While', 29),
  p('cw-whenever', 'core-little-words', 'Whenever', 30),
  p('cw-wherever', 'core-little-words', 'Wherever', 31),
  p('cw-both', 'core-little-words', 'Both', 32),
  p('cw-either', 'core-little-words', 'Either', 33),
  p('cw-neither', 'core-little-words', 'Neither', 34),
  p('cw-whether', 'core-little-words', 'Whether', 35),
  p('cw-although', 'core-little-words', 'Although', 36),
  p('cw-though', 'core-little-words', 'Though', 37),
  p('cw-unless', 'core-little-words', 'Unless', 38),
  p('cw-so', 'core-little-words', 'So', 39),
  p('cw-then', 'core-little-words', 'Then', 40),
  p('cw-also', 'core-little-words', 'Also', 41),
  p('cw-plus', 'core-little-words', 'Plus', 42),
  p('cw-like-2', 'core-little-words', 'Like', 43),
  p('cw-as', 'core-little-words', 'As', 44),
  p('cw-such-as', 'core-little-words', 'Such as', 45),
  p('cw-versus', 'core-little-words', 'Versus', 46),
  p('cw-since-then', 'core-little-words', 'Since then', 47),
  p('cw-until-now', 'core-little-words', 'Until now', 48),
  p('cw-right-after', 'core-little-words', 'Right after', 49),
  p('cw-just-before', 'core-little-words', 'Just before', 50),
  p('cw-up-to', 'core-little-words', 'Up to', 51),
  p('cw-down-to', 'core-little-words', 'Down to', 52),
  p('cw-next-to', 'core-little-words', 'Next to', 53),
  p('cw-out-of', 'core-little-words', 'Out of', 54),
  p('cw-a-few', 'core-little-words', 'A few', 55),
  p('cw-a-lot', 'core-little-words', 'A lot', 56),
  p('cw-a-little', 'core-little-words', 'A little', 57),

  // Help / Needs
  p('help-all-done', 'help-needs', 'All done', 0),
  p('help-break', 'help-needs', 'Take a break', 1),
  p('help-need-help', 'help-needs', 'I need help', 2),
  p('help-hungry', 'help-needs', 'I am hungry', 3),
  p('help-thirsty', 'help-needs', 'I am thirsty', 4),
  p('help-bathroom', 'help-needs', 'Bathroom', 5),
  p('help-yes', 'help-needs', 'Yes', 6),
  p('help-no', 'help-needs', 'No', 7),
  p('help-stop', 'help-needs', 'Stop', 8),
  p('help-more', 'help-needs', 'More', 9),
  p('help-want', 'help-needs', 'I want', 10),
  p('help-dont-want', 'help-needs', "I don't want", 11),
  p('help-hurts', 'help-needs', 'It hurts', 12),
  p('help-tired', 'help-needs', 'I am tired', 13),
  p('help-i-am-cold', 'help-needs', 'I am cold', 14),
  p('help-i-am-hot', 'help-needs', 'I am hot', 15),
  p('help-i-am-sleepy', 'help-needs', 'I am sleepy', 16),
  p('help-i-am-scared', 'help-needs', 'I am scared', 17),
  p('help-i-am-sick', 'help-needs', 'I am sick', 18),
  p('help-i-am-okay', 'help-needs', 'I am okay', 19),
  p('help-i-am-not-okay', 'help-needs', 'I am not okay', 20),
  p('help-i-am-ready', 'help-needs', 'I am ready', 21),
  p('help-i-am-not-ready', 'help-needs', 'I am not ready', 22),
  p('help-too-loud', 'help-needs', 'Too loud', 23),
  p('help-too-bright', 'help-needs', 'Too bright', 24),
  p('help-too-fast', 'help-needs', 'Too fast', 25),
  p('help-too-slow', 'help-needs', 'Too slow', 26),
  p('help-i-need-quiet', 'help-needs', 'I need quiet', 27),
  p('help-i-need-a-break', 'help-needs', 'I need a break', 28),
  p('help-i-need-water', 'help-needs', 'I need water', 29),
  p('help-i-need-air', 'help-needs', 'I need air', 30),
  p('help-i-need-my-mom', 'help-needs', 'I need my mom', 31),
  p('help-i-need-my-dad', 'help-needs', 'I need my dad', 32),
  p('help-i-need-my-teacher', 'help-needs', 'I need my teacher', 33),
  p('help-i-need-a-hug', 'help-needs', 'I need a hug', 34),
  p('help-i-need-space', 'help-needs', 'I need space', 35),
  p('help-i-need-time', 'help-needs', 'I need time', 36),
  p('help-hold-my-hand', 'help-needs', 'Hold my hand', 37),
  p('help-watch-me', 'help-needs', 'Watch me', 38),
  p('help-listen-to-me', 'help-needs', 'Listen to me', 39),
  p('help-look-at-this', 'help-needs', 'Look at this', 40),
  p('help-help-me-please', 'help-needs', 'Help me please', 41),
  p('help-help-with-this', 'help-needs', 'Help with this', 42),
  p('help-wait-for-me', 'help-needs', 'Wait for me', 43),
  p('help-slow-down-please', 'help-needs', 'Slow down please', 44),
  p('help-speak-more-slowly', 'help-needs', 'Speak more slowly', 45),
  p('help-one-at-a-time', 'help-needs', 'One at a time', 46),
  p('help-i-am-overwhelmed', 'help-needs', 'I am overwhelmed', 47),
  p('help-i-am-confused', 'help-needs', 'I am confused', 48),
  p('help-i-do-not-understand', 'help-needs', 'I do not understand', 49),
  p('help-please-be-patient', 'help-needs', 'Please be patient', 50),
  p('help-give-me-a-minute', 'help-needs', 'Give me a minute', 51),
  p('help-try-again', 'help-needs', 'Try again', 52),
  p('help-calm-down', 'help-needs', 'Calm down', 53),
  p('help-let-me-think', 'help-needs', 'Let me think', 54),
  p('help-show-me-how', 'help-needs', 'Show me how', 55),
  p('help-i-do-not-feel-good', 'help-needs', 'I do not feel good', 56),
  p('help-my-head-hurts', 'help-needs', 'My head hurts', 57),
  p('help-my-tummy-hurts', 'help-needs', 'My tummy hurts', 58),
  p('help-my-ears-hurt', 'help-needs', 'My ears hurt', 59),
  p('help-my-eyes-hurt', 'help-needs', 'My eyes hurt', 60),
  p('help-i-feel-dizzy', 'help-needs', 'I feel dizzy', 61),
  p('help-get-help', 'help-needs', 'Get help', 62),
  p('help-call-my-mom', 'help-needs', 'Call my mom', 63),
  p('help-call-my-dad', 'help-needs', 'Call my dad', 64),
  p('help-call-the-nurse', 'help-needs', 'Call the nurse', 65),
  p('help-where-is-my-aac', 'help-needs', 'Where is my AAC', 66),
  p('help-my-battery-is-low', 'help-needs', 'My battery is low', 67),
  p('help-i-dropped-my-tablet', 'help-needs', 'I dropped my tablet', 68),

  // Quick Talk
  p('qt-hello', 'quick-talk', 'Hello', 0),
  p('qt-goodbye', 'quick-talk', 'Goodbye', 1),
  p('qt-thank-you', 'quick-talk', 'Thank you', 2),
  p('qt-please', 'quick-talk', 'Please', 3),
  p('qt-excuse-me', 'quick-talk', 'Excuse me', 4),
  p('qt-dont-understand', 'quick-talk', "I don't understand", 5),
  p('qt-wait', 'quick-talk', 'Wait', 6),
  p('qt-come-here', 'quick-talk', 'Come here', 7),
  p('qt-how-are-you', 'quick-talk', 'How are you?', 8),
  p('qt-im-good', 'quick-talk', "I'm good", 9),
  p('qt-sorry', 'quick-talk', 'Sorry', 10),
  p('qt-i-dont-know', 'quick-talk', "I don't know", 11),
  p('qt-my-name', 'quick-talk', 'My name is', 12),
  p('qt-nice-meet', 'quick-talk', 'Nice to meet you', 13),
  p('qt-see-later', 'quick-talk', 'See you later', 14),
  p('qt-youre-welcome', 'quick-talk', "You're welcome", 15),
  p('qt-hi', 'quick-talk', 'Hi', 16),
  p('qt-hey', 'quick-talk', 'Hey', 17),
  p('qt-bye', 'quick-talk', 'Bye', 18),
  p('qt-bye-bye', 'quick-talk', 'Bye-bye', 19),
  p('qt-see-you', 'quick-talk', 'See you', 20),
  p('qt-see-you-soon', 'quick-talk', 'See you soon', 21),
  p('qt-see-you-tomorrow', 'quick-talk', 'See you tomorrow', 22),
  p('qt-take-care', 'quick-talk', 'Take care', 23),
  p('qt-have-fun', 'quick-talk', 'Have fun', 24),
  p('qt-good-morning', 'quick-talk', 'Good morning', 25),
  p('qt-good-afternoon', 'quick-talk', 'Good afternoon', 26),
  p('qt-good-evening', 'quick-talk', 'Good evening', 27),
  p('qt-good-night', 'quick-talk', 'Good night', 28),
  p('qt-good-job', 'quick-talk', 'Good job', 29),
  p('qt-well-done', 'quick-talk', 'Well done', 30),
  p('qt-way-to-go', 'quick-talk', 'Way to go', 31),
  p('qt-awesome', 'quick-talk', 'Awesome', 32),
  p('qt-cool', 'quick-talk', 'Cool', 33),
  p('qt-nice', 'quick-talk', 'Nice', 34),
  p('qt-great', 'quick-talk', 'Great', 35),
  p('qt-wonderful', 'quick-talk', 'Wonderful', 36),
  p('qt-amazing', 'quick-talk', 'Amazing', 37),
  p('qt-perfect', 'quick-talk', 'Perfect', 38),
  p('qt-yay', 'quick-talk', 'Yay', 39),
  p('qt-okay', 'quick-talk', 'Okay', 40),
  p('qt-alright', 'quick-talk', 'Alright', 41),
  p('qt-sure', 'quick-talk', 'Sure', 42),
  p('qt-of-course', 'quick-talk', 'Of course', 43),
  p('qt-definitely', 'quick-talk', 'Definitely', 44),
  p('qt-maybe', 'quick-talk', 'Maybe', 45),
  p('qt-i-think-so', 'quick-talk', 'I think so', 46),
  p('qt-i-am-not-sure', 'quick-talk', 'I am not sure', 47),
  p('qt-it-is-fine', 'quick-talk', 'It is fine', 48),
  p('qt-no-problem', 'quick-talk', 'No problem', 49),
  p('qt-no-worries', 'quick-talk', 'No worries', 50),
  p('qt-never-mind', 'quick-talk', 'Never mind', 51),
  p('qt-my-bad', 'quick-talk', 'My bad', 52),
  p('qt-oops', 'quick-talk', 'Oops', 53),
  p('qt-bless-you', 'quick-talk', 'Bless you', 54),
  p('qt-happy-birthday', 'quick-talk', 'Happy birthday', 55),
  p('qt-happy-holidays', 'quick-talk', 'Happy holidays', 56),
  p('qt-merry-christmas', 'quick-talk', 'Merry Christmas', 57),
  p('qt-happy-new-year', 'quick-talk', 'Happy New Year', 58),
  p('qt-eid-mubarak', 'quick-talk', 'Eid Mubarak', 59),
  p('qt-happy-hanukkah', 'quick-talk', 'Happy Hanukkah', 60),
  p('qt-congratulations', 'quick-talk', 'Congratulations', 61),
  p('qt-i-am-proud-of-you', 'quick-talk', 'I am proud of you', 62),
  p('qt-you-did-it', 'quick-talk', 'You did it', 63),
  p('qt-how-was-your-day', 'quick-talk', 'How was your day', 64),
  p('qt-i-had-a-good-day', 'quick-talk', 'I had a good day', 65),
  p('qt-i-had-a-bad-day', 'quick-talk', 'I had a bad day', 66),
  p('qt-tell-me-about-your-day', 'quick-talk', 'Tell me about your day', 67),
  p('qt-i-missed-you', 'quick-talk', 'I missed you', 68),
  p('qt-i-am-here', 'quick-talk', 'I am here', 69),
  p('qt-i-love-you-too', 'quick-talk', 'I love you too', 70),
  p('qt-you-are-my-friend', 'quick-talk', 'You are my friend', 71),
  p('qt-best-friends', 'quick-talk', 'Best friends', 72),

  // Feelings
  p('fe-happy', 'feelings', 'Happy', 0),
  p('fe-sad', 'feelings', 'Sad', 1),
  p('fe-angry', 'feelings', 'Angry', 2),
  p('fe-scared', 'feelings', 'Scared', 3),
  p('fe-excited', 'feelings', 'Excited', 4),
  p('fe-frustrated', 'feelings', 'Frustrated', 5),
  p('fe-bored', 'feelings', 'Bored', 6),
  p('fe-surprised', 'feelings', 'Surprised', 7),
  p('fe-confused', 'feelings', 'Confused', 8),
  p('fe-proud', 'feelings', 'Proud', 9),
  p('fe-nervous', 'feelings', 'Nervous', 10),
  p('fe-silly', 'feelings', 'Silly', 11),
  p('fe-love', 'feelings', 'I love you', 12),
  p('fe-hurt', 'feelings', 'My feelings are hurt', 13),
  p('fe-calm', 'feelings', 'Calm', 14),
  p('fe-peaceful', 'feelings', 'Peaceful', 15),
  p('fe-relaxed', 'feelings', 'Relaxed', 16),
  p('fe-content', 'feelings', 'Content', 17),
  p('fe-joyful', 'feelings', 'Joyful', 18),
  p('fe-glad', 'feelings', 'Glad', 19),
  p('fe-cheerful', 'feelings', 'Cheerful', 20),
  p('fe-hopeful', 'feelings', 'Hopeful', 21),
  p('fe-grateful', 'feelings', 'Grateful', 22),
  p('fe-thankful', 'feelings', 'Thankful', 23),
  p('fe-loved', 'feelings', 'Loved', 24),
  p('fe-safe', 'feelings', 'Safe', 25),
  p('fe-comfortable', 'feelings', 'Comfortable', 26),
  p('fe-warm-inside', 'feelings', 'Warm inside', 27),
  p('fe-tired', 'feelings', 'Tired', 28),
  p('fe-sleepy', 'feelings', 'Sleepy', 29),
  p('fe-hungry', 'feelings', 'Hungry', 30),
  p('fe-full', 'feelings', 'Full', 31),
  p('fe-thirsty', 'feelings', 'Thirsty', 32),
  p('fe-sick', 'feelings', 'Sick', 33),
  p('fe-lonely', 'feelings', 'Lonely', 34),
  p('fe-embarrassed', 'feelings', 'Embarrassed', 35),
  p('fe-shy', 'feelings', 'Shy', 36),
  p('fe-ashamed', 'feelings', 'Ashamed', 37),
  p('fe-guilty', 'feelings', 'Guilty', 38),
  p('fe-jealous', 'feelings', 'Jealous', 39),
  p('fe-disappointed', 'feelings', 'Disappointed', 40),
  p('fe-annoyed', 'feelings', 'Annoyed', 41),
  p('fe-anxious', 'feelings', 'Anxious', 42),
  p('fe-worried', 'feelings', 'Worried', 43),
  p('fe-stressed', 'feelings', 'Stressed', 44),
  p('fe-panicked', 'feelings', 'Panicked', 45),
  p('fe-terrified', 'feelings', 'Terrified', 46),
  p('fe-brave', 'feelings', 'Brave', 47),
  p('fe-strong', 'feelings', 'Strong', 48),
  p('fe-weak', 'feelings', 'Weak', 49),
  p('fe-dizzy', 'feelings', 'Dizzy', 50),
  p('fe-itchy', 'feelings', 'Itchy', 51),
  p('fe-ticklish', 'feelings', 'Ticklish', 52),
  p('fe-numb', 'feelings', 'Numb', 53),
  p('fe-cold-inside', 'feelings', 'Cold inside', 54),
  p('fe-empty', 'feelings', 'Empty', 55),
  p('fe-heavy-heart', 'feelings', 'Heavy heart', 56),
  p('fe-mixed-up', 'feelings', 'Mixed up', 57),
  p('fe-confused-inside', 'feelings', 'Confused inside', 58),
  p('fe-stuck', 'feelings', 'Stuck', 59),
  p('fe-missing-someone', 'feelings', 'Missing someone', 60),
  p('fe-homesick', 'feelings', 'Homesick', 61),
  p('fe-overwhelmed', 'feelings', 'Overwhelmed', 62),
  p('fe-done-with-this', 'feelings', 'Done with this', 63),
  p('fe-i-have-had-enough', 'feelings', 'I have had enough', 64),
  p('fe-i-feel-good', 'feelings', 'I feel good', 65),
  p('fe-i-feel-bad', 'feelings', 'I feel bad', 66),
  p('fe-i-feel-okay', 'feelings', 'I feel okay', 67),
  p('fe-i-feel-weird', 'feelings', 'I feel weird', 68),

  // Questions
  p('qu-what', 'questions', 'What?', 0),
  p('qu-where', 'questions', 'Where?', 1),
  p('qu-when', 'questions', 'When?', 2),
  p('qu-who', 'questions', 'Who?', 3),
  p('qu-why', 'questions', 'Why?', 4),
  p('qu-how', 'questions', 'How?', 5),
  p('qu-which', 'questions', 'Which one?', 6),
  p('qu-how-many', 'questions', 'How many?', 7),
  p('qu-can-i', 'questions', 'Can I?', 8),
  p('qu-is-it', 'questions', 'Is it?', 9),
  p('qu-whats-that', 'questions', "What's that?", 10),
  p('qu-where-going', 'questions', 'Where are we going?', 11),
  p('qu-who-is-that', 'questions', 'Who is that', 12),
  p('qu-what-is-that', 'questions', 'What is that', 13),
  p('qu-where-is-it', 'questions', 'Where is it', 14),
  p('qu-when-is-it', 'questions', 'When is it', 15),
  p('qu-why-is-that', 'questions', 'Why is that', 16),
  p('qu-how-does-it-work', 'questions', 'How does it work', 17),
  p('qu-how-do-i', 'questions', 'How do I', 18),
  p('qu-can-i-have-it', 'questions', 'Can I have it', 19),
  p('qu-can-i-try', 'questions', 'Can I try', 20),
  p('qu-can-i-go', 'questions', 'Can I go', 21),
  p('qu-may-i-please', 'questions', 'May I please', 22),
  p('qu-will-you-help', 'questions', 'Will you help', 23),
  p('qu-are-you-okay', 'questions', 'Are you okay', 24),
  p('qu-are-we-there-yet', 'questions', 'Are we there yet', 25),
  p('qu-where-are-we-going', 'questions', 'Where are we going', 26),
  p('qu-when-will-we-be-there', 'questions', 'When will we be there', 27),
  p('qu-how-much-longer', 'questions', 'How much longer', 28),
  p('qu-what-time-is-it', 'questions', 'What time is it', 29),
  p('qu-what-day-is-it', 'questions', 'What day is it', 30),
  p('qu-is-it-ready-yet', 'questions', 'Is it ready yet', 31),
  p('qu-can-we-go-now', 'questions', 'Can we go now', 32),
  p('qu-can-we-do-this', 'questions', 'Can we do this', 33),
  p('qu-did-you-see-that', 'questions', 'Did you see that', 34),
  p('qu-did-i-do-good', 'questions', 'Did I do good', 35),
  p('qu-what-happened', 'questions', 'What happened', 36),
  p('qu-where-did-it-go', 'questions', 'Where did it go', 37),
  p('qu-who-said-that', 'questions', 'Who said that', 38),
  p('qu-what-did-they-say', 'questions', 'What did they say', 39),
  p('qu-how-old-are-you', 'questions', 'How old are you', 40),
  p('qu-what-is-your-name', 'questions', 'What is your name', 41),
  p('qu-how-are-you-feeling', 'questions', 'How are you feeling', 42),
  p('qu-what-is-for-dinner', 'questions', 'What is for dinner', 43),
  p('qu-what-is-for-snack', 'questions', 'What is for snack', 44),
  p('qu-is-it-bedtime', 'questions', 'Is it bedtime', 45),
  p('qu-are-you-my-friend', 'questions', 'Are you my friend', 46),
  p('qu-will-you-play-with-me', 'questions', 'Will you play with me', 47),

  // Actions
  p('ac-go', 'actions', 'Go', 0),
  p('ac-stop', 'actions', 'Stop', 1),
  p('ac-eat', 'actions', 'Eat', 2),
  p('ac-drink', 'actions', 'Drink', 3),
  p('ac-play', 'actions', 'Play', 4),
  p('ac-read', 'actions', 'Read', 5),
  p('ac-watch', 'actions', 'Watch', 6),
  p('ac-listen', 'actions', 'Listen', 7),
  p('ac-open', 'actions', 'Open', 8),
  p('ac-close', 'actions', 'Close', 9),
  p('ac-give', 'actions', 'Give', 10),
  p('ac-take', 'actions', 'Take', 11),
  p('ac-look', 'actions', 'Look', 12),
  p('ac-sit', 'actions', 'Sit', 13),
  p('ac-stand', 'actions', 'Stand up', 14),
  p('ac-walk', 'actions', 'Walk', 15),
  p('ac-run', 'actions', 'Run', 16),
  p('ac-write', 'actions', 'Write', 17),
  p('ac-draw', 'actions', 'Draw', 18),
  p('ac-make', 'actions', 'Make', 19),
  p('ac-put', 'actions', 'Put', 20),
  p('ac-get', 'actions', 'Get', 21),
  p('ac-turn', 'actions', 'Turn', 22),
  p('ac-wash', 'actions', 'Wash', 23),
  p('ac-wave', 'actions', 'Wave', 24),
  p('ac-clap', 'actions', 'Clap', 25),
  p('ac-point', 'actions', 'Point', 26),
  p('ac-nod', 'actions', 'Nod', 27),
  p('ac-shake-head', 'actions', 'Shake head', 28),
  p('ac-whisper', 'actions', 'Whisper', 29),
  p('ac-shout', 'actions', 'Shout', 30),
  p('ac-sing', 'actions', 'Sing', 31),
  p('ac-hum', 'actions', 'Hum', 32),
  p('ac-roll', 'actions', 'Roll', 33),
  p('ac-slide', 'actions', 'Slide', 34),
  p('ac-spin', 'actions', 'Spin', 35),
  p('ac-hop', 'actions', 'Hop', 36),
  p('ac-skip', 'actions', 'Skip', 37),
  p('ac-crawl', 'actions', 'Crawl', 38),
  p('ac-tiptoe', 'actions', 'Tiptoe', 39),
  p('ac-tip-toe', 'actions', 'Tip-toe', 40),
  p('ac-march', 'actions', 'March', 41),
  p('ac-climb-up', 'actions', 'Climb up', 42),
  p('ac-climb-down', 'actions', 'Climb down', 43),
  p('ac-push-it', 'actions', 'Push it', 44),
  p('ac-pull-it', 'actions', 'Pull it', 45),
  p('ac-pick-it-up', 'actions', 'Pick it up', 46),
  p('ac-set-it-down', 'actions', 'Set it down', 47),
  p('ac-pour', 'actions', 'Pour', 48),
  p('ac-stir', 'actions', 'Stir', 49),
  p('ac-mix', 'actions', 'Mix', 50),
  p('ac-spread', 'actions', 'Spread', 51),
  p('ac-fold', 'actions', 'Fold', 52),
  p('ac-tie', 'actions', 'Tie', 53),
  p('ac-untie', 'actions', 'Untie', 54),
  p('ac-zip', 'actions', 'Zip', 55),
  p('ac-unzip', 'actions', 'Unzip', 56),
  p('ac-snap', 'actions', 'Snap', 57),
  p('ac-buckle', 'actions', 'Buckle', 58),
  p('ac-brush-teeth', 'actions', 'Brush teeth', 59),
  p('ac-brush-hair', 'actions', 'Brush hair', 60),
  p('ac-comb', 'actions', 'Comb', 61),
  p('ac-floss', 'actions', 'Floss', 62),
  p('ac-get-dressed', 'actions', 'Get dressed', 63),
  p('ac-get-undressed', 'actions', 'Get undressed', 64),
  p('ac-put-on-shoes', 'actions', 'Put on shoes', 65),
  p('ac-take-off-shoes', 'actions', 'Take off shoes', 66),
  p('ac-wash-hands', 'actions', 'Wash hands', 67),
  p('ac-take-a-bath', 'actions', 'Take a bath', 68),
  p('ac-take-a-shower', 'actions', 'Take a shower', 69),
  p('ac-sleep', 'actions', 'Sleep', 70),
  p('ac-take-a-nap', 'actions', 'Take a nap', 71),
  p('ac-wake-up', 'actions', 'Wake up', 72),
  p('ac-wait-for', 'actions', 'Wait for', 73),
  p('ac-look-for', 'actions', 'Look for', 74),
  p('ac-search', 'actions', 'Search', 75),
  p('ac-discover', 'actions', 'Discover', 76),
  p('ac-hide', 'actions', 'Hide', 77),
  p('ac-seek', 'actions', 'Seek', 78),
  p('ac-tag', 'actions', 'Tag', 79),
  p('ac-race', 'actions', 'Race', 80),
  p('ac-cuddle', 'actions', 'Cuddle', 81),
  p('ac-snuggle', 'actions', 'Snuggle', 82),
  p('ac-pat', 'actions', 'Pat', 83),
  p('ac-tickle', 'actions', 'Tickle', 84),
  p('ac-sweep', 'actions', 'Sweep', 85),
  p('ac-mop', 'actions', 'Mop', 86),
  p('ac-vacuum', 'actions', 'Vacuum', 87),
  p('ac-dust', 'actions', 'Dust', 88),
  p('ac-carry-it', 'actions', 'Carry it', 89),
  p('ac-drop-it', 'actions', 'Drop it', 90),
  p('ac-toss-it', 'actions', 'Toss it', 91),
  p('ac-roll-it', 'actions', 'Roll it', 92),

  // Describing Words
  p('dw-big', 'describing', 'Big', 0),
  p('dw-small', 'describing', 'Small', 1),
  p('dw-hot', 'describing', 'Hot', 2),
  p('dw-cold', 'describing', 'Cold', 3),
  p('dw-good', 'describing', 'Good', 4),
  p('dw-bad', 'describing', 'Bad', 5),
  p('dw-fast', 'describing', 'Fast', 6),
  p('dw-slow', 'describing', 'Slow', 7),
  p('dw-new', 'describing', 'New', 8),
  p('dw-old', 'describing', 'Old', 9),
  p('dw-same', 'describing', 'Same', 10),
  p('dw-different', 'describing', 'Different', 11),
  p('dw-funny', 'describing', 'Funny', 12),
  p('dw-pretty', 'describing', 'Pretty', 13),
  p('dw-yucky', 'describing', 'Yucky', 14),
  p('dw-favorite', 'describing', 'Favorite', 15),
  p('dw-tall', 'describing', 'Tall', 16),
  p('dw-short', 'describing', 'Short', 17),
  p('dw-long', 'describing', 'Long', 18),
  p('dw-wide', 'describing', 'Wide', 19),
  p('dw-narrow', 'describing', 'Narrow', 20),
  p('dw-thick', 'describing', 'Thick', 21),
  p('dw-thin', 'describing', 'Thin', 22),
  p('dw-round', 'describing', 'Round', 23),
  p('dw-square', 'describing', 'Square', 24),
  p('dw-smooth', 'describing', 'Smooth', 25),
  p('dw-rough', 'describing', 'Rough', 26),
  p('dw-sticky', 'describing', 'Sticky', 27),
  p('dw-wet', 'describing', 'Wet', 28),
  p('dw-dry', 'describing', 'Dry', 29),
  p('dw-clean', 'describing', 'Clean', 30),
  p('dw-dirty', 'describing', 'Dirty', 31),
  p('dw-soft', 'describing', 'Soft', 32),
  p('dw-hard', 'describing', 'Hard', 33),
  p('dw-sweet', 'describing', 'Sweet', 34),
  p('dw-salty', 'describing', 'Salty', 35),
  p('dw-sour', 'describing', 'Sour', 36),
  p('dw-spicy', 'describing', 'Spicy', 37),
  p('dw-bitter', 'describing', 'Bitter', 38),
  p('dw-quiet', 'describing', 'Quiet', 39),
  p('dw-loud', 'describing', 'Loud', 40),
  p('dw-bright', 'describing', 'Bright', 41),
  p('dw-dark', 'describing', 'Dark', 42),
  p('dw-shiny', 'describing', 'Shiny', 43),
  p('dw-heavy', 'describing', 'Heavy', 44),
  p('dw-light', 'describing', 'Light', 45),
  p('dw-empty', 'describing', 'Empty', 46),
  p('dw-full', 'describing', 'Full', 47),
  p('dw-easy', 'describing', 'Easy', 48),
  p('dw-tricky', 'describing', 'Tricky', 49),
  p('dw-simple', 'describing', 'Simple', 50),
  p('dw-fun', 'describing', 'Fun', 51),
  p('dw-boring', 'describing', 'Boring', 52),
  p('dw-cool', 'describing', 'Cool', 53),
  p('dw-awesome', 'describing', 'Awesome', 54),
  p('dw-scary', 'describing', 'Scary', 55),
  p('dw-safe', 'describing', 'Safe', 56),
  p('dw-dangerous', 'describing', 'Dangerous', 57),
  p('dw-friendly', 'describing', 'Friendly', 58),
  p('dw-mean', 'describing', 'Mean', 59),
  p('dw-nice', 'describing', 'Nice', 60),
  p('dw-helpful', 'describing', 'Helpful', 61),
  p('dw-mine', 'describing', 'Mine', 62),
  p('dw-special', 'describing', 'Special', 63),

  // People
  p('pp-mom', 'people-social', 'Mom', 0),
  p('pp-dad', 'people-social', 'Dad', 1),
  p('pp-teacher', 'people-social', 'Teacher', 2),
  p('pp-friend', 'people-social', 'Friend', 3),
  p('pp-family', 'people-social', 'Family', 4),
  p('pp-doctor', 'people-social', 'Doctor', 5),
  p('pp-brother', 'people-social', 'Brother', 6),
  p('pp-sister', 'people-social', 'Sister', 7),
  p('pp-grandma', 'people-social', 'Grandma', 8),
  p('pp-grandpa', 'people-social', 'Grandpa', 9),
  p('pp-baby', 'people-social', 'Baby', 10),
  p('pp-boy', 'people-social', 'Boy', 11),
  p('pp-girl', 'people-social', 'Girl', 12),
  p('pp-therapist', 'people-social', 'Therapist', 13),
  p('pp-aunt', 'people-social', 'Aunt', 14),
  p('pp-uncle', 'people-social', 'Uncle', 15),
  p('pp-cousin', 'people-social', 'Cousin', 16),
  p('pp-stepmom', 'people-social', 'Stepmom', 17),
  p('pp-stepdad', 'people-social', 'Stepdad', 18),
  p('pp-bus-driver', 'people-social', 'Bus driver', 19),
  p('pp-coach', 'people-social', 'Coach', 20),
  p('pp-principal', 'people-social', 'Principal', 21),
  p('pp-counselor', 'people-social', 'Counselor', 22),
  p('pp-nurse', 'people-social', 'Nurse', 23),
  p('pp-dentist', 'people-social', 'Dentist', 24),
  p('pp-bcba', 'people-social', 'BCBA', 25),
  p('pp-rbt', 'people-social', 'RBT', 26),
  p('pp-babysitter', 'people-social', 'Babysitter', 27),
  p('pp-neighbor', 'people-social', 'Neighbor', 28),
  p('pp-helper', 'people-social', 'Helper', 29),
  p('pp-classmate', 'people-social', 'Classmate', 30),
  p('pp-best-friend', 'people-social', 'Best friend', 31),
  p('pp-new-friend', 'people-social', 'New friend', 32),
  p('pp-man', 'people-social', 'Man', 33),
  p('pp-woman', 'people-social', 'Woman', 34),
  p('pp-kid', 'people-social', 'Kid', 35),
  p('pp-grown-up', 'people-social', 'Grown-up', 36),
  p('pp-stranger', 'people-social', 'Stranger', 37),
  p('pp-police-officer', 'people-social', 'Police officer', 38),
  p('pp-firefighter', 'people-social', 'Firefighter', 39),
  p('pp-paramedic', 'people-social', 'Paramedic', 40),
  p('pp-my-family', 'people-social', 'My family', 41),
  p('pp-my-class', 'people-social', 'My class', 42),
  p('pp-my-team', 'people-social', 'My team', 43),

  // Food & Drink
  p('fd-water', 'food-ordering', 'Water', 0),
  p('fd-juice', 'food-ordering', 'Juice', 1),
  p('fd-milk', 'food-ordering', 'Milk', 2),
  p('fd-pizza', 'food-ordering', 'Pizza', 3),
  p('fd-sandwich', 'food-ordering', 'Sandwich', 4),
  p('fd-chicken', 'food-ordering', 'Chicken', 5),
  p('fd-fries', 'food-ordering', 'Fries', 6),
  p('fd-fruit', 'food-ordering', 'Fruit', 7),
  p('fd-snack', 'food-ordering', 'Snack', 8),
  p('fd-more', 'food-ordering', 'More please', 9),
  p('fd-no-thanks', 'food-ordering', 'No thanks', 10),
  p('fd-cookie', 'food-ordering', 'Cookie', 11),
  p('fd-apple', 'food-ordering', 'Apple', 12),
  p('fd-banana', 'food-ordering', 'Banana', 13),
  p('fd-cereal', 'food-ordering', 'Cereal', 14),
  p('fd-cheese', 'food-ordering', 'Cheese', 15),
  p('fd-ice-cream', 'food-ordering', 'Ice cream', 16),
  p('fd-crackers', 'food-ordering', 'Crackers', 17),
  p('fd-bread', 'food-ordering', 'Bread', 18),
  p('fd-toast', 'food-ordering', 'Toast', 19),
  p('fd-pancakes', 'food-ordering', 'Pancakes', 20),
  p('fd-waffles', 'food-ordering', 'Waffles', 21),
  p('fd-eggs', 'food-ordering', 'Eggs', 22),
  p('fd-bacon', 'food-ordering', 'Bacon', 23),
  p('fd-yogurt', 'food-ordering', 'Yogurt', 24),
  p('fd-oatmeal', 'food-ordering', 'Oatmeal', 25),
  p('fd-granola', 'food-ordering', 'Granola', 26),
  p('fd-smoothie', 'food-ordering', 'Smoothie', 27),
  p('fd-pasta', 'food-ordering', 'Pasta', 28),
  p('fd-noodles', 'food-ordering', 'Noodles', 29),
  p('fd-rice', 'food-ordering', 'Rice', 30),
  p('fd-soup', 'food-ordering', 'Soup', 31),
  p('fd-salad', 'food-ordering', 'Salad', 32),
  p('fd-wrap', 'food-ordering', 'Wrap', 33),
  p('fd-hamburger', 'food-ordering', 'Hamburger', 34),
  p('fd-hot-dog', 'food-ordering', 'Hot dog', 35),
  p('fd-taco', 'food-ordering', 'Taco', 36),
  p('fd-burrito', 'food-ordering', 'Burrito', 37),
  p('fd-quesadilla', 'food-ordering', 'Quesadilla', 38),
  p('fd-sushi', 'food-ordering', 'Sushi', 39),
  p('fd-dumplings', 'food-ordering', 'Dumplings', 40),
  p('fd-curry', 'food-ordering', 'Curry', 41),
  p('fd-stir-fry', 'food-ordering', 'Stir fry', 42),
  p('fd-carrots', 'food-ordering', 'Carrots', 43),
  p('fd-broccoli', 'food-ordering', 'Broccoli', 44),
  p('fd-peas', 'food-ordering', 'Peas', 45),
  p('fd-corn', 'food-ordering', 'Corn', 46),
  p('fd-tomato', 'food-ordering', 'Tomato', 47),
  p('fd-cucumber', 'food-ordering', 'Cucumber', 48),
  p('fd-lettuce', 'food-ordering', 'Lettuce', 49),
  p('fd-spinach', 'food-ordering', 'Spinach', 50),
  p('fd-potato', 'food-ordering', 'Potato', 51),
  p('fd-sweet-potato', 'food-ordering', 'Sweet potato', 52),
  p('fd-strawberry', 'food-ordering', 'Strawberry', 53),
  p('fd-blueberry', 'food-ordering', 'Blueberry', 54),
  p('fd-grapes', 'food-ordering', 'Grapes', 55),
  p('fd-watermelon', 'food-ordering', 'Watermelon', 56),
  p('fd-orange', 'food-ordering', 'Orange', 57),
  p('fd-pear', 'food-ordering', 'Pear', 58),
  p('fd-peach', 'food-ordering', 'Peach', 59),
  p('fd-mango', 'food-ordering', 'Mango', 60),
  p('fd-pineapple', 'food-ordering', 'Pineapple', 61),
  p('fd-cake', 'food-ordering', 'Cake', 62),
  p('fd-cupcake', 'food-ordering', 'Cupcake', 63),
  p('fd-brownie', 'food-ordering', 'Brownie', 64),
  p('fd-donut', 'food-ordering', 'Donut', 65),
  p('fd-muffin', 'food-ordering', 'Muffin', 66),
  p('fd-pie', 'food-ordering', 'Pie', 67),
  p('fd-pudding', 'food-ordering', 'Pudding', 68),
  p('fd-jello', 'food-ordering', 'Jello', 69),
  p('fd-candy', 'food-ordering', 'Candy', 70),
  p('fd-chocolate', 'food-ordering', 'Chocolate', 71),
  p('fd-lollipop', 'food-ordering', 'Lollipop', 72),
  p('fd-gum', 'food-ordering', 'Gum', 73),
  p('fd-soda', 'food-ordering', 'Soda', 74),
  p('fd-tea', 'food-ordering', 'Tea', 75),
  p('fd-hot-chocolate', 'food-ordering', 'Hot chocolate', 76),
  p('fd-lemonade', 'food-ordering', 'Lemonade', 77),
  p('fd-spoon', 'food-ordering', 'Spoon', 78),
  p('fd-fork', 'food-ordering', 'Fork', 79),
  p('fd-knife', 'food-ordering', 'Knife', 80),
  p('fd-plate', 'food-ordering', 'Plate', 81),
  p('fd-bowl', 'food-ordering', 'Bowl', 82),
  p('fd-cup', 'food-ordering', 'Cup', 83),
  p('fd-straw', 'food-ordering', 'Straw', 84),
  p('fd-napkin', 'food-ordering', 'Napkin', 85),
  p('fd-bib', 'food-ordering', 'Bib', 86),
  p('fd-open-it-please', 'food-ordering', 'Open it please', 87),
  p('fd-cut-it-up-please', 'food-ordering', 'Cut it up please', 88),
  p('fd-not-too-hot', 'food-ordering', 'Not too hot', 89),
  p('fd-i-am-allergic', 'food-ordering', 'I am allergic', 90),

  // Places
  p('pl-home', 'places-plans', 'Home', 0),
  p('pl-school', 'places-plans', 'School', 1),
  p('pl-park', 'places-plans', 'Park', 2),
  p('pl-store', 'places-plans', 'Store', 3),
  p('pl-restaurant', 'places-plans', 'Restaurant', 4),
  p('pl-library', 'places-plans', 'Library', 5),
  p('pl-pool', 'places-plans', 'Pool', 6),
  p('pl-car', 'places-plans', 'Car', 7),
  p('pl-outside', 'places-plans', 'Outside', 8),
  p('pl-inside', 'places-plans', 'Inside', 9),
  p('pl-bathroom', 'places-plans', 'Bathroom', 10),
  p('pl-bedroom', 'places-plans', 'Bedroom', 11),
  p('pl-kitchen', 'places-plans', 'Kitchen', 12),
  p('pl-playground', 'places-plans', 'Playground', 13),
  p('pl-backyard', 'places-plans', 'Backyard', 14),
  p('pl-front-yard', 'places-plans', 'Front yard', 15),
  p('pl-garden', 'places-plans', 'Garden', 16),
  p('pl-driveway', 'places-plans', 'Driveway', 17),
  p('pl-living-room', 'places-plans', 'Living room', 18),
  p('pl-dining-room', 'places-plans', 'Dining room', 19),
  p('pl-garage', 'places-plans', 'Garage', 20),
  p('pl-basement', 'places-plans', 'Basement', 21),
  p('pl-attic', 'places-plans', 'Attic', 22),
  p('pl-hospital', 'places-plans', 'Hospital', 23),
  p('pl-doctor-office', 'places-plans', 'Doctor office', 24),
  p('pl-dentist-office', 'places-plans', 'Dentist office', 25),
  p('pl-pharmacy', 'places-plans', 'Pharmacy', 26),
  p('pl-grocery-store', 'places-plans', 'Grocery store', 27),
  p('pl-mall', 'places-plans', 'Mall', 28),
  p('pl-pet-store', 'places-plans', 'Pet store', 29),
  p('pl-toy-store', 'places-plans', 'Toy store', 30),
  p('pl-movie-theater', 'places-plans', 'Movie theater', 31),
  p('pl-bowling-alley', 'places-plans', 'Bowling alley', 32),
  p('pl-arcade', 'places-plans', 'Arcade', 33),
  p('pl-beach', 'places-plans', 'Beach', 34),
  p('pl-lake', 'places-plans', 'Lake', 35),
  p('pl-mountain', 'places-plans', 'Mountain', 36),
  p('pl-forest', 'places-plans', 'Forest', 37),
  p('pl-camp', 'places-plans', 'Camp', 38),
  p('pl-zoo', 'places-plans', 'Zoo', 39),
  p('pl-aquarium', 'places-plans', 'Aquarium', 40),
  p('pl-museum', 'places-plans', 'Museum', 41),
  p('pl-farm', 'places-plans', 'Farm', 42),
  p('pl-church', 'places-plans', 'Church', 43),
  p('pl-temple', 'places-plans', 'Temple', 44),
  p('pl-mosque', 'places-plans', 'Mosque', 45),
  p('pl-synagogue', 'places-plans', 'Synagogue', 46),
  p('pl-bus-stop', 'places-plans', 'Bus stop', 47),
  p('pl-train-station', 'places-plans', 'Train station', 48),
  p('pl-airport', 'places-plans', 'Airport', 49),

  // School / Work
  p('sw-class', 'school-work', 'Class', 0),
  p('sw-homework', 'school-work', 'Homework', 1),
  p('sw-computer', 'school-work', 'Computer', 2),
  p('sw-book', 'school-work', 'Book', 3),
  p('sw-pencil', 'school-work', 'Pencil', 4),
  p('sw-question', 'school-work', 'I have a question', 5),
  p('sw-finished', 'school-work', "I'm finished", 6),
  p('sw-help', 'school-work', 'I need help with this', 7),
  p('sw-paper', 'school-work', 'Paper', 8),
  p('sw-table', 'school-work', 'Table', 9),
  p('sw-chair', 'school-work', 'Chair', 10),
  p('sw-art', 'school-work', 'Art', 11),
  p('sw-music', 'school-work', 'Music', 12),
  p('sw-recess', 'school-work', 'Recess', 13),
  p('sw-backpack', 'school-work', 'Backpack', 14),
  p('sw-lunchbox', 'school-work', 'Lunchbox', 15),
  p('sw-folder', 'school-work', 'Folder', 16),
  p('sw-notebook', 'school-work', 'Notebook', 17),
  p('sw-crayons', 'school-work', 'Crayons', 18),
  p('sw-markers', 'school-work', 'Markers', 19),
  p('sw-scissors', 'school-work', 'Scissors', 20),
  p('sw-glue', 'school-work', 'Glue', 21),
  p('sw-tape', 'school-work', 'Tape', 22),
  p('sw-eraser', 'school-work', 'Eraser', 23),
  p('sw-ruler', 'school-work', 'Ruler', 24),
  p('sw-whiteboard', 'school-work', 'Whiteboard', 25),
  p('sw-smart-board', 'school-work', 'Smart board', 26),
  p('sw-projector', 'school-work', 'Projector', 27),
  p('sw-math', 'school-work', 'Math', 28),
  p('sw-reading', 'school-work', 'Reading', 29),
  p('sw-writing', 'school-work', 'Writing', 30),
  p('sw-spelling', 'school-work', 'Spelling', 31),
  p('sw-science', 'school-work', 'Science', 32),
  p('sw-social-studies', 'school-work', 'Social studies', 33),
  p('sw-history', 'school-work', 'History', 34),
  p('sw-pe', 'school-work', 'PE', 35),
  p('sw-gym', 'school-work', 'Gym', 36),
  p('sw-recess-time', 'school-work', 'Recess time', 37),
  p('sw-library-time', 'school-work', 'Library time', 38),
  p('sw-story-time', 'school-work', 'Story time', 39),
  p('sw-circle-time', 'school-work', 'Circle time', 40),
  p('sw-lunch-time', 'school-work', 'Lunch time', 41),
  p('sw-snack-time', 'school-work', 'Snack time', 42),
  p('sw-worksheet', 'school-work', 'Worksheet', 43),
  p('sw-quiz', 'school-work', 'Quiz', 44),
  p('sw-test', 'school-work', 'Test', 45),
  p('sw-project', 'school-work', 'Project', 46),
  p('sw-field-trip', 'school-work', 'Field trip', 47),
  p('sw-assembly', 'school-work', 'Assembly', 48),
  p('sw-bus-ride', 'school-work', 'Bus ride', 49),

  // Health / Body
  p('hb-head', 'health-body', 'Head', 0),
  p('hb-tummy', 'health-body', 'Tummy', 1),
  p('hb-hand', 'health-body', 'Hand', 2),
  p('hb-foot', 'health-body', 'Foot', 3),
  p('hb-eye', 'health-body', 'Eye', 4),
  p('hb-ear', 'health-body', 'Ear', 5),
  p('hb-mouth', 'health-body', 'Mouth', 6),
  p('hb-nose', 'health-body', 'Nose', 7),
  p('hb-hurts', 'health-body', 'It hurts', 8),
  p('hb-sick', 'health-body', 'I feel sick', 9),
  p('hb-medicine', 'health-body', 'Medicine', 10),
  p('hb-teeth', 'health-body', 'Teeth', 11),
  p('hb-back', 'health-body', 'Back', 12),
  p('hb-arm', 'health-body', 'Arm', 13),
  p('hb-hair', 'health-body', 'Hair', 14),
  p('hb-face', 'health-body', 'Face', 15),
  p('hb-forehead', 'health-body', 'Forehead', 16),
  p('hb-cheek', 'health-body', 'Cheek', 17),
  p('hb-chin', 'health-body', 'Chin', 18),
  p('hb-lips', 'health-body', 'Lips', 19),
  p('hb-tongue', 'health-body', 'Tongue', 20),
  p('hb-throat', 'health-body', 'Throat', 21),
  p('hb-neck', 'health-body', 'Neck', 22),
  p('hb-shoulder', 'health-body', 'Shoulder', 23),
  p('hb-elbow', 'health-body', 'Elbow', 24),
  p('hb-wrist', 'health-body', 'Wrist', 25),
  p('hb-finger', 'health-body', 'Finger', 26),
  p('hb-thumb', 'health-body', 'Thumb', 27),
  p('hb-knuckle', 'health-body', 'Knuckle', 28),
  p('hb-knee', 'health-body', 'Knee', 29),
  p('hb-ankle', 'health-body', 'Ankle', 30),
  p('hb-toe', 'health-body', 'Toe', 31),
  p('hb-heel', 'health-body', 'Heel', 32),
  p('hb-chest', 'health-body', 'Chest', 33),
  p('hb-belly', 'health-body', 'Belly', 34),
  p('hb-hip', 'health-body', 'Hip', 35),
  p('hb-bottom', 'health-body', 'Bottom', 36),
  p('hb-skin', 'health-body', 'Skin', 37),
  p('hb-bone', 'health-body', 'Bone', 38),
  p('hb-muscle', 'health-body', 'Muscle', 39),
  p('hb-headache', 'health-body', 'Headache', 40),
  p('hb-stomachache', 'health-body', 'Stomachache', 41),
  p('hb-earache', 'health-body', 'Earache', 42),
  p('hb-toothache', 'health-body', 'Toothache', 43),
  p('hb-sore-throat', 'health-body', 'Sore throat', 44),
  p('hb-cough', 'health-body', 'Cough', 45),
  p('hb-sneeze', 'health-body', 'Sneeze', 46),
  p('hb-runny-nose', 'health-body', 'Runny nose', 47),
  p('hb-stuffy-nose', 'health-body', 'Stuffy nose', 48),
  p('hb-fever', 'health-body', 'Fever', 49),
  p('hb-chills', 'health-body', 'Chills', 50),
  p('hb-shaking', 'health-body', 'Shaking', 51),
  p('hb-dizzy-spell', 'health-body', 'Dizzy spell', 52),
  p('hb-bruise', 'health-body', 'Bruise', 53),
  p('hb-cut', 'health-body', 'Cut', 54),
  p('hb-scrape', 'health-body', 'Scrape', 55),
  p('hb-bump', 'health-body', 'Bump', 56),
  p('hb-bandage', 'health-body', 'Bandage', 57),
  p('hb-itchy-spot', 'health-body', 'Itchy spot', 58),
  p('hb-rash', 'health-body', 'Rash', 59),
  p('hb-allergic-reaction', 'health-body', 'Allergic reaction', 60),
  p('hb-pain', 'health-body', 'Pain', 61),
  p('hb-sharp-pain', 'health-body', 'Sharp pain', 62),
  p('hb-dull-pain', 'health-body', 'Dull pain', 63),
  p('hb-burning', 'health-body', 'Burning', 64),
  p('hb-vitamins', 'health-body', 'Vitamins', 65),
  p('hb-inhaler', 'health-body', 'Inhaler', 66),
  p('hb-epipen', 'health-body', 'EpiPen', 67),
  p('hb-pill', 'health-body', 'Pill', 68),
  p('hb-drops', 'health-body', 'Drops', 69),
  p('hb-doctor-visit', 'health-body', 'Doctor visit', 70),
  p('hb-shot', 'health-body', 'Shot', 71),
  p('hb-x-ray', 'health-body', 'X-ray', 72),
  p('hb-check-up', 'health-body', 'Check-up', 73),
  p('hb-wash-my-hands', 'health-body', 'Wash my hands', 74),
  p('hb-brush-my-teeth', 'health-body', 'Brush my teeth', 75),

  // Time
  p('ti-now', 'time', 'Now', 0),
  p('ti-later', 'time', 'Later', 1),
  p('ti-today', 'time', 'Today', 2),
  p('ti-tomorrow', 'time', 'Tomorrow', 3),
  p('ti-yesterday', 'time', 'Yesterday', 4),
  p('ti-morning', 'time', 'Morning', 5),
  p('ti-afternoon', 'time', 'Afternoon', 6),
  p('ti-night', 'time', 'Night', 7),
  p('ti-before', 'time', 'Before', 8),
  p('ti-after', 'time', 'After', 9),
  p('ti-first', 'time', 'First', 10),
  p('ti-last', 'time', 'Last', 11),
  p('ti-right-now', 'time', 'Right now', 12),
  p('ti-in-a-minute', 'time', 'In a minute', 13),
  p('ti-soon', 'time', 'Soon', 14),
  p('ti-later-today', 'time', 'Later today', 15),
  p('ti-tonight', 'time', 'Tonight', 16),
  p('ti-this-morning', 'time', 'This morning', 17),
  p('ti-this-afternoon', 'time', 'This afternoon', 18),
  p('ti-this-evening', 'time', 'This evening', 19),
  p('ti-last-night', 'time', 'Last night', 20),
  p('ti-all-day', 'time', 'All day', 21),
  p('ti-all-night', 'time', 'All night', 22),
  p('ti-a-long-time', 'time', 'A long time', 23),
  p('ti-a-short-time', 'time', 'A short time', 24),
  p('ti-a-while-ago', 'time', 'A while ago', 25),
  p('ti-weekend', 'time', 'Weekend', 26),
  p('ti-weekday', 'time', 'Weekday', 27),
  p('ti-monday', 'time', 'Monday', 28),
  p('ti-tuesday', 'time', 'Tuesday', 29),
  p('ti-wednesday', 'time', 'Wednesday', 30),
  p('ti-thursday', 'time', 'Thursday', 31),
  p('ti-friday', 'time', 'Friday', 32),
  p('ti-saturday', 'time', 'Saturday', 33),
  p('ti-sunday', 'time', 'Sunday', 34),
  p('ti-birthday', 'time', 'Birthday', 35),
  p('ti-holiday', 'time', 'Holiday', 36),

  // Animals
  p('an-dog', 'animals', 'Dog', 0),
  p('an-cat', 'animals', 'Cat', 1),
  p('an-fish', 'animals', 'Fish', 2),
  p('an-bird', 'animals', 'Bird', 3),
  p('an-horse', 'animals', 'Horse', 4),
  p('an-cow', 'animals', 'Cow', 5),
  p('an-pig', 'animals', 'Pig', 6),
  p('an-rabbit', 'animals', 'Rabbit', 7),
  p('an-bear', 'animals', 'Bear', 8),
  p('an-elephant', 'animals', 'Elephant', 9),
  p('an-duck', 'animals', 'Duck', 10),
  p('an-butterfly', 'animals', 'Butterfly', 11),
  p('an-puppy', 'animals', 'Puppy', 12),
  p('an-kitten', 'animals', 'Kitten', 13),
  p('an-hamster', 'animals', 'Hamster', 14),
  p('an-guinea-pig', 'animals', 'Guinea pig', 15),
  p('an-turtle', 'animals', 'Turtle', 16),
  p('an-frog', 'animals', 'Frog', 17),
  p('an-snake', 'animals', 'Snake', 18),
  p('an-lizard', 'animals', 'Lizard', 19),
  p('an-spider', 'animals', 'Spider', 20),
  p('an-bug', 'animals', 'Bug', 21),
  p('an-bee', 'animals', 'Bee', 22),
  p('an-ant', 'animals', 'Ant', 23),
  p('an-lion', 'animals', 'Lion', 24),
  p('an-tiger', 'animals', 'Tiger', 25),
  p('an-monkey', 'animals', 'Monkey', 26),
  p('an-giraffe', 'animals', 'Giraffe', 27),
  p('an-zebra', 'animals', 'Zebra', 28),
  p('an-hippo', 'animals', 'Hippo', 29),
  p('an-penguin', 'animals', 'Penguin', 30),
  p('an-owl', 'animals', 'Owl', 31),
  p('an-eagle', 'animals', 'Eagle', 32),
  p('an-parrot', 'animals', 'Parrot', 33),
  p('an-chicken', 'animals', 'Chicken', 34),
  p('an-rooster', 'animals', 'Rooster', 35),
  p('an-sheep', 'animals', 'Sheep', 36),
  p('an-goat', 'animals', 'Goat', 37),
  p('an-donkey', 'animals', 'Donkey', 38),
  p('an-dolphin', 'animals', 'Dolphin', 39),
  p('an-whale', 'animals', 'Whale', 40),
  p('an-shark', 'animals', 'Shark', 41),
  p('an-octopus', 'animals', 'Octopus', 42),
  p('an-crab', 'animals', 'Crab', 43),
  p('an-starfish', 'animals', 'Starfish', 44),
  p('an-my-pet', 'animals', 'My pet', 45),
  p('an-my-dog', 'animals', 'My dog', 46),
  p('an-my-cat', 'animals', 'My cat', 47),

  // Colors
  p('co-red', 'colors', 'Red', 0),
  p('co-blue', 'colors', 'Blue', 1),
  p('co-green', 'colors', 'Green', 2),
  p('co-yellow', 'colors', 'Yellow', 3),
  p('co-orange', 'colors', 'Orange', 4),
  p('co-purple', 'colors', 'Purple', 5),
  p('co-pink', 'colors', 'Pink', 6),
  p('co-black', 'colors', 'Black', 7),
  p('co-white', 'colors', 'White', 8),
  p('co-brown', 'colors', 'Brown', 9),
  p('co-gray', 'colors', 'Gray', 10),
  p('co-silver', 'colors', 'Silver', 11),
  p('co-gold', 'colors', 'Gold', 12),
  p('co-beige', 'colors', 'Beige', 13),
  p('co-tan', 'colors', 'Tan', 14),
  p('co-light-blue', 'colors', 'Light blue', 15),
  p('co-dark-blue', 'colors', 'Dark blue', 16),
  p('co-light-green', 'colors', 'Light green', 17),
  p('co-dark-green', 'colors', 'Dark green', 18),
  p('co-light-pink', 'colors', 'Light pink', 19),
  p('co-hot-pink', 'colors', 'Hot pink', 20),
  p('co-rainbow', 'colors', 'Rainbow', 21),
  p('co-my-favorite-color', 'colors', 'My favorite color', 22),

  // Clothes
  p('cl-shirt', 'clothes', 'Shirt', 0),
  p('cl-pants', 'clothes', 'Pants', 1),
  p('cl-shoes', 'clothes', 'Shoes', 2),
  p('cl-socks', 'clothes', 'Socks', 3),
  p('cl-jacket', 'clothes', 'Jacket', 4),
  p('cl-hat', 'clothes', 'Hat', 5),
  p('cl-dress', 'clothes', 'Dress', 6),
  p('cl-pajamas', 'clothes', 'Pajamas', 7),
  p('cl-underwear', 'clothes', 'Underwear', 8),
  p('cl-boots', 'clothes', 'Boots', 9),
  p('cl-t-shirt', 'clothes', 'T-shirt', 10),
  p('cl-sweater', 'clothes', 'Sweater', 11),
  p('cl-sweatshirt', 'clothes', 'Sweatshirt', 12),
  p('cl-hoodie', 'clothes', 'Hoodie', 13),
  p('cl-coat', 'clothes', 'Coat', 14),
  p('cl-shorts', 'clothes', 'Shorts', 15),
  p('cl-skirt', 'clothes', 'Skirt', 16),
  p('cl-leggings', 'clothes', 'Leggings', 17),
  p('cl-sandals', 'clothes', 'Sandals', 18),
  p('cl-sneakers', 'clothes', 'Sneakers', 19),
  p('cl-mittens', 'clothes', 'Mittens', 20),
  p('cl-gloves', 'clothes', 'Gloves', 21),
  p('cl-scarf', 'clothes', 'Scarf', 22),
  p('cl-belt', 'clothes', 'Belt', 23),
  p('cl-backpack', 'clothes', 'Backpack', 24),
  p('cl-helmet', 'clothes', 'Helmet', 25),
  p('cl-glasses', 'clothes', 'Glasses', 26),
  p('cl-sunglasses', 'clothes', 'Sunglasses', 27),
  p('cl-diaper', 'clothes', 'Diaper', 28),
  p('cl-pull-up', 'clothes', 'Pull-up', 29),

  // Transportation
  p('tr-car', 'transport', 'Car', 0),
  p('tr-bus', 'transport', 'Bus', 1),
  p('tr-train', 'transport', 'Train', 2),
  p('tr-airplane', 'transport', 'Airplane', 3),
  p('tr-bike', 'transport', 'Bike', 4),
  p('tr-truck', 'transport', 'Truck', 5),
  p('tr-boat', 'transport', 'Boat', 6),
  p('tr-walk', 'transport', 'Walk', 7),
  p('tr-wheelchair', 'transport', 'Wheelchair', 8),
  p('tr-scooter', 'transport', 'Scooter', 9),
  p('tr-stroller', 'transport', 'Stroller', 10),
  p('tr-tricycle', 'transport', 'Tricycle', 11),
  p('tr-skateboard', 'transport', 'Skateboard', 12),
  p('tr-roller-skates', 'transport', 'Roller skates', 13),
  p('tr-subway', 'transport', 'Subway', 14),
  p('tr-taxi', 'transport', 'Taxi', 15),
  p('tr-helicopter', 'transport', 'Helicopter', 16),
  p('tr-rocket', 'transport', 'Rocket', 17),
  p('tr-tractor', 'transport', 'Tractor', 18),
  p('tr-fire-truck', 'transport', 'Fire truck', 19),
  p('tr-police-car', 'transport', 'Police car', 20),
  p('tr-ambulance', 'transport', 'Ambulance', 21),
  p('tr-ferry', 'transport', 'Ferry', 22),
  p('tr-sled', 'transport', 'Sled', 23),
  p('tr-drive', 'transport', 'Drive', 24),
  p('tr-ride', 'transport', 'Ride', 25),

  // Weather
  p('we-sunny', 'weather', 'Sunny', 0),
  p('we-rainy', 'weather', 'Rainy', 1),
  p('we-cloudy', 'weather', 'Cloudy', 2),
  p('we-snowy', 'weather', 'Snowy', 3),
  p('we-windy', 'weather', 'Windy', 4),
  p('we-hot', 'weather', 'Hot', 5),
  p('we-cold', 'weather', 'Cold', 6),
  p('we-storm', 'weather', 'Storm', 7),
  p('we-foggy', 'weather', 'Foggy', 8),
  p('we-rainbow', 'weather', 'Rainbow', 9),
  p('we-lightning', 'weather', 'Lightning', 10),
  p('we-thunder', 'weather', 'Thunder', 11),
  p('we-tornado', 'weather', 'Tornado', 12),
  p('we-hurricane', 'weather', 'Hurricane', 13),
  p('we-earthquake', 'weather', 'Earthquake', 14),
  p('we-warm-out', 'weather', 'Warm out', 15),
  p('we-cool-out', 'weather', 'Cool out', 16),
  p('we-freezing', 'weather', 'Freezing', 17),
  p('we-wear-a-coat', 'weather', 'Wear a coat', 18),
  p('we-wear-shorts', 'weather', 'Wear shorts', 19),

  // Toys & Fun
  p('tf-ball', 'toys-fun', 'Ball', 0),
  p('tf-blocks', 'toys-fun', 'Blocks', 1),
  p('tf-doll', 'toys-fun', 'Doll', 2),
  p('tf-puzzle', 'toys-fun', 'Puzzle', 3),
  p('tf-game', 'toys-fun', 'Game', 4),
  p('tf-movie', 'toys-fun', 'Movie', 5),
  p('tf-music', 'toys-fun', 'Music', 6),
  p('tf-bubbles', 'toys-fun', 'Bubbles', 7),
  p('tf-swing', 'toys-fun', 'Swing', 8),
  p('tf-slide', 'toys-fun', 'Slide', 9),
  p('tf-coloring', 'toys-fun', 'Coloring', 10),
  p('tf-tablet', 'toys-fun', 'Tablet', 11),
  p('tf-stuffed-animal', 'toys-fun', 'Stuffed animal', 12),
  p('tf-action-figure', 'toys-fun', 'Action figure', 13),
  p('tf-lego', 'toys-fun', 'Lego', 14),
  p('tf-train-set', 'toys-fun', 'Train set', 15),
  p('tf-card-game', 'toys-fun', 'Card game', 16),
  p('tf-board-game', 'toys-fun', 'Board game', 17),
  p('tf-video-game', 'toys-fun', 'Video game', 18),
  p('tf-crayons', 'toys-fun', 'Crayons', 19),
  p('tf-stickers', 'toys-fun', 'Stickers', 20),
  p('tf-sandbox', 'toys-fun', 'Sandbox', 21),
  p('tf-trampoline', 'toys-fun', 'Trampoline', 22),
  p('tf-sprinkler', 'toys-fun', 'Sprinkler', 23),
  p('tf-story', 'toys-fun', 'Story', 24),
  p('tf-song', 'toys-fun', 'Song', 25),
  p('tf-cartoon', 'toys-fun', 'Cartoon', 26),

];
