import type { SupportedLanguage } from '@/engine/i18n';
import type { SceneType } from '@/services/sceneInference';

type VisionPhraseMap = Partial<Record<SceneType, Partial<Record<SupportedLanguage, string[]>>>>;

export const VISION_PHRASES: VisionPhraseMap = {
  mealtime: {
    en: ['I want more', 'Water please', 'All done', 'Yummy', 'Too hot', "I don't like it", 'More please', "I'm hungry"],
    bn: ['আমি আরও চাই', 'জল দাও', 'সব শেষ', 'মজার', 'খুব গরম', 'আমার ভালো লাগছে না', 'আরও দাও', 'আমার খিদে পেয়েছে'],
    sw: ['Nataka ingine', 'Maji tafadhali', 'Nimetimiza', 'Tamu!', 'Ni moto sana', 'Sipendi', 'Ongeza tafadhali', 'Nina njaa'],
    am: ['ተጨማሪ እፈልጋለሁ', 'ውሃ እባክዎን', 'ጨርሻለሁ', 'ይጣፍጣል', 'በጣም ይሞቃል', 'አልወደድኩትም', 'ተጨማሪ እባክዎን', 'ራበኝ'],
    es: ['Quiero más', 'Agua por favor', 'Ya terminé', 'Rico', 'Muy caliente', 'No me gusta', 'Más por favor', 'Tengo hambre'],
    fr: ['Je veux encore', "De l'eau s'il vous plaît", "J'ai fini", 'Miam', 'Trop chaud', "Je n'aime pas", "Encore s'il vous plaît", "J'ai faim"],
    pt: ['Quero mais', 'Água por favor', 'Acabei', 'Gostoso', 'Muito quente', 'Não gosto', 'Mais por favor', 'Estou com fome'],
    ro: ['Mai vreau', 'Apă te rog', 'Gata', 'Delicios', 'Prea cald', 'Nu-mi place', 'Mai te rog', 'Mi-e foame'],
    uk: ['Хочу ще', 'Води будь ласка', 'Все', 'Смачно', 'Гаряче', 'Не подобається', 'Ще будь ласка', 'Хочу їсти'],
    ru: ['Хочу ещё', 'Воды пожалуйста', 'Всё', 'Вкусно', 'Горячо', 'Не нравится', 'Ещё пожалуйста', 'Хочу есть'],
    de: ['Ich will mehr', 'Wasser bitte', 'Fertig', 'Lecker', 'Zu heiß', 'Mag ich nicht', 'Mehr bitte', 'Ich habe Hunger'],
    ja: ['もっとほしい', 'お水ください', 'おしまい', 'おいしい', 'あつい', 'すきじゃない', 'もっとください', 'おなかすいた'],
    ko: ['더 주세요', '물 주세요', '다 먹었어요', '맛있어요', '뜨거워요', '싫어요', '더요', '배고파요'],
    zh: ['我还要', '请给我水', '吃完了', '好吃', '太烫了', '我不喜欢', '再来一点', '我饿了'],
    ar: ['أريد المزيد', 'ماء من فضلك', 'انتهيت', 'لذيذ', 'ساخن جداً', 'لا أحبه', 'المزيد من فضلك', 'أنا جائع'],
    hi: ['और चाहिए', 'पानी दो', 'हो गया', 'स्वादिष्ट', 'बहुत गरम', 'पसंद नहीं', 'और दो', 'भूख लगी'],
    it: ['Ne voglio ancora', 'Acqua per favore', 'Ho finito', 'Buono', 'Troppo caldo', 'Non mi piace', 'Ancora per favore', 'Ho fame'],
    pl: ['Chcę więcej', 'Wodę proszę', 'Skończyłem', 'Pyszne', 'Za gorące', 'Nie lubię', 'Więcej proszę', 'Jestem głodny'],
    he: ['אני רוצה עוד', 'מים בבקשה', 'סיימתי', 'טעים', 'חם מדי', 'אני לא אוהב', 'עוד בבקשה', 'אני רעב'],
    nl: ['Ik wil meer', 'Water alsjeblieft', 'Klaar', 'Lekker', 'Te heet', 'Lust ik niet', 'Meer alsjeblieft', 'Ik heb honger'],
    vi: ['Con muốn thêm', 'Cho con nước', 'Con ăn xong rồi', 'Ngon', 'Nóng quá', 'Con không thích', 'Thêm nữa', 'Con đói'],
    tl: ['Gusto ko pa', 'Tubig po', 'Tapos na', 'Masarap', 'Mainit', 'Ayaw ko', 'Pa po', 'Gutom na ako'],
    tr: ['Daha istiyorum', 'Su lütfen', 'Bittim', 'Lezzetli', 'Çok sıcak', 'Sevmiyorum', 'Daha lütfen', 'Acıktım'],
    id: ['Mau lagi', 'Air dong', 'Sudah selesai', 'Enak', 'Kepanasan', 'Tidak suka', 'Lagi dong', 'Lapar'],
    bg: ['Искам още', 'Вода моля', 'Готово', 'Вкусно', 'Горещо', 'Не ми харесва', 'Още моля', 'Гладен съм'],
  },
  bedtime: {
    en: ["I'm tired", 'Good night', 'Read a story', 'Water please', "I can't sleep", 'Hug please', 'Scared', 'Light on'],
    bn: ['আমার ক্লান্তি লাগছে', 'শুভ রাত্রি', 'গল্প বলো', 'জল দাও', 'ঘুম আসছে না', 'জড়িয়ে ধরো', 'ভয় করছে', 'আলো জ্বালো'],
    sw: ['Nimechoka', 'Usiku mwema', 'Soma hadithi', 'Maji tafadhali', 'Sipati Usingizi', 'Nikumbatie tafadhali', 'Nina hofu', 'Washa taa'],
    am: ['ደክሞኛል', 'ደህና እደር', 'ታሪክ አንብብልኝ', 'ውሃ እባክዎን', 'እንቅልፍ እምቢ አለኝ', 'እቀፈኝ እባክዎን', 'ፈርቻለሁ', 'መብራቱን አብራ'],
    es: ['Tengo sueño', 'Buenas noches', 'Lee un cuento', 'Agua por favor', 'No puedo dormir', 'Abrazo por favor', 'Tengo miedo', 'Prende la luz'],
    fr: ["J'ai sommeil", 'Bonne nuit', 'Lis une histoire', "De l'eau", 'Je ne peux pas dormir', 'Câlin', "J'ai peur", 'Lumière'],
    pt: ['Estou com sono', 'Boa noite', 'Leia uma história', 'Água por favor', 'Não consigo dormir', 'Abraço', 'Com medo', 'Acende a luz'],
    ro: ['Mi-e somn', 'Noapte bună', 'Citește o poveste', 'Apă te rog', 'Nu pot dormi', 'Îmbrățișare', 'Mi-e frică', 'Lumina'],
    ru: ['Хочу спать', 'Спокойной ночи', 'Почитай сказку', 'Воды', 'Не могу уснуть', 'Обними', 'Страшно', 'Включи свет'],
    uk: ['Хочу спати', 'Добраніч', 'Почитай казку', 'Води', 'Не можу заснути', 'Обійми', 'Страшно', 'Увімкни світло'],
    de: ['Ich bin müde', 'Gute Nacht', 'Lies eine Geschichte', 'Wasser bitte', 'Kann nicht schlafen', 'Umarmung', 'Angst', 'Licht an'],
    ja: ['ねむい', 'おやすみ', 'おはなしよんで', 'おみずください', 'ねれない', 'だっこ', 'こわい', 'でんきつけて'],
    ko: ['졸려요', '잘 자요', '이야기 읽어주세요', '물 주세요', '잠이 안 와요', '안아주세요', '무서워요', '불 켜주세요'],
    zh: ['我困了', '晚安', '讲故事', '要喝水', '睡不着', '抱抱', '害怕', '开灯'],
    ar: ['أنا نعسان', 'تصبح على خير', 'اقرأ قصة', 'ماء', 'لا أستطيع النوم', 'عناق', 'خائف', 'أضئ النور'],
  },
  playtime: {
    en: ['I want to play', 'My turn', 'Fun!', 'Again!', 'Help me', 'I won', 'Your turn', "Let's play"],
    bn: ['আমি খেলতে চাই', 'আমার পালা', 'মজা!', 'আবার!', 'আমাকে সাহায্য করো', 'আমি জিতেছি', 'তোমার পালা', 'চলো খেলি'],
    sw: ['Nataka kucheza', 'Lamu yangu', 'Raha!', 'Tena!', 'Nisaidie', 'Nimeshinda', 'Zamu yako', 'Tucheze'],
    am: ['መጫወት እፈልጋለሁ', 'የእኔ ተራ', 'ደስ ይላል!', 'ድጋሚ!', 'እርዳኝ', 'አሸነፍኩ', 'የአንተ ተራ', 'እንጫወት'],
    es: ['Quiero jugar', 'Mi turno', '¡Divertido!', '¡Otra vez!', 'Ayúdame', 'Gané', 'Tu turno', 'Juguemos'],
    fr: ['Je veux jouer', 'Mon tour', 'Amusant !', 'Encore !', 'Aide-moi', "J'ai gagné", 'Ton tour', 'Jouons'],
    pt: ['Quero brincar', 'Minha vez', 'Divertido!', 'De novo!', 'Me ajuda', 'Ganhei', 'Sua vez', 'Vamos brincar'],
    ro: ['Vreau să mă joc', 'Rândul meu', 'Distractiv!', 'Încă o dată!', 'Ajută-mă', 'Am câștigat', 'Rândul tău', 'Hai să ne jucăm'],
    ru: ['Хочу играть', 'Моя очередь', 'Весело!', 'Ещё раз!', 'Помоги', 'Я выиграл', 'Твоя очередь', 'Давай играть'],
    uk: ['Хочу грати', 'Моя черга', 'Весело!', 'Ще раз!', 'Допоможи', 'Я виграв', 'Твоя черга', 'Давай грати'],
    de: ['Ich will spielen', 'Ich bin dran', 'Spaß!', 'Nochmal!', 'Hilf mir', 'Ich habe gewonnen', 'Du bist dran', 'Lass uns spielen'],
    ja: ['あそびたい', 'ぼくのばん', 'たのしい！', 'もういっかい！', 'てつだって', 'かった', 'きみのばん', 'あそぼう'],
    ko: ['놀고 싶어요', '내 차례', '재미있어요!', '한 번 더!', '도와주세요', '내가 이겼어', '네 차례', '같이 놀자'],
    zh: ['我要玩', '轮到我了', '好玩！', '再来一次！', '帮帮我', '我赢了', '轮到你了', '我们一起玩'],
    ar: ['أريد أن ألعب', 'دوري', 'ممتع!', 'مرة أخرى!', 'ساعدني', 'فزت', 'دورك', 'هيا نلعب'],
  },
  schoolwork: {
    en: ['Help please', "I don't understand", 'Done', 'What is this?', 'Too hard', 'I need a break', 'Read it again', 'More time'],
    bn: ['সাহায্য করো', 'বুঝতে পারছি না', 'শেষ', 'এটা কী?', 'খুব কঠিন', 'একটু জিরোনো দরকার', 'আবার পড়ো', 'আরও সময় চাই'],
    sw: ['Msaada tafadhali', 'Sielewi', 'Tayari', 'Hii ni nini?', 'Ngumu sana', 'Nahitaji mapumziko', 'Soma tena', 'Muda zaidi'],
    am: ['እርዳታ እባክዎን', 'አልገባኝም', 'ጨረስኩ', 'ይህ ምንድን ነው?', 'በጣም ይከብዳል', 'ዕረፍት እፈልጋለሁ', 'ድጋሚ አንብበው', 'ተጨማሪ ጊዜ'],
    es: ['Ayuda por favor', 'No entiendo', 'Listo', '¿Qué es esto?', 'Muy difícil', 'Necesito un descanso', 'Léelo otra vez', 'Más tiempo'],
    fr: ["Aide s'il vous plaît", 'Je ne comprends pas', 'Fini', "Qu'est-ce que c'est ?", 'Trop difficile', "J'ai besoin d'une pause", 'Relis', 'Plus de temps'],
    pt: ['Ajuda por favor', 'Não entendo', 'Pronto', 'O que é isso?', 'Muito difícil', 'Preciso de uma pausa', 'Leia de novo', 'Mais tempo'],
    ro: ['Ajutor te rog', 'Nu înțeleg', 'Gata', 'Ce este asta?', 'Prea greu', 'Am nevoie de pauză', 'Citește din nou', 'Mai mult timp'],
    ru: ['Помогите', 'Не понимаю', 'Готово', 'Что это?', 'Слишком сложно', 'Нужен перерыв', 'Прочитай ещё раз', 'Ещё время'],
    uk: ['Допоможіть', 'Не розумію', 'Готово', 'Що це?', 'Занадто складно', 'Потрібна перерва', 'Прочитай ще раз', 'Ще час'],
    de: ['Hilfe bitte', 'Ich verstehe nicht', 'Fertig', 'Was ist das?', 'Zu schwer', 'Ich brauche eine Pause', 'Nochmal lesen', 'Mehr Zeit'],
    ja: ['たすけて', 'わからない', 'できた', 'これなに？', 'むずかしい', 'やすみたい', 'もういちどよんで', 'もうすこし'],
    ko: ['도와주세요', '모르겠어요', '다 했어요', '이게 뭐예요?', '너무 어려워요', '쉬고 싶어요', '다시 읽어주세요', '시간 더요'],
    zh: ['帮帮我', '我不懂', '做完了', '这是什么？', '太难了', '我想休息', '再读一遍', '再给我点时间'],
    ar: ['مساعدة من فضلك', 'لا أفهم', 'انتهيت', 'ما هذا؟', 'صعب جداً', 'أحتاج استراحة', 'اقرأه مرة أخرى', 'وقت أكثر'],
  },
  bathtime: {
    en: ['I need to go', 'Wash hands', 'All done', 'Help me', 'Cold water', 'Hot water', 'Towel please', 'I need help'],
    bn: ['বাথরুম পাবো', 'হাত ধোওয়া', 'সব শেষ', 'আমাকে সাহায্য করো', 'ঠান্ডা জল', 'গরম জল', 'তোয়ালে দাও', 'সাহায্য লাগবে'],
    sw: ['Nahitaji kwenda', 'Osha mikono', 'Nimetimiza', 'Nisaidie', 'Maji ya baridi', 'Maji ya moto', 'Taulo tafadhali', 'Nahitaji msaada'],
    am: ['ሽናት መጣብኝ', 'እጅ መታጠብ', 'ጨርሻለሁ', 'እርዳኝ', 'ቀዝቃዛ ውሃ', 'ትኩስ ውሃ', 'ፎጣ እባክዎን', 'እርዳታ እፈልጋለሁ'],
    es: ['Necesito ir', 'Lavar manos', 'Ya terminé', 'Ayúdame', 'Agua fría', 'Agua caliente', 'Toalla por favor', 'Necesito ayuda'],
    fr: ['Je dois y aller', 'Laver les mains', "C'est fini", 'Aide-moi', 'Eau froide', 'Eau chaude', 'Serviette', "J'ai besoin d'aide"],
    pt: ['Preciso ir', 'Lavar as mãos', 'Acabei', 'Me ajuda', 'Água fria', 'Água quente', 'Toalha por favor', 'Preciso de ajuda'],
    ro: ['Trebuie să merg', 'Spală mâinile', 'Gata', 'Ajută-mă', 'Apă rece', 'Apă caldă', 'Prosop te rog', 'Am nevoie de ajutor'],
    ru: ['Мне нужно в туалет', 'Помыть руки', 'Всё', 'Помоги', 'Холодная вода', 'Горячая вода', 'Полотенце', 'Нужна помощь'],
    uk: ['Мені треба', 'Помити руки', 'Все', 'Допоможи', 'Холодна вода', 'Гаряча вода', 'Рушник будь ласка', 'Потрібна допомога'],
    de: ['Ich muss aufs Klo', 'Hände waschen', 'Fertig', 'Hilf mir', 'Kaltes Wasser', 'Warmes Wasser', 'Handtuch bitte', 'Ich brauche Hilfe'],
    ja: ['トイレいきたい', 'てをあらう', 'おわり', 'てつだって', 'つめたいみず', 'あついみず', 'タオルください', 'たすけて'],
    ko: ['화장실 가고 싶어요', '손 씻을래요', '다 했어요', '도와주세요', '찬물', '뜨거운 물', '수건 주세요', '도움이 필요해요'],
    zh: ['我要上厕所', '洗手', '好了', '帮帮我', '冷水', '热水', '毛巾', '我需要帮助'],
    ar: ['أريد الذهاب', 'غسل اليدين', 'انتهيت', 'ساعدني', 'ماء بارد', 'ماء ساخن', 'منشفة من فضلك', 'أحتاج مساعدة'],
  },
  watching_tv: {
    en: ['I want to watch', 'Turn it off', 'Too loud', 'Change it', 'I like this', 'Boring', 'Again', 'Pause'],
    bn: ['আমি দেখতে চাই', 'বন্ধ করো', 'খুব আওয়াজ', 'বদলে দাও', 'এটা ভালো লাগছে', 'একঘেয়ে', 'আবার', 'থামাও'],
    sw: ['Nataka kutazama', 'Zima', 'Sauti kubwa', 'Badilisha', 'Napenda hii', 'Inaboa', 'Tena', 'Simamisha'],
    am: ['ማየት እፈልጋለሁ', 'አጥፋው', 'ድምፁ ጨመረ', 'ቀይረው', 'ይህን ወድጄዋለሁ', 'ያሰለቻል', 'ድጋሚ', 'አቁመው'],
    es: ['Quiero ver', 'Apágalo', 'Muy fuerte', 'Cambia', 'Me gusta', 'Aburrido', 'Otra vez', 'Pausa'],
    fr: ['Je veux regarder', 'Éteins', 'Trop fort', 'Change', "J'aime bien", 'Ennuyeux', 'Encore', 'Pause'],
    pt: ['Quero assistir', 'Desliga', 'Muito alto', 'Muda', 'Eu gosto', 'Chato', 'De novo', 'Pausa'],
    ro: ['Vreau să mă uit', 'Oprește', 'Prea tare', 'Schimbă', 'Îmi place', 'Plictisitor', 'Încă o dată', 'Pauză'],
    ru: ['Хочу смотреть', 'Выключи', 'Слишком громко', 'Переключи', 'Мне нравится', 'Скучно', 'Ещё раз', 'Пауза'],
    uk: ['Хочу дивитися', 'Вимкни', 'Занадто гучно', 'Переключи', 'Мені подобається', 'Нудно', 'Ще раз', 'Пауза'],
    de: ['Ich will gucken', 'Mach aus', 'Zu laut', 'Umschalten', 'Gefällt mir', 'Langweilig', 'Nochmal', 'Pause'],
    ja: ['みたい', 'けして', 'うるさい', 'かえて', 'すき', 'つまんない', 'もういっかい', 'とめて'],
    ko: ['보고 싶어요', '꺼주세요', '너무 시끄러워요', '바꿔주세요', '좋아요', '지루해요', '다시', '멈춰'],
    zh: ['我要看', '关掉', '太吵了', '换一个', '我喜欢', '无聊', '再看一遍', '暂停'],
    ar: ['أريد أن أشاهد', 'أطفئه', 'صوت عالي', 'غيّره', 'يعجبني', 'ممل', 'مرة أخرى', 'إيقاف مؤقت'],
  },
  snacktime: {
    en: ['Snack please', "I'm thirsty", 'Juice please', 'Cookie', 'Fruit', 'More', 'All done', 'Yummy'],
    bn: ['টিফিন দাও', 'আমার চেষ্টা পেয়েছে', 'জুস দাও', 'বিস্কুট', 'ফল', 'আরও', 'সব শেষ', 'মজার'],
    sw: ['Kitafunio tafadhali', 'Nina kiu', 'Juisi tafadhali', 'Biskuti', 'Matunda', 'Tena', 'Nimetimiza', 'Tamu!'],
    am: ['መክሰስ እባክዎን', 'ጠማኝ', 'ጁስ እባክዎን', 'ኩኪስ', 'ፍራፍሬ', 'ተጨማሪ', 'ጨርሻለሁ', 'ይጣፍጣል'],
    es: ['Merienda por favor', 'Tengo sed', 'Jugo por favor', 'Galleta', 'Fruta', 'Más', 'Ya terminé', 'Rico'],
    fr: ['Goûter', "J'ai soif", 'Jus', 'Biscuit', 'Fruit', 'Encore', 'Fini', 'Miam'],
    pt: ['Lanche', 'Estou com sede', 'Suco', 'Biscoito', 'Fruta', 'Mais', 'Acabei', 'Gostoso'],
    ro: ['Gustare', 'Mi-e sete', 'Suc te rog', 'Biscuit', 'Fruct', 'Mai', 'Gata', 'Delicios'],
    ru: ['Перекус', 'Хочу пить', 'Сок пожалуйста', 'Печенье', 'Фрукт', 'Ещё', 'Всё', 'Вкусно'],
    uk: ['Перекус', 'Хочу пити', 'Сік будь ласка', 'Печиво', 'Фрукт', 'Ще', 'Все', 'Смачно'],
    de: ['Snack bitte', 'Ich habe Durst', 'Saft bitte', 'Keks', 'Obst', 'Mehr', 'Fertig', 'Lecker'],
    ja: ['おやつ', 'のどかわいた', 'ジュースください', 'クッキー', 'くだもの', 'もっと', 'おしまい', 'おいしい'],
    ko: ['간식 주세요', '목말라요', '주스 주세요', '쿠키', '과일', '더요', '다 먹었어요', '맛있어요'],
    zh: ['要零食', '我渴了', '果汁', '饼干', '水果', '还要', '吃完了', '好吃'],
    ar: ['وجبة خفيفة', 'أنا عطشان', 'عصير من فضلك', 'بسكويت', 'فاكهة', 'المزيد', 'انتهيت', 'لذيذ'],
  },
  outdoors: {
    en: ['Look!', "Let's go", 'I see a bird', 'Hot outside', 'Cold outside', 'I want to go home', 'Play outside', 'Swing'],
    bn: ['দেখো!', 'চলো যাই', 'পাখি দেখতে পাচ্ছি', 'বাইরে গরম', 'বাইরে ঠান্ডা', 'বাড়িতে যেতে চাই', 'বাইরে খেলি', 'দোলনা'],
    sw: ['Tazama!', 'Twende', 'Ninaona ndege', 'Nje ni moto', 'Nje ni baridi', 'Nataka kwenda nyumbani', 'Cheza nje', 'Xilipia'],
    am: ['ተመልከት!', 'እንሂድ', 'ወፍ አያለሁ', 'ውጪ ይሞቃል', 'ውጪ ይበርዳል', 'ወደ ቤት መሄድ እፈልጋለሁ', 'ውጪ መጫወት', 'ኡஞ்சሊሽ'],
    es: ['¡Mira!', 'Vamos', 'Veo un pájaro', 'Hace calor', 'Hace frío', 'Quiero ir a casa', 'Jugar afuera', 'Columpio'],
    ru: ['Смотри!', 'Пойдём', 'Вижу птицу', 'Жарко', 'Холодно', 'Хочу домой', 'Играть на улице', 'Качели'],
    uk: ['Дивись!', 'Ходімо', 'Бачу пташку', 'Спекотно', 'Холодно', 'Хочу додому', 'Грати надворі', 'Гойдалка'],
    de: ['Schau!', 'Los gehts', 'Ich sehe einen Vogel', 'Heiß draußen', 'Kalt draußen', 'Ich will nach Hause', 'Draußen spielen', 'Schaukel'],
  },
  reading: {
    en: ['Read more', 'Turn the page', "What's that word?", 'I like this book', 'Read again', 'New book', 'Show me', 'Point to it'],
    bn: ['আরও পড়ো', 'পাতা উল্টাও', 'ওটা কী শব্দ?', 'এই বইটা ভালো লাগছে', 'আবার পড়ো', 'নতুন বই', 'আমাকে দেখাও', 'আঙুল দিয়ে দেখাও'],
    sw: ['Soma zaidi', 'Geuza ukurasa', 'Neno gani hili?', 'Napenda kitabu hiki', 'Soma tena', 'Kitabu kipya', 'Nionyeshe', 'Onyesha hapo'],
    am: ['ተጨማሪ አንብብ', 'ገጹን ገልብጠው', 'ያ ቃል ምንድን ነው?', 'ይህን መጽሐፍ ወድጄዋለሁ', 'ድጋሚ አንብብ', 'አዲስ መጽሐፍ', 'አሳየኝ', 'ጠቁምበት'],
    es: ['Lee más', 'Pasa la página', '¿Qué palabra es?', 'Me gusta este libro', 'Lee otra vez', 'Libro nuevo', 'Muéstrame', 'Señala'],
    ru: ['Читай дальше', 'Переверни страницу', 'Что за слово?', 'Мне нравится книга', 'Читай ещё', 'Новая книга', 'Покажи', 'Укажи'],
    uk: ['Читай далі', 'Переверни сторінку', 'Що за слово?', 'Мені подобається книга', 'Читай ще', 'Нова книга', 'Покажи', 'Вкажи'],
    de: ['Weiter lesen', 'Seite umblättern', 'Was ist das Wort?', 'Ich mag dieses Buch', 'Nochmal lesen', 'Neues Buch', 'Zeig mir', 'Zeig drauf'],
  },
};

export function getVisionPhrases(scene: SceneType, lang: SupportedLanguage): string[] {
  const scenePhrases = VISION_PHRASES[scene];
  if (!scenePhrases) return [];
  return scenePhrases[lang] ?? scenePhrases['en'] ?? [];
}
