/**
 * Language allowlist gate — single source of truth for "is this word
 * allowed in this language's UI?"
 *
 * Background: prism-aac's prediction pipeline merges several sources
 * (curated per-lang corpus, default-phrase seed, clinical vocab, user
 * n-grams, AI completions). For non-EN languages, English words leak
 * in from multiple vectors:
 *   - default phrases without translation fall back to English text
 *   - the user's prior English typing populates a global wordFreq
 *   - the autocorrect /text/correct route can return English
 *     completions for English-looking input even when lang=ro
 *
 * Earlier attempts used:
 *   1. SCRIPT_FILTER (regex per script) — fails for Latin-script
 *      non-English (RO/ES/FR/DE/PT) because EN words look the same.
 *   2. EN_STOPWORDS list — works for known stopwords but misses any
 *      English noun the user happens to see (the user kept hitting
 *      new leaks like "Main", "noise", "to" — each requiring a list
 *      bump → bandaid forever).
 *
 * Structural fix: positive allowlist using the curated lang corpus
 * as truth. The corpus is auto-generated by training/build_prediction_seeds.py
 * from real per-language data — it has 5759 RO words, 5000+ for every
 * supported lang. If a candidate word ISN'T in this corpus AND doesn't
 * contain a language-specific diacritic, it's foreign-language pollution
 * — drop it.
 *
 * Diacritic carve-out: a user-typed proper noun like "Mihăilescu"
 * (uncommon, not in corpus) shouldn't be filtered just because it's
 * absent from the curated set. So we accept anything that contains a
 * lang-specific diacritic as a generous escape hatch — keeps user
 * names, places, etc.
 */
import { getCachedPredictionSeed, loadPredictionSeed, SUPPORTED_SEED_LANGS } from '@/constants/predictionSeeds';

/** Per-language diacritic regex — accepted as "looks like this lang"
 *  even when the word isn't in the curated corpus. EN has none (so
 *  EN allows everything via the lang === 'en' bypass). Non-Latin
 *  scripts (ru/uk/ar/ja/ko/zh) use the script-character regex
 *  directly — any character matching the script is accepted. */
const LANG_ACCEPT_REGEX: Record<string, RegExp> = {
  ro: /[ăâîșțşţĂÂÎȘȚŞŢ]/,
  es: /[ñáéíóúüÑÁÉÍÓÚÜ]/,
  fr: /[àâäçéèêëîïôœùûüÿÀÂÄÇÉÈÊËÎÏÔŒÙÛÜŸ]/,
  de: /[äöüßÄÖÜ]/,
  pt: /[áàâãçéêíóôõúÁÀÂÃÇÉÊÍÓÔÕÚ]/,
  it: /[àèéìíîòóùúÀÈÉÌÍÎÒÓÙÚ]/,
  pl: /[ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]/,
  nl: /[áéíóúëïöüÁÉÍÓÚËÏÖÜ]/,
  tr: /[çğıöşüÇĞİÖŞÜ]/,
  vi: /[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ]/i,
};

/** Strict per-script regex for non-Latin languages. A pure non-Latin
 *  script word is unambiguously in that language. */
const SCRIPT_FILTER: Record<string, RegExp> = {
  ru: /^[а-яё'\-]+$/i,
  uk: /^[а-яєіїґ'\-]+$/i,
  ar: /^[؀-ۿݐ-ݿ'\-]+$/,
  ja: /^[぀-ゟ゠-ヿ一-鿿]+$/,
  ko: /^[가-힯ᄀ-ᇿ㄰-㆏]+$/,
  'zh-Hans': /^[一-鿿]+$/,
  'zh-Hant': /^[一-鿿]+$/,
  'zh-HK': /^[一-鿿]+$/,
  he: /^[֐-׿'\-]+$/,
  hi: /^[ऀ-ॿ'\-]+$/,
};

/** Eagerly preload BOTH the target lang's corpus AND the English
 *  corpus so isAllowedInLang has the cross-lang frequency data it
 *  needs synchronously. Always returns a Promise so callers can
 *  reliably await — even when both corpora are already cached
 *  (returns Promise.resolve()). The previous version returned null
 *  in the cached path, which let callers think there was nothing to
 *  wait for and continue rendering before BOTH corpora were loaded
 *  (English wasn't preloaded at all → cross-lang freq compare ran
 *  with enFreq=0 → fail-open → English words flashed in the bar).
 */
export function ensureLangCorpusLoaded(lang: string): Promise<void> {
  const targets: Promise<unknown>[] = [];
  if (SUPPORTED_SEED_LANGS.includes(lang as never) && !getCachedPredictionSeed(lang)) {
    targets.push(loadPredictionSeed(lang));
  }
  // Always ensure EN is loaded too — it's the comparison corpus for
  // every Latin-script non-EN cross-lang check.
  if (!getCachedPredictionSeed('en')) {
    targets.push(loadPredictionSeed('en'));
  }
  if (targets.length === 0) return Promise.resolve();
  return Promise.all(targets).then(() => undefined);
}

/** Latin-script languages that participate in the cross-corpus
 *  domination comparison. The current lang is removed from this list
 *  at check time so we compare against everything else. */
const LATIN_LANGS = ['en', 'ro', 'es', 'fr', 'de', 'pt', 'it', 'pl', 'nl', 'tr', 'vi'] as const;

/** True when `word` is allowed for `lang`. Decision tree:
 *
 *    1. Empty/whitespace → keep
 *    2. Non-Latin script lang → strict character regex
 *    3. Latin-script word → diacritic carve-out (unambiguous lang
 *       word if it has lang-specific accent)
 *    4. Latin-script word, no diacritic → CROSS-CORPUS FREQUENCY
 *       comparison: allowed iff target lang's frequency dominates
 *       every OTHER loaded Latin-script corpus.
 *
 *  Why ALL Latin corpora and not just EN: the user's prediction bar
 *  in EN mode showed `eu` (Romanian for "I") leaking from the RO
 *  corpus — comparing only against EN missed the inverse-direction
 *  leak (RO → EN). The cross-corpus check is now symmetric: a word
 *  belongs to lang X iff X's freq beats every other lang's freq for
 *  it. This applies to EN too — `eu` has en_freq~0 vs ro_freq~3 →
 *  drop in EN mode.
 *
 *  Why frequency comparison and not simple corpus presence: corpora
 *  are auto-generated and contain some cross-language noise — e.g.,
 *  "main" appears in the RO corpus with count=10 (training-data
 *  contamination) but is overwhelmingly English. Presence-only
 *  check would let "main" through. Comparing en_freq=high vs
 *  ro_freq=10 catches it: "main" → drop in RO mode.
 *
 *  Returns true when no corpora are loaded (fail-open). The lazy
 *  load is fired by ensureLangCorpusLoaded on language switch;
 *  production callers always have target+EN loaded by render time.
 *  Tests should `await loadPredictionSeed(lang)` +
 *  `await loadPredictionSeed('en')` in beforeEach to make the gate
 *  strict. To pin against a specific competing lang (e.g. RO leak
 *  in EN mode), preload that competing lang's seed too.
 */
export function isAllowedInLang(word: string, lang: string): boolean {
  if (!word) return true;
  const w = word.toLowerCase().trim();
  if (!w) return true;

  // Non-Latin: pure-script check is sufficient.
  const strict = SCRIPT_FILTER[lang];
  if (strict) return strict.test(w);

  // Latin-script: diacritic = unambiguous accept for this lang.
  const accept = LANG_ACCEPT_REGEX[lang];
  if (accept && accept.test(word)) return true;

  // n-gram path: split on `|` and check each component.
  if (w.includes('|')) {
    return w.split('|').every((part) => part === '' || isAllowedInLang(part, lang));
  }

  // Multi-word phrase path. AAC core defaults include lemma forms like
  // "Mai Mult", "A vrea", "A ajuta" (RO) — single tokens with internal
  // spaces. Without this branch, every default phrase looked up as one
  // word against the corpus → langFreq=0 → dropped. Result: PredictionBar
  // showed only the single-word defaults ("Eu", "Tu") and silently
  // dropped the rest (May 2026 user report: "only 2 tiles in RO").
  //
  // Rule: a phrase is allowed iff every NON-TRIVIAL component word is
  // allowed. "Trivial" = 1-2 chars (e.g. RO "a" = infinitive marker,
  // EN "a" = article — these tokens are too short for the cross-corpus
  // frequency check to be meaningful; English's article-frequency for
  // "a" dominates every Romanian phrase that uses it). The longer
  // distinguishing words ("vrea", "ajuta", "Mult", etc.) carry the
  // language signal — if they pass, the phrase is fine. A pure-trivial
  // phrase ("a a") falls back to per-token resolution and stays
  // conservative.
  if (/\s/.test(w)) {
    const parts = w.split(/\s+/).filter((p) => p !== '');
    if (parts.length === 0) return true;
    const significant = parts.filter((p) => p.length > 2);
    if (significant.length === 0) {
      // No long tokens to anchor on → fall back to strict every-part rule.
      return parts.every((p) => isAllowedInLang(p, lang));
    }
    return significant.every((p) => isAllowedInLang(p, lang));
  }

  const langCorpus = getCachedPredictionSeed(lang);
  const langFreq = langCorpus?.wordFreq[w]?.count ?? 0;

  // CRITICAL fail-open: if the TARGET lang's corpus hasn't loaded yet,
  // the cross-corpus comparison is meaningless. EN is preloaded
  // eagerly by ensureLangCorpusLoaded, so without this guard we'd see
  // langFreq=0 (target absent) vs enFreq>0 (target's natural words
  // happen to appear once or twice in EN) → dominatedByOther = true →
  // EVERY Romanian word filtered out → empty PredictionBar during the
  // boot race window. The user-visible regression: "no predictions
  // appear in RO mode" (May 2026 report). The previous guard only
  // fired when NO corpora at all were loaded — useless because EN
  // always loads first. Now the guard fires whenever the TARGET lang
  // is missing, which is the only state where the comparison is
  // actually undefined. Once the target's seed lands, the strict
  // check resumes on the next render.
  if (!langCorpus) return true;

  // Cross-corpus comparison: if any OTHER loaded Latin-lang corpus
  // has a higher frequency for this word, the word belongs to that
  // other lang — drop it from this lang's predictions.
  let dominatedByOther = false;
  let foundInAnyCorpus = langFreq > 0;
  for (const otherLang of LATIN_LANGS) {
    if (otherLang === lang) continue;
    const otherCorpus = getCachedPredictionSeed(otherLang);
    if (!otherCorpus) continue;
    const otherFreq = otherCorpus.wordFreq[w]?.count ?? 0;
    if (otherFreq > 0) foundInAnyCorpus = true;
    if (otherFreq > langFreq) {
      dominatedByOther = true;
      break;
    }
  }

  // Some other lang has a higher frequency → drop.
  if (dominatedByOther) return false;

  // Target lang has the highest freq among loaded corpora → keep.
  if (langFreq > 0) return true;

  // Word not in ANY loaded corpus → could be a user proper noun.
  // Without diacritic evidence, drop conservatively. The diacritic
  // carve-out above already preserved real proper nouns with accents.
  if (foundInAnyCorpus) return false;
  return false;
}
