/**
 * Language allowlist gate — single source of truth for "is this word
 * allowed in this language's UI?"
 *
 * Background: prism-aac's prediction pipeline merges several sources
 * (curated per-lang corpus, default-phrase seed, clinical vocab, user
 * n-grams, AI completions). For non-EN languages, English words leak
 * in from multiple vectors:
 *   - default phrases without translation fall back to English text
 *   - the user's prior English typing populates a global wordFreq
 *   - the autocorrect /text/correct route can return English
 *     completions for English-looking input even when lang=ro
 *
 * Earlier attempts used:
 *   1. SCRIPT_FILTER (regex per script) — fails for Latin-script
 *      non-English (RO/ES/FR/DE/PT) because EN words look the same.
 *   2. EN_STOPWORDS list — works for known stopwords but misses any
 *      English noun the user happens to see (the user kept hitting
 *      new leaks like "Main", "noise", "to" — each requiring a list
 *      bump → bandaid forever).
 *
 * Structural fix: positive allowlist using the curated lang corpus
 * as truth. The corpus is auto-generated by training/build_prediction_seeds.py
 * from real per-language data — it has 5759 RO words, 5000+ for every
 * supported lang. If a candidate word ISN'T in this corpus AND doesn't
 * contain a language-specific diacritic, it's foreign-language pollution
 * — drop it.
 *
 * Diacritic carve-out: a user-typed proper noun like "Mihăilescu"
 * (uncommon, not in corpus) shouldn't be filtered just because it's
 * absent from the curated set. So we accept anything that contains a
 * lang-specific diacritic as a generous escape hatch — keeps user
 * names, places, etc.
 */
import { getCachedPredictionSeed, loadPredictionSeed, SUPPORTED_SEED_LANGS } from '@/constants/predictionSeeds';

/** Per-language diacritic regex — accepted as "looks like this lang"
 *  even when the word isn't in the curated corpus. EN has none (so
 *  EN allows everything via the lang === 'en' bypass). Non-Latin
 *  scripts (ru/uk/ar/ja/ko/zh) use the script-character regex
 *  directly — any character matching the script is accepted. */
const LANG_ACCEPT_REGEX: Record<string, RegExp> = {
  ro: /[ăâîșțşţĂÂÎȘȚŞŢ]/,
  es: /[ñáéíóúüÑÁÉÍÓÚÜ]/,
  fr: /[àâäçéèêëîïôœùûüÿÀÂÄÇÉÈÊËÎÏÔŒÙÛÜŸ]/,
  de: /[äöüßÄÖÜ]/,
  pt: /[áàâãçéêíóôõúÁÀÂÃÇÉÊÍÓÔÕÚ]/,
  it: /[àèéìíîòóùúÀÈÉÌÍÎÒÓÙÚ]/,
  pl: /[ąćęłńóśźżĄĆĘŁŃÓŚŹŻ]/,
  nl: /[áéíóúëïöüÁÉÍÓÚËÏÖÜ]/,
  tr: /[çğıöşüÇĞİÖŞÜ]/,
  vi: /[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ]/i,
};

/** Strict per-script regex for non-Latin languages. A pure non-Latin
 *  script word is unambiguously in that language. */
const SCRIPT_FILTER: Record<string, RegExp> = {
  ru: /^[а-яё'\-]+$/i,
  uk: /^[а-яєіїґ'\-]+$/i,
  ar: /^[؀-ۿݐ-ݿ'\-]+$/,
  ja: /^[぀-ゟ゠-ヿ一-鿿]+$/,
  ko: /^[가-힯ᄀ-ᇿ㄰-㆏]+$/,
  'zh-Hans': /^[一-鿿]+$/,
  'zh-Hant': /^[一-鿿]+$/,
  'zh-HK': /^[一-鿿]+$/,
  he: /^[֐-׿'\-]+$/,
  hi: /^[ऀ-ॿ'\-]+$/,
};

/** Eagerly preload a lang's corpus so isAllowedInLang can answer
 *  synchronously. Call this when the user switches language so the
 *  allowlist is ready before predictions/aiCompletion fire. */
export function ensureLangCorpusLoaded(lang: string): Promise<void> | null {
  if (!SUPPORTED_SEED_LANGS.includes(lang as never)) return null;
  if (getCachedPredictionSeed(lang)) return null;
  return loadPredictionSeed(lang).then(() => undefined);
}

/** True when `word` is allowed for `lang`. Decision tree:
 *
 *    1. EN or unknown lang → always true (no filter)
 *    2. Non-Latin script lang → strict character regex
 *    3. Latin-script non-EN word → diacritic carve-out (real lang
 *       word for sure if it has lang-specific accent)
 *    4. Latin-script non-EN word, no diacritic → CROSS-LANGUAGE
 *       FREQUENCY comparison: word is allowed iff its frequency in
 *       the target lang's corpus DOMINATES its frequency in the
 *       English corpus.
 *
 *  Why frequency comparison and not simple corpus presence: the
 *  curated corpora are auto-generated from training data and contain
 *  some cross-language noise — e.g., "main" appears in the RO corpus
 *  with count=10 (probably scraped from a French/English-mixed text)
 *  but is overwhelmingly English. Presence-only check would let
 *  "main" through. Comparing en_freq vs ro_freq catches it: "main"
 *  has en_freq >> ro_freq → drop in RO mode.
 *
 *  Returns true when corpora haven't loaded yet (fail-open). The
 *  lazy load is fired by ensureLangCorpusLoaded on language switch;
 *  callers in production always have data loaded by the time tiles
 *  render. Tests should `await loadPredictionSeed('ro')` +
 *  `await loadPredictionSeed('en')` in beforeEach to make the gate
 *  strict.
 */
export function isAllowedInLang(word: string, lang: string): boolean {
  if (!word || lang === 'en') return true;
  const w = word.toLowerCase().trim();
  if (!w) return true;

  // Non-Latin: pure-script check is sufficient.
  const strict = SCRIPT_FILTER[lang];
  if (strict) return strict.test(w);

  // Latin-script non-EN: diacritic = unambiguous accept.
  const accept = LANG_ACCEPT_REGEX[lang];
  if (accept && accept.test(word)) return true;

  // n-gram path: split on `|` and check each component.
  if (w.includes('|')) {
    return w.split('|').every((part) => part === '' || isAllowedInLang(part, lang));
  }

  const langCorpus = getCachedPredictionSeed(lang);
  const enCorpus = getCachedPredictionSeed('en');

  // If neither corpus is loaded, fail-open. The lazy load fires on
  // language switch; production code always has both loaded by render
  // time.
  if (!langCorpus && !enCorpus) return true;

  const langFreq = langCorpus?.wordFreq[w]?.count ?? 0;
  const enFreq = enCorpus?.wordFreq[w]?.count ?? 0;

  // Only-in-EN → drop. Words like "I", "want", "hello", "noise"
  // appear in the EN corpus but not in the RO corpus → langFreq=0,
  // enFreq>0 → drop.
  if (langFreq === 0 && enFreq > 0) return false;

  // In both corpora → keep iff target lang's frequency dominates EN.
  // Catches noise entries like "main" (en=high, ro=10 → drop).
  // Threshold 1 (langFreq must be > enFreq) is conservative; corpus
  // noise typically has langFreq much smaller than enFreq, so the
  // simple comparison correctly rejects it. Real lang-only words
  // have enFreq=0 → fall through the previous branch.
  if (langFreq > 0 && enFreq > 0) return langFreq >= enFreq;

  // langFreq > 0, enFreq === 0 → unambiguous lang word, keep.
  if (langFreq > 0) return true;

  // Both 0 → not in any corpus. Could be a user proper noun. Without
  // diacritic evidence we can't tell — drop conservatively. (The
  // diacritic carve-out above already keeps user proper nouns with
  // accents.)
  return false;
}
