/**
 * Local fallback catalog.
 *
 * Mirrors the 13 items previously hardcoded in MarketplacePanel.CATALOG.
 * Used when the portal API is unreachable (offline) or has not been wired
 * yet (Phases 1-2). Phase 3 introduces a server-driven catalog and this
 * file becomes a fallback only.
 *
 * Adding a new entry here should NOT be the way new modules ship in
 * production — that's what the portal catalog is for. Use this list for
 * the bundled set that must be reachable even with no network.
 */
import type { ModuleManifest } from '../types';

export const LOCAL_CATALOG: ModuleManifest[] = [
  {
    slug: 'symbol-libraries',
    version: '1.0.0',
    kind: 'symbol-library',
    tier: 'free',
    category: 'symbols',
    nameKey: 'mp_symbol_libraries',
    descKey: 'mp_symbol_libraries_desc',
    icon: '📚',
    status: 'available',
  },
  {
    slug: 'board-templates',
    version: '1.0.0',
    kind: 'board-template',
    tier: 'free',
    category: 'vocab',
    nameKey: 'mp_board_templates',
    descKey: 'mp_board_templates_desc',
    icon: '📋',
    status: 'available',
  },
  {
    slug: 'vocab-my-core',
    version: '1.0.0',
    kind: 'vocab-set',
    tier: 'free',
    category: 'vocab',
    nameKey: 'vs_my_core',
    descKey: 'vs_my_core_desc',
    icon: '⚡',
    status: 'available',
    handlerPayload: { vocabSetId: 'my-core' },
  },
  {
    slug: 'vocab-wordpower',
    version: '1.0.0',
    kind: 'vocab-set',
    tier: 'free',
    category: 'vocab',
    nameKey: 'vs_wordpower',
    descKey: 'vs_wordpower_desc',
    icon: '💪',
    status: 'available',
    handlerPayload: { vocabSetId: 'wordpower' },
  },
  {
    slug: 'vocab-gateway',
    version: '1.0.0',
    kind: 'vocab-set',
    tier: 'free',
    category: 'vocab',
    nameKey: 'vs_gateway',
    descKey: 'vs_gateway_desc',
    icon: '🚪',
    status: 'available',
    handlerPayload: { vocabSetId: 'gateway' },
  },
  {
    slug: 'vocab-aphasia',
    version: '1.0.0',
    kind: 'vocab-set',
    tier: 'free',
    category: 'vocab',
    nameKey: 'vs_aphasia',
    descKey: 'vs_aphasia_desc',
    icon: '🧠',
    status: 'available',
    handlerPayload: { vocabSetId: 'aphasia' },
  },
  {
    slug: 'vocab-social-chat',
    version: '1.0.0',
    kind: 'vocab-set',
    tier: 'free',
    category: 'vocab',
    nameKey: 'vs_social_chat',
    descKey: 'vs_social_chat_desc',
    icon: '💬',
    status: 'available',
    handlerPayload: { vocabSetId: 'social-chat' },
  },
  {
    slug: 'game-packs',
    version: '1.0.0',
    kind: 'game-pack',
    tier: 'free',
    category: 'games',
    nameKey: 'mp_game_packs',
    descKey: 'mp_game_packs_desc',
    icon: '🎮',
    status: 'available',
    handlerPayload: { entry: 'panel' },
  },
  {
    slug: 'voice-packs',
    version: '0.0.0',
    kind: 'voice-pack',
    tier: 'standard',
    category: 'voices',
    nameKey: 'mp_voice_packs',
    descKey: 'mp_voice_packs_desc',
    icon: '🎙',
    status: 'coming_soon',
  },
  {
    slug: 'picture-editor',
    version: '1.0.0',
    kind: 'panel',
    tier: 'standard',
    category: 'tools',
    nameKey: 'mp_picture_editor',
    descKey: 'mp_picture_editor_desc',
    icon: '🖼',
    status: 'available',
    handlerPayload: { panelId: 'picture-editor' },
  },
  {
    slug: 'music-composer',
    version: '1.0.0',
    kind: 'panel',
    tier: 'standard',
    category: 'tools',
    nameKey: 'mp_music_composer',
    descKey: 'mp_music_composer_desc',
    icon: '🎵',
    status: 'available',
    handlerPayload: { panelId: 'music-composer' },
  },
  {
    slug: 'aac-designer',
    version: '0.0.0',
    kind: 'panel',
    tier: 'advanced',
    category: 'tools',
    nameKey: 'mp_aac_designer',
    descKey: 'mp_aac_designer_desc',
    icon: '🎨',
    status: 'coming_soon',
    handlerPayload: { panelId: 'aac-designer' },
  },
  {
    slug: 'video-composer',
    version: '0.0.0',
    kind: 'panel',
    tier: 'advanced',
    category: 'tools',
    nameKey: 'mp_video_composer',
    descKey: 'mp_video_composer_desc',
    icon: '🎬',
    status: 'coming_soon',
    handlerPayload: { panelId: 'video-composer' },
  },

  // ─── Synalux first-party apps ─────────────────────────────────────────
  // Free tier so AAC users always have access — these are productivity tools,
  // not premium content. Launches into the live portal with the existing
  // session cookie carrying auth.
  {
    slug: 'synalux-mail',
    version: '1.0.0',
    kind: 'synalux-app',
    tier: 'free',
    category: 'apps',
    nameKey: 'mp_synalux_mail',
    descKey: 'mp_synalux_mail_desc',
    icon: '✉️',
    status: 'available',
    handlerPayload: { path: '/mail' },
  },
  {
    slug: 'synalux-drive',
    version: '1.0.0',
    kind: 'synalux-app',
    tier: 'free',
    category: 'apps',
    nameKey: 'mp_synalux_drive',
    descKey: 'mp_synalux_drive_desc',
    icon: '📂',
    status: 'available',
    handlerPayload: { path: '/drive' },
  },
  // Built-in feature surfaced for discovery. Free tier so the listing
  // shows up for everyone — provider-by-provider tier gating happens
  // inside the panel (see services/sendToContact.PROVIDER_MIN_TIER).
  {
    slug: 'aac-chat',
    version: '1.0.0',
    kind: 'builtin-shortcut',
    tier: 'free',
    category: 'tools',
    nameKey: 'mp_aac_chat',
    descKey: 'mp_aac_chat_desc',
    icon: '💬',
    status: 'available',
    handlerPayload: { builtin: 'aac-chat' },
  },
];
